### ISSUE TITLE
邮件测试问题

### ISSUE THREAD

**Issue by requestdeny** [sendya/shadowsocks-panel#102]
## 环境
**PHP** ：  5.6  有`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ：否

## 问题/错误信息
测试邮件的时候，邮件是发出去了了，但是右上角提示
系统错误
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.mail_queue' doesn't exist
注册也不行

**Comment by Acris** [comment]
@requestdeny 程序版本是最新版？有没有执行`php index.php install`?

**Comment by requestdeny** [comment]
@Acris git的最新版。 install也执行了

**Comment by sendya** [comment]
@requestdeny 请把 install 执行结果贴出来，谢谢。

**Comment by requestdeny** [comment]
@sendya Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...

dir=$(d=${0%[/\\]*}; cd "$d"; cd '../robmorgan/phinx/bin' && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
	# Cygwin paths start with /cygdrive/ which will break windows PHP,
	# so we need to translate the dir path to windows format. However
	# we could be using cygwin PHP which does not require this, so we
	# test if the path to PHP starts with /cygdrive/ rather than /usr/bin
	if [[ $(which php) == /cygdrive/* ]]; then
		dir=$(cygpath -m "$dir");
	fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phinx" "$@"
Now installing resources...
Deleting old resources...  
Done.
Copying resources...
All done~ Cheers! open http://yourdomain.com/
