### ISSUE TITLE
后台修改用户账户过期时间后，用户还是可以使用

### ISSUE THREAD

**Issue by Nuono** [sendya/shadowsocks-panel#103]
## 环境
**PHP** ：  5.6.21  有装`OpCache`
**NGINX** ： 1.10.0
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
后台修改用户账户过期时间后，用户还是可以使用

**Comment by sendya** [comment]
@Nuono 有执行计划任务吗？

**Comment by Nuono** [comment]
@sendya  是WIKI安装教程里的CRON计划任务配置么？如果是，有按教程做过奥。

**Comment by sendya** [comment]
@Nuono `在确定程序能正常访问之后，在进行CRON计划任务配置`

是按照这句话来的吗..

**Comment by Nuono** [comment]
恩...正常运行半个月了，都是朋友在用所以没有注意到这个问题。刚才又重复了一遍计划任务配置，还是这样。不过我貌似是1.14版的不是最新的。

看了下后台计划任务显示
#stopExpireUser	自动停止超流/到期用户	2016-04-28 21:13:28	运行完毕	30

貌似这个一直没运行...

**Comment by sendya** [comment]
@Nuono 那就是没运行啊， 检查计划任务服务有没开启

**Comment by Nuono** [comment]
啊啊啊啊，发现问题了！十分抱歉，是我#了，https://yourdomain.com/cron  没发现是https.....。

**Comment by Nuono** [comment]
啊啊啊啊，发现问题了！十分抱歉，是我#了，https://yourdomain.com/cron  没发现是https.....。
