### ISSUE TITLE
ss数据库信息在哪里？

### ISSUE THREAD

**Issue by BorLee** [sendya/shadowsocks-panel#109]
测试SS的时候提示数据表不存在，请问数据库备份是哪个？

**Comment by sendya** [comment]
在你的`MySQL`数据库里...
具体在哪里，看你安装在那个库就在哪里。程序没有 `.sql` 文件，不需要手动导入SQL,必须正规执行安装命令自动安装程序，才会创建数据库表以及默认数据参数。

**Comment by BorLee** [comment]
好的 谢谢
