### ISSUE TITLE
ss manyuser 多用户频繁挂掉，screen -r提示 screen is terminating,怎么解决啊

### ISSUE THREAD

**Issue by leehost** [sendya/shadowsocks-panel#11]

**Comment by sendya** [comment]
哪个版本，我稳定运行半个月以上 没遇到一台崩溃的

**Comment by sendya** [comment]
还有，screen 不工作，有可能是你哪里操作错误，或者资源占用过多导致被系统kill

**Comment by sendya** [comment]
请提供ss manyuser使用哪个版本

系统版本

**Comment by leehost** [comment]
郁闷死了，天天断，我再看看吧，自动暂停

- 发送自我的Sony Xperia™智能手机


---- Anan Yang编写 ----


还有，screen 不工作，有可能是你哪里操作错误，或者资源占用过多导致被系统kill

**Comment by sendya** [comment]
还有，认真阅读 README.md 你可能会有收获，在 第4项 安装多用户服务端 处
