### ISSUE TITLE
关于cat和ss-panel

### ISSUE THREAD

**Issue by ayooay** [sendya/shadowsocks-panel#111]
Hello,
这个项目比ss-panel看着舒服多了，但是我现在遇到一个问题。
因为ss-panel和cat的表很多都不一样。而我ss用的是shadowsocks-go  mu.
有没有好点的方法把ss-panel的数据导入cat，还有mu可以接入吗？

**Comment by sendya** [comment]
详细见 [常见问题与解答（FAQ）](https://github.com/sendya/shadowsocks-panel/wiki/FAQ)  

Q. 可以从 `orvice/ss-panel` 迁移到本面板吗?

> 不行，暂不支持。

并不支持ss-panel的web api
