### ISSUE TITLE
安装好了,打开主页有错误信息.

### ISSUE THREAD

**Issue by genics** [sendya/shadowsocks-panel#113]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
打开主页后出现这些.
Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/shadowsocks-panel/Package/autoload.php) is not within the allowed path(s): (/home/wwwroot/shadowsocks-panel/Public:/tmp/:/proc/) in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

Warning: require(/home/wwwroot/shadowsocks-panel/Package/autoload.php): failed to open stream: Operation not permitted in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

Fatal error: require(): Failed opening required '/home/wwwroot/shadowsocks-panel/Package/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

**Comment by sendya** [comment]
@genics `php.ini` 中，把 `open_basedir` 项配置屏蔽

**Comment by genics** [comment]
感谢回复,照你说的做了,还是没用啊.

; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file.
; http://php.net/open-basedir
;open_basedir =

; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions = open_basedir,passthru,chroot,chgrp,chown,proc_open,proc_get_status,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server,fsocket,popen

**Comment by genics** [comment]
好吧,我也不知道是不是lnmp的user.ini的问题,最后还是打开open_basedir.设置了相应目录解决了问题,留下给相同问题的兄弟参考吧.

**Comment by sendya** [comment]
然而我并不推荐用一键包

**Comment by genics** [comment]
一建包方便啊.

**Comment by sendya** [comment]
@genics 方便不方便跟我没关系，这程序对环境要求很正规。 正规环境才能保证其正常运行

**Comment by genics** [comment]
明白,明白.谢谢~
