### ISSUE TITLE
安装成功后无法代理.

### ISSUE THREAD

**Issue by cheny95** [sendya/shadowsocks-panel#114]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.10.1
**MYSQL** ：10.1.14-MariaDB
**是否为升级程序** ： 否
**PHP**
PHP 7.0.7 (cli) (built: May 31 2016 11:35:29) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
**MYSQL** 
mysql  Ver 15.1 Distrib 10.1.14-MariaDB, for Linux (x86_64) using readline 5.1
**NGINX** 
nginx version: nginx/1.10.1
**Linux CentOS**
CentOS Linux release 7.2.1511 (Core) //
Linux version 2.6.32-042stab111.11 (root@kbuild-rh6-x64.eng.sw.ru) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Tue Sep 1 18:19:12 MSK 2015

**进程**
![image](https://cloud.githubusercontent.com/assets/6293952/16513016/8c878556-3f93-11e6-8a31-09926239d4e8.png)
## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
Nginx,MySQL,PHP全部运行正常,后台登录正常,操作正常,就是SS连不上,无法代理.
安装没有报错,按照Wiki页面安装的,设置也是一样设置的.(不过PHP源换了,因为你提供的源下载不下来...)
服务器是bandwagon的,请问我是哪里做的不对吗?还是服务器不支持? 

劳烦解答,感谢!

**Comment by sendya** [comment]
自己看是不是防火墙端口之类的没开，

**Comment by cheny95** [comment]
@sendya 我刚才把firewall禁用了还是连不上.但是前端服务都正常,死循环懵逼ing...想不到哪里出错了.😂

**Comment by cheny95** [comment]
已经处理好了,多谢.
重新按照教程安装了一次,前一次也不知道哪个环节出了问题...
