### ISSUE TITLE
套餐卡充值时间叠加

### ISSUE THREAD

**Issue by lezaijjh** [sendya/shadowsocks-panel#116]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

系统设置中的套餐卡充值时间叠加开关是什么意思？

**Comment by sendya** [comment]
升级套餐后的时间是否叠加

**Comment by Acris** [comment]
@sendya 系统设置里面有开关可以控制。
