### ISSUE TITLE
404页面有错误代码

### ISSUE THREAD

**Issue by ju0594** [sendya/shadowsocks-panel#12]
Catchable fatal error: Argument 1 passed to Core\Error::handleUncaughtException() must be an instance of Throwable, instance of Core\Error given, called in /home/wwwroot/speed.vlink.xyz/Library/Core/Error.php on line 50 and defined in /home/wwwroot/speed.vlink.xyz/Library/Core/Error.php on line 57

不知道是不是Bug还是我的问题。

还有就是今天安装的时候user_power表里uid是5000 member表里id为1的用户端口是1 这两个好像是反了 我手动改过来就正常了

**Comment by sendya** [comment]
1. 这个问题是在做什么操作的时候出现的问题？
（你的php版本是 7 以下的吧?）

2. 可能第一个账户注册的判断有问题，我下午查一下
INSERT INTO `user_power` (`id`, `uid`) VALUES ('1', '5000');

**Comment by ju0594** [comment]
php 5.5.25 错误就是没有404页面…这个页面是要手动配置吗？我nginx里就配置了重写，其他没动。

**Comment by sendya** [comment]
@ju0594 你安装的哪一个版本  PHP5分支？还是 master 分支

**Comment by sendya** [comment]
@ju0594 我提交了一下修正，你尝试 `git pull` 同步代码一下。
修正于 [issue #12](https://github.com/sendya/shadowsocks-panel/commit/91a942d56f4ca359d8c5306ee64326e7f22a95b0) - Sendya

**Comment by ju0594** [comment]
还有个问题 手机端看Pro节点是这样的
- Vultr-日本
地址: s1.sscat.it 
可用 aes-128-cfb 
地址和加密都不是设定的，普通节点没问题。

**Comment by ju0594** [comment]
@sendya 我用的master分支 现在是[这样的](http://speed.vlink.xyz/test)
还有个Pro节点的问题有空也看下。

**Comment by sendya** [comment]
@ju0594  节点显示问题修好了 详细看 [Fixed issue #12(Pro node show error)](https://github.com/sendya/shadowsocks-panel/commit/6b9f1923c0e001c53f7c1bb6276e78ceaa951b4b)

**Comment by ju0594** [comment]
@sendya pro节点可以了，404可以正常显示但是还有错误代码，见我的[点这里查看](http://speed.vlink.xyz/404test)
顺便问下消息通知是不是还在开发？怎么才能让登陆后浮动通知显示我要的内容？

**Comment by sendya** [comment]
@ju0594 后台消息设置自己改

**Comment by sendya** [comment]
@ju0594 错误代码隐藏  配置文件里面有一个 DEBUG 模式 ，设置为 false 就可以了，顺便把 TEMPLATE_UPDATE 也设置为 false

**Comment by ju0594** [comment]
@sendya 404弄好了，消息的话能创建不能删除，显示request failed。
并且设置推送后，用户回收到两条一模一样的消息…

**Comment by sendya** [comment]
@ju0594 消息类型不要控制为 -4  那是系统消息 。属于不能删除的，系统消息就那三条 不允许改变

**Comment by ju0594** [comment]
@sendya 我之前在数据库删了这三条，怪不得，现在重新导入正常了。
还有几个小问题，我再开个issue。
