### ISSUE TITLE
关于端口号的问题

### ISSUE THREAD

**Issue by waymao** [sendya/shadowsocks-panel#120]
## 环境
**PHP** ：  5.6  有/无装`OpCache`
**NGINX** ： 1.6.4
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

更换系统端口后，部分链接仍然不带端口号，导致许多功能无法正常运行。

**Comment by sendya** [comment]
@waymao 表述清楚点 `更换系统端口后，部分链接仍然不带端口号`    更换什么端口？  什么链接？

**Comment by waymao** [comment]
web服务的端口号

**Comment by waymao** [comment]
nginx的端口号不是默认

**Comment by sendya** [comment]
用 80 / 443
