### ISSUE TITLE
网站打开缓慢，另外网站的首页界面可不可去掉

### ISSUE THREAD

**Issue by 1558204459** [sendya/shadowsocks-panel#121]
网站打开缓慢
从登陆到打开后台经过几十秒，这个和cron有关系吗？我用的PHP5.6

另外网站的首页界面可不可有选择的去掉
感觉网站首页太个性，可不可以去掉网站首页

**Comment by sendya** [comment]
@1558204459 1. 网站打开慢 你自己机子问题，自行解决。
2. CRON不会影响程序的访问，但是关闭会导致程序失去至少40%功能
3. 首页爱怎么弄随便你，现在源代码在你手里，无人能管

**Comment by 1558204459** [comment]
额，在打开网页的时候我发现服务器 CPU使用率很低，但是就是一直在那等待跳转到下一个页面
