### ISSUE TITLE
安装报错　Base table or view already exists: 1050 Table 'cron' already exists  

### ISSUE THREAD

**Issue by nqzhang** [sendya/shadowsocks-panel#124]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
安装报错出现这个
Now installing dependencies...
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...

                                                                                        
  [PDOException]                                                                        
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cron' already exists  
                                                                                        

migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE]

FAILED! migrate database wrong. Please run command: ./Package/bin/phinx migrate

然后执行
./Package/bin/phinx migrate
出现这个
Phinx by Rob Morgan - https://phinx.org. version 0.5.3

using config file ./phinx.php
using config parser php
using migration path /www/test.feifeiss.com/Migrations
warning no environment specified, defaulting to: current
using database feifeiss

 == 20160406101626 CreateTable: migrating

                                                                                        
  [PDOException]                                                                        
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cron' already exists  
                                                                                        

migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE]

数据库是新建的

**Comment by sendya** [comment]
清空数据库重新执行安装 ，MYSQL必须高于5.5
