### ISSUE TITLE
账户到期问题

### ISSUE THREAD

**Issue by 1558204459** [sendya/shadowsocks-panel#125]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
账户到期后会在用户管理界面有提示吗？
有没有邮件提醒？
为什么我测试一个账户到期后，控制面板没有任何提示？
Crontab里加入了定时运行计划

**Comment by Acris** [comment]
@1558204459 会有邮件提醒

**Comment by sendya** [comment]
@1558204459 如果你的邮件服务器配置没问题，是会自动发送到期提示邮件到到期账户的邮箱上

**Comment by 1558204459** [comment]
邮件服务器没有问题，我只是把前端搭好了，shadowsocks-manyuser没有搭，我在后台将账户到期日期改为测试的日期，到期后没有提醒，打开后台也没有提示
