### ISSUE TITLE
配置完成后执行php index.php install  base url 错误

### ISSUE THREAD

**Issue by jameseroyi** [sendya/shadowsocks-panel#126]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
/data/config 里面的相关字段配置为：
```
/**
 * Base URL:
 * To manually config this, uncomment the following line and change the URL
 * To use auto detect, keep this commented
 */
define('BASE_URL', 'http://godwithjames.xyz');
//Core\Request::autoDetectBaseURL();
```
并且开启了rewrit 规则，并在nginx中该网站的vhost配置中添加了rewrite
执行php index.php install 出现下面结果

    All done~ Cheers! open site: http://godwithjames.xyzyourdomain.com/

想请教下哪里出错了

**Comment by sendya** [comment]
不要手动设定 **BASE_URL**！！！！  
不要手动设定 **BASE_URL**！！！！  
不要手动设定 **BASE_URL**！！！！  

使用 `Core\Request::autoDetectBaseURL();` 即可

**Comment by jameseroyi** [comment]
如果开启 https 也不用手动设定了是吗
