### ISSUE TITLE
测试邮件发送成功 但无法发送忘记密码邮件

### ISSUE THREAD

**Issue by frankwei98** [sendya/shadowsocks-panel#127]
## 环境
**PHP** ：  7.0.8  无装`OpCache`
**NGINX** ： 1.10.1
**MYSQL** ： 5.5.48
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
测试邮件发送平台有Mailgun 和 Sendgrid(SMTP)
配置完成后 Mailgun(API)和Sendgrid(SMTP)都可以正常发送测试邮件

但是一到了忘记密码就无法发送验证码了 虽然系统提醒发送成功 但是邮箱没收到 Mailgun 和 Sendgrid也没有相应的发送记录 
没有任何错误输出

**Comment by Acris** [comment]
@frankwei98 看下mailgun的log有没有投递出去

**Comment by frankwei98** [comment]
@Acris 没有和密码修改相关的邮件记录 全是测试邮件
![image](https://cloud.githubusercontent.com/assets/3261732/16905985/ca6c5b3e-4ce1-11e6-8fe8-1912a45cca6e.png)

**Comment by frankwei98** [comment]
通过SMTP发送的Sendgrid也一样
![image](https://cloud.githubusercontent.com/assets/3261732/16905999/066259e0-4ce2-11e6-8c3f-d778ce2eaf22.png)

**Comment by sendya** [comment]
没有执行计划任务。 测试邮件有两封，你也只收到一封

**Comment by frankwei98** [comment]
Thanks
