### ISSUE TITLE
外部ss服务器配置失败

### ISSUE THREAD

**Issue by BorLee** [sendya/shadowsocks-panel#128]
vultr 自带的centos7没有安装web任何组件就直接安装的ss-rm版
panel和ss-rm一套在linode上安装成功并且使用了很久，今天在vultr开了台最低配的vps，然后安装ss-rm做第二台节点试试速度，结果出现了错误。连接linode服务器是正常使用的。

下面是一些报告，根据Wiki安装流程，已经调试成功(密码做了处理，下同)
[root@vultr shadowsocks]# python servers.py
add: {"server_port": 5000, "password":"xxxxxxx", "method":"aes-256-cfb"}
add: {"server_port": 5002, "password":"1111111", "method":"aes-256-cfb"}
add: {"server_port": 5003, "password":"2222222", "method":"aes-256-cfb"}
add: {"server_port": 5004, "password":"3333333", "method":"aes-256-cfb"}
开了日志后查看如下，说实在的看不懂哪里出错了，进城守护那一步还设置。
[root@vultr shadowsocks]# cat /var/log/shadowsocks.log
2016, Aug 01 Mon 14:36:01 eventloop.py[line:251] DEBUG using event model: epoll
2016, Aug 01 Mon 14:36:02 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:36:03 dbtransfer.py[line:136] INFO db start server at port [5000] pass [xxxxxxx]
2016, Aug 01 Mon 14:36:03 manager.py[line:86] INFO adding server at 0.0.0.0:5000
2016, Aug 01 Mon 14:36:03 dbtransfer.py[line:136] INFO db start server at port [5002] pass [11111333]
2016, Aug 01 Mon 14:36:03 manager.py[line:86] INFO adding server at 0.0.0.0:5002
2016, Aug 01 Mon 14:36:03 dbtransfer.py[line:136] INFO db start server at port [5003] pass [22222222]
2016, Aug 01 Mon 14:36:03 manager.py[line:86] INFO adding server at 0.0.0.0:5003
2016, Aug 01 Mon 14:36:03 dbtransfer.py[line:136] INFO db start server at port [5004] pass [33333333]
2016, Aug 01 Mon 14:36:03 manager.py[line:86] INFO adding server at 0.0.0.0:5004
2016, Aug 01 Mon 14:36:19 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:36:35 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:36:51 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:37:06 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:37:22 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:37:38 dbtransfer.py[line:149] INFO db loop
2016, Aug 01 Mon 14:37:54 dbtransfer.py[line:149] INFO db loop

配置文件方面，数据库方面应该是设置正确的，不然调试的时候也不会读取到linode服务器上的账户信息，这一段看不太懂MANAGE_BIND_IP应该填什么？还有其他是否有错？
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333
#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'aes-256-cfb'

最后是ss客户端报错，一直都是超时和无效的用户名组合。

**Comment by BorLee** [comment]
守护进程也设置了反馈信息如下
[root@vultr shadowsocks]# systemctl status shadowsocks-rm
● shadowsocks-rm.service - Shadowsocks Proxy Services(shadowsocks-rm manyuser)
   Loaded: loaded (/etc/systemd/system/shadowsocks-rm.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-08-01 14:52:50 UTC; 1s ago
 Main PID: 9677 (python)
   CGroup: /system.slice/shadowsocks-rm.service
           └─9677 /usr/bin/python /home/shadowsocks-rm/shadowsocks/servers.py

Aug 01 14:52:50 vultr.guest systemd[1]: Started Shadowsocks Proxy Services(shadowsocks-rm manyuser).
Aug 01 14:52:50 vultr.guest systemd[1]: Starting Shadowsocks Proxy Services(shadowsocks-rm manyuser)...

SS客户端反馈
[2016-08-01 22:53:44] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()
[2016-08-01 22:53:47] 45.32.12.46:5011 timed out
[2016-08-01 22:53:47] 45.32.12.46:5011 timed out
[2016-08-01 22:53:47] 45.32.12.46:5011 timed out

**Comment by sendya** [comment]
并没有报错啊，哪里报错了

**Comment by BorLee** [comment]
所以才说啊，服务端全部正常，可是客户端就是连接不上，不知道为什么，客户端什么参数都没改，就把IP地址改成linode服务器的就正常上google，改回vultr服务器的就无法使用。。。

**Comment by sendya** [comment]
@BorLee 那就问你自己了呗，我又不是做ss服务端开发的。  你查查看是不是端口没开之类的

**Comment by BorLee** [comment]
一语惊醒梦中人，我去看了下端口。。vultr安装的centos7里5000那几个端口默认是不对外开放的。。linode默认是对外网开放的。。
