### ISSUE TITLE
smtp设置

### ISSUE THREAD

**Issue by sunyh87** [sendya/shadowsocks-panel#129]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
![qq 20160811181214](https://cloud.githubusercontent.com/assets/20852855/17585581/4a8e2552-5fef-11e6-9b19-46981acbef22.jpg)
这样设置对吗？点测试邮件 邮箱里没收到测试邮件啊，求指点

**Comment by sendya** [comment]
@sunyh87 点测试 有什么提示？

**Comment by sunyh87** [comment]
@sendya 
![image](https://cloud.githubusercontent.com/assets/20852855/17585886/06faa39a-5ff1-11e6-8556-775b2a68cddb.png)

**Comment by sunyh87** [comment]
大神回复的好快啊，不像orvice/ss-panel那么多问题扔那都没人理，而且他那有个BUG 用了出错比例太高，访问延迟厉害，更换后端也没用 换了大神的面板 这现象没有了

**Comment by sendya** [comment]
@sunyh87 我不是大神啊抱歉，

**Comment by sendya** [comment]
@sunyh87 还有 你截图返回后的提示 不要给我 请稍等，我也看不出是什么错。

**Comment by sunyh87** [comment]
@sendya 那这是设置问题，还是哪的问题，那个没用悬浮提示

**Comment by sunyh87** [comment]
@sendya 冒出这个
![image](https://cloud.githubusercontent.com/assets/20852855/17586226/f48fe07e-5ff2-11e6-8fb3-081d9f3ab373.png)

**Comment by sendya** [comment]
@sunyh87 你服务器商禁止SMTP了

**Comment by sendya** [comment]
@sunyh87 用代发

**Comment by Acris** [comment]
@sunyh87 或者QQ邮箱开启SMTP

**Comment by sendya** [comment]
@sunyh87 话说 qq的 mail 发信不是   `smtp.qq.com` ?

**Comment by sunyh87** [comment]
@Acris QQ里肯定开启了啊，发短信得到一个授权码 不用SMTP，那个代发咋设置啊，偶小白一个 低端问题还请谅解

**Comment by Acris** [comment]
@sunyh87 你邮件服务器地址写成 smtp.qq.com 试试

**Comment by Acris** [comment]
@sunyh87 http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=371
