### ISSUE TITLE
修改头像网址不对 最后使用时间不是24小时

### ISSUE THREAD

**Issue by ju0594** [sendya/shadowsocks-panel#13]
SS服务→修改头像
仪表盘→最后使用时间
还有就是邀请码能不能批量生成？
生成对应套餐的 流量也是对应的还是默认设置的10G？
最后 签到过去的流量在哪里设置呃…

**Comment by sendya** [comment]
04. 
```php
/**
 * Flow default value
 */
define('TRANSFER', 10);// Default flow 10GB
```

**Comment by ju0594** [comment]
@sendya 默认的这个知道 (`●__●ˊ) /

**Comment by sendya** [comment]
@ju0594 
1. 头像修改链接 (这玩意你作为站长，想改到什么地址都随意你，现在我把地址改为了 gravatar官方了
2. 最后使用时间格式已经调整为 24小时制
3. 邀请码没有批量功能，可能会在 `稳定版` 中增加这个功能（或许要不了多久，感谢提供这个意见
4. 生成套餐按照套餐等级赋予用户流量 修正。
当前方案是：
```php
A ： 10GB
B ： 50GB
C ： 150GB
D ： 300GB
VIP ： 500GB
```
如果有需要，你可以自行修改`Auth`类文件，路径为：`Controller\Auth.php` -> register() 第 128 行开始

签到流量 的控制当前没有独立出来，如果你阅读过源代码或者查看过目录结构，会发现一个 `Setting` 类，由于 系统设置 的类还没被设计出来，所以这个参数目前也被写死了。
其默认值为 `5MB ~ 25MB` ，若要修改。在 `Controller\Form.php` -> checkIn() 第 116 行

**Comment by ju0594** [comment]
@sendya 感谢！问题都得到了解决。

**Comment by ju0594** [comment]
@sendya 能不能帮我改下index.html，不要背景音乐，只要一张背景图片就行，其他照常。（不懂html）

**Comment by sendya** [comment]
@ju0594 不能，这个index是我自己的站点用的。 你自己想办法

**Comment by ju0594** [comment]
@sendya @_@ 好吧
