### ISSUE TITLE
邮件附件问题

### ISSUE THREAD

**Issue by BorLee** [sendya/shadowsocks-panel#130]
群里问过了，这里报备下。

邮件选择的是SMTP模式，发送正常。

出现的问题是，发送给其他邮件供应商都没问题，但是发送给outlook.com的邮件就会产生一个ATT00001.TXT的空白文件，而outlook.com的邮箱接收其他邮件都不会出现这种情况。

是否邮件代码需要优化？

**Comment by BorLee** [comment]
测试的其他邮件供应商有gmail.com和qq.com

**Comment by sendya** [comment]
代码里检查没有插入附件。 如果不行就换一种邮件发送方式试试？

**Comment by BorLee** [comment]
The ATT00001.txt file is a file generated as an attachment by Microsoft Outlook or Microsoft Exchange Server. The name ATT00001 is a generic file name and you’ll often see these in .htm format, .dat, and other extensions when there is some sort of compatibility issue between the sender and recipients Microsoft email program settings.
It is often the result of a MIME file being sent and because of a compatibility issue when the redundant / additional txt file gets generated and attached.  These Microsoft mail systems use Transport Neutral Encapsulation Format (TNEF) to pack and send this information, which is a proprietary format that sometimes leads to problems.
Was this added as a garbage attachment and has no content in it?
This file type is typically going to either be the plain text of the email or blank.  If its blank, you will need to check with the sender, as the attachment didn’t send properly and was replaced with this garbage/blank file.
Good luck.

来源：http://itknowledgeexchange.techtarget.com/itanswers/how-to-open-a-file/

**Comment by BorLee** [comment]
邮件发送的内容都是默认设置的没改过，应该是发送的格式让outlook产生误判了，这个问题对我没太大影响。如果你觉得没必要去解决的话就closed吧。

**Comment by sendya** [comment]
@BorLee 把 `ATT00001.txt` 文件下载发给我

**Comment by BorLee** [comment]
@sendya QQ上提示说无法发送空白文件，已经跟你说明。另外刚才测试了下
把Library/Helper/Mailer/smtp.php里这段

`        if (isset($this->_attachment)) {
            //含有附件的邮件头需要声明成这个
            $header .= "Content-Type: multipart/mixed;\r\n";
        } elseif (false) {
            //邮件体含有图片资源的,且包含的图片在邮件内部时声明成这个，如果是引用的远程图片，就不需要了
            $header .= "Content-Type: multipart/related;\r\n";
        } else {
            //html或者纯文本的邮件声明成这个
            $header .= "Content-Type: multipart/alternative;\r\n";
        }`

改成
`$header .= "Content-Type: multipart/alternative;\r\n";`
后，附件消失，但是所有右键都被outlook识别成垃圾邮件。

**Comment by sendya** [comment]
@BorLee 好的谢谢。 还有没必要死磕SMTP. 你可以自己实现任何想要的邮件发送方式。 也可以用已经对接好的另外三种方式
