### ISSUE TITLE
用户中心新增一个页面的问题

### ISSUE THREAD

**Issue by PftHost** [sendya/shadowsocks-panel#131]
如果在用户中心新建一个siteurl/bbs的页面，bbs.htm的文件建立后还需要修改那些配置文件？

我在template/Xenon/panel中建立了一个bbs.htm页面，但是使用siteurl/bbs无法访问；

请问还需要修改哪里的配置文件才可以使siteurl/bbs链接到template/Xenon/panel/bbs.htm？

谢谢！

**Comment by sendya** [comment]
@PftHost https://docs.ikk.me/kk-framework/QuickStart.html

**Comment by PftHost** [comment]
Thanks a lot~
