### ISSUE TITLE
续费后未被启用

### ISSUE THREAD

**Issue by xu988** [sendya/shadowsocks-panel#132]
## 环境
**PHP** ：  7    无装`OpCache`
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

一个用户因为到期停用后   使用了套餐卡续了时间    计划任务却没有重新把他启用？？？

**Comment by sendya** [comment]
@xu988 计划任务页面的执行时间都正常麻

**Comment by xu988** [comment]
@sendya  正常的

**Comment by xu988** [comment]
@sendya  也就是说原来的话是应该会启用的？？

**Comment by sendya** [comment]
@xu988 账户流量有超吗？

**Comment by xu988** [comment]
没有超    我知道了  是因为生成套餐的时候  套餐类型我用小写的了     /委屈

**Comment by xu988** [comment]
@sendya   真的是谢谢了  谢谢你的帮助  谢谢你这个项目

**Comment by sendya** [comment]
@xu988 没事
