### ISSUE TITLE
Have any plan to support php 7.1?请问有支持php 7.1 的计划吗？

### ISSUE THREAD

**Issue by cybmp3** [sendya/shadowsocks-panel#134]
## 环境
**PHP** ：  7.1.9  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： mariadb 10.1
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

All Done. Took 0.7198s
Now installing resources...
Deleting old resources...  
old resources not exist.
Copying resources...
All done~ Cheers! open site: http://yourdomain.com/

安装成功

打开主页显示

#!env php Sorry, This page is not available due to incorrect server configuration.

php -v
PHP 7.1.0beta2 (cli) (built: Aug  3 2016 11:59:34) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

**Comment by sendya** [comment]
**安装面板第二步骤**

> 请将`NGINX`/`Apache`的 网站根目录路径指向到 `Public` 而不是 `shadowsocks-panel` 目录（程序入口在 `/Public/index.php` 而非 `/index.php`）。
