### ISSUE TITLE
[安装问题] Failed to download composer binary!

### ISSUE THREAD

**Issue by shirohako** [sendya/shadowsocks-panel#136]
## 环境

**PHP** ：  7.0.10  无`OpCache`
**NGINX** ： 1.10.1
**MYSQL** ： 5.6.32
**是否为升级程序** ： 否
## 问题/错误信息

[root@abc shadowsocks-panel]# php index.php install
Downloading composer...Done!
PHP Notice:  Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 145

Notice: Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 145
PHP Warning:  exec() has been disabled for security reasons in /data/wwwroot/default/shadowsocks-panel/index.php on line 145

Warning: exec() has been disabled for security reasons in /data/wwwroot/default/shadowsocks-panel/index.php on line 145
PHP Notice:  Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 146

Notice: Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 146
PHP Warning:  Invalid argument supplied for foreach() in /data/wwwroot/default/shadowsocks-panel/index.php on line 120

Warning: Invalid argument supplied for foreach() in /data/wwwroot/default/shadowsocks-panel/index.php on line 120
PHP Notice:  Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 147

Notice: Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 147
PHP Notice:  Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 147

Notice: Undefined variable: return_arr in /data/wwwroot/default/shadowsocks-panel/index.php on line 147
**Failed to download composer binary!**

**Comment by Acris** [comment]
使用 `php -d disable_functions='' index.php install` 安装

**Comment by sendya** [comment]
这个问题不关闭了，就放在issue里，有遇到的自行尝试

**Comment by shirohako** [comment]
使用`php -d disable_functions='' index.php install`安装成功了，感谢
但是加载jquery和bootstrap失败了
看了下配置，资源文件应该是在Resource/主题/下，但是我Resource/Xenon/里什么也没有= =
是要自己准备吗

**Comment by sendya** [comment]
@shirohako 看 https://github.com/sendya/shadowsocks-panel/wiki

**Comment by Acris** [comment]
@shirohako 资源文件需要单独下载，请移步：https://github.com/sendya/shadowsocks-panel/releases
