### ISSUE TITLE
请问支持SSR后端吗,看了下，都是SS

### ISSUE THREAD

**Issue by afeng1991** [sendya/shadowsocks-panel#139]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
支持吗？

**Comment by sendya** [comment]
@afeng1991 https://github.com/sendya/shadowsocks-panel/wiki/shadowsocks-manyuser-%E5%AE%89%E8%A3%85%E4%B8%8E%E5%AF%B9%E6%8E%A5#%E5%85%B6%E4%BB%96%E7%89%88%E6%9C%AC

不支持

**Comment by afeng1991** [comment]
尚未支持的shadowsocks manyuser版本，请自行修改sql查询字符串即可与面板对接 

 我自己修改后,就可以用了？还是面板根本不支持。

**Comment by sendya** [comment]
@afeng1991 可以。 只要字段跟面板程序一样， 面板怎么限制支持或者不支持呢

**Comment by afeng1991** [comment]
关于计划任务
$ crontab -e
$ * * * * * /usr/bin/curl https://yourdomain.com/cron
# 保存退出
这个https://yourdomain.com/cron 是填写自己的域名，还是什么都不动？

**Comment by sendya** [comment]
@afeng1991 Your domain

**Comment by afeng1991** [comment]
* * * * * /usr/bin/curl
这个***代表什么呢。路径？

**Comment by sendya** [comment]
@afeng1991 

1. [crontab_百度搜索](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=0&rsv_idx=1&tn=baidu&wd=crontab&rsv_pq=d6c0e4f60003085f&rsv_t=c6bd3kXG8cHuVwluGop9r9zdrrNHR80C5ue6J4an%2BWF9yXQHR3q%2F681Ufnw&rqlang=cn&rsv_enter=1&rsv_sug3=4&rsv_sug1=4&rsv_sug7=100)
2. [curl_百度搜索](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=curl%20&oq=curl%20%E5%91%BD%E4%BB%A4&rsv_pq=94d0e1ef0003221c&rsv_t=9f75qQ1Uv0ifHu9cTDgsnjkRwOqEVNxn8oM1MeaZH5mlFSvLjCGMCCFZxYA&rqlang=cn&rsv_enter=1&inputT=598&rsv_sug3=7&rsv_sug1=6&rsv_sug7=100&rsv_sug2=0&rsv_sug4=599&rsv_sug=1)
3. [/bin、/sbin、/usr/bin、/usr/sbin目录的区别](http://www.2cto.com/os/201211/170994.html)
