### ISSUE TITLE
邮箱后缀超过4位就不给注册

### ISSUE THREAD

**Issue by kuertianshi** [sendya/shadowsocks-panel#14]
可能需要修改下正则吧，现在5位后缀的域名也挺多了

**Comment by sendya** [comment]
@kuertianshi `Helper\Util->MailFormatCheck()` 下的第一行代码，就是正则，你可以尝试自己改一下，或者等我的下一次 fixed issue

**Comment by kuertianshi** [comment]
@sendya 我没啥事 就是来提交下233

**Comment by sendya** [comment]
@kuertianshi 邮箱地址修正了  [Fixed mail check...more](https://github.com/sendya/shadowsocks-panel/commit/d2f5932b8a0ad5cdf4b825f7a960c1f70078ac45)
