### ISSUE TITLE
执行完rpm 发现yum 坏了

### ISSUE THREAD

**Issue by zxd882002** [sendya/shadowsocks-panel#140]
## 环境
**PHP** ：  没装
**NGINX** ： 1.10.1
**MYSQL** ： Ver 15.1 Distrib 10.1.17-MariaDB
**是否为升级程序** ： 否

## 问题/错误信息
我按照[CentOS7 LNMP环境,NGINX配置面板conf](https://github.com/sendya/shadowsocks-panel/wiki/CentOS7-LNMP%E7%8E%AF%E5%A2%83,NGINX%E9%85%8D%E7%BD%AE%E9%9D%A2%E6%9D%BFconf)下面的教程做，发现当我执行完下面这个命令之后，我的yum不能用了

> rpm -ivh https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm

下面是error log：

 # yum install -y php70u-fpm php70u-gd php70u-json php70
u-intl php70u-mbstring php70u-mcrypt php70u-mysqlnd php70u-opcache php70u-pdo ph
p70u-pdo-dblib php70u-process php70u-pgsql php70u-recode php70u-xml php70u-xmlrp
c php70u-cli
Loaded plugins: fastestmirror
Could not retrieve mirrorlist https://mirrors.iuscommunity.org/mirrorlist?repo=i
us-centos7&arch=x86_64&protocol=http error was
14: curl#7 - "Failed to connect to 2001:4802:7901:0:4ccc:ff11:0:4: Network is un
reachable"

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: ius/x86_64

看上去好像是我的vps不能访问ius，请问有什么办法吗？

**Comment by sendya** [comment]
@zxd882002 清理一下 yum 缓存

**Comment by zxd882002** [comment]
试过yum clean和yum clean all。都不行

**Comment by kookxiang** [comment]
@zxd882002 关闭服务器的IPV6支持看看

**Comment by zxd882002** [comment]
还是不行，执行cat /proc/sys/net/ipv6/conf/all/disable_ipv6，返回1

**Comment by Acris** [comment]
@zxd882002 ping一下mirrors.iuscommunity.org的ipv4地址，然后写进hosts试试。

**Comment by zxd882002** [comment]
貌似也ping不了ip
ping 104.239.182.92
PING 104.239.182.92 (104.239.182.92) 56(84) bytes of data.
From 104.223.25.28 icmp_seq=1 Destination Host Unreachable

**Comment by kookxiang** [comment]
应该是你网络配置有问题，问下主机商

**Comment by zxd882002** [comment]
发ticket了

**Comment by zxd882002** [comment]
vps开发商说ius block了vps的ip。那个onestack好像是编译安装，之前试过，好像会卡在某个地方。不过我会再试试的。所以想问问有没有其他通过yum安装的方法

**Comment by sendya** [comment]
@zxd882002 百度或者谷歌 yum install php 如何？

**Comment by zxd882002** [comment]
找到一个站点，但是我的机器好像不能装。地址：http://www.king-liu.net/?p=1096。请问有没有CentOS 6 安装的教程吗？

**Comment by zxd882002** [comment]
https://www.eaimty.xyz/ToBeGay/2016/03/install-lnmp-on-centos6.html  这个网站有CentOS 6 装php 7的教程。已试过，可行。此贴可结~
