### ISSUE TITLE
部份文件返回404，但是这些文件在目录里头也没有

### ISSUE THREAD

**Issue by zxd882002** [sendya/shadowsocks-panel#142]
## 环境
**PHP** ：  7.0.11  无装`OpCache`
**NGINX** ： 1.10.1
**MYSQL** ： mysql  Ver 14.14 Distrib 5.5.52, for Linux (x86_64) using readline 5.1
**是否为升级程序** ： 否

## 问题/错误信息
我装完起动发现下面这些Resource没有：
GET http://104.223.25.28/Resource/Xenon/css/bootstrap.css 404 (Not Found)
GET http://104.223.25.28/Resource/Xenon/js/jquery-1.11.1.min.js 
GET http://104.223.25.28/Resource/Xenon/js/bootstrap.min.js 404 (Not Found)
GET http://104.223.25.28/Resource/Home/Resource/Home/img/p-img-4.png 404 (Not Found)
GET http://104.223.25.28/Resource/Home/Resource/Home/img/bg-icon.png 404 (Not Found)

我查了一下，有的文件在其他目录，有的就是没有。想问问，这要手动改吗（加相关的文件）？

**Comment by sendya** [comment]
@zxd882002 https://github.com/sendya/shadowsocks-panel/wiki

第一块，第三点 
或者 FAQ 里也有
