### ISSUE TITLE
System Error - 42000

### ISSUE THREAD

**Issue by joelsantana** [sendya/shadowsocks-panel#143]
## 环境
**PHP** ：  7.0.6  有/无装`OpCache`
**NGINX** ： 1.10.0
**MariaDB** ： 10.1.13
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

订单中心任何一个套餐，立即购买，确定后提示如下：
System Error - 42000
SQLSTATE[42000]: Syntax error or access violation: 1110 Column 'userId' specified twice

**Comment by sendya** [comment]
@joelsantana 并没这个功能

**Comment by joelsantana** [comment]
懂了

**Comment by joelsantana** [comment]
谢谢

**Comment by sendya** [comment]
@joelsantana 没事，等有这个功能之后才公告通知

**Comment by joelsantana** [comment]
ok😀

**Comment by cybmp3** [comment]
期待。。。。。。
