### ISSUE TITLE
请问邀请码的那个扣10G流量在那修改

### ISSUE THREAD

**Issue by ahuangsen** [sendya/shadowsocks-panel#144]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
如上，后台没有带这个设定把？

**Comment by sendya** [comment]
@ahuangsen 你可以自己改代码

**Comment by ahuangsen** [comment]
2.1 systemd脚本 （这是什么?）

提供一个 systemd 服务脚本，写进 /etc/systemd/system/shadowsocks-rm.service 即可，需要修改其中的运行用户组以及运行路径
CentOS6.X没有这个脚本支持,是不是必须装CentOS7

**Comment by sendya** [comment]
@ahuangsen 用 `supervisor` 也行

**Comment by ahuangsen** [comment]
已经全部弄好,非常感谢,但是有个问题,后台的节点只能加4个???

**Comment by sendya** [comment]
@ahuangsen 不是有个 添加按钮 吗？多少个都可以

**Comment by ahuangsen** [comment]
有的,原因是ie模式好像兼容性有问题,换极速模式后正常添加,感谢技术支持

**Comment by sendya** [comment]
@ahuangsen 真爱生命，原理IE

**Comment by ahuangsen** [comment]
还有个小问题,就是关于流量和套餐的事
流量是每个月自动重置一次? 比如套餐是B,那么下个月还是B?还是一个月过去就失效了?

**Comment by ahuangsen** [comment]
重置问题,我搞明白了..  套餐我也搞明白了, 然后怎么样才能让免费用户用不到期呢

**Comment by ahuangsen** [comment]
抱歉,我没有看后台那个试用,问题已经全部解决,非常感谢作者
