### ISSUE TITLE
请问下nodequery API的current_tx current_rx 的单位是多少

### ISSUE THREAD

**Issue by usami-muzugi** [sendya/shadowsocks-panel#146]
{
                "id": 30251,
                "status": "active",
                "availability": "100%",
                "update_time": 1475108122,
                "name": "node1",
                "load_percent": 1,
                "load_average": "0.00 0.01 0.05",
                "ram_total": 1041494016,
                "ram_usage": 394858496,
                "disk_total": 105158455296,
                "disk_usage": 75065016320,
                "ipv4": "",
                "ipv6": "",
                **"current_rx": 2231897,**
                **"current_tx": 568834**
            },

**Comment by usami-muzugi** [comment]
这么怎么换算成速率？

**Comment by usami-muzugi** [comment]
这个该如何换算成速率？

**Comment by sendya** [comment]
@usami-muzugi 详情建议直接看 NodeQuery 官网 API文档：https://nodequery.com/help/developer-api
单位好像是 KB
