### ISSUE TITLE
发现一点后台ui问题，不知道是不是故意这样显示

### ISSUE THREAD

**Issue by otherfish** [sendya/shadowsocks-panel#148]
管理员后台，点系统设置→详细参数，会把上面的系统设置也一并高亮，点其他的菜单则没有这方面的问题。如图：

![sp20161015_210608](https://cloud.githubusercontent.com/assets/12808134/19410306/4b868d8c-931b-11e6-9eb3-97645b50b5ce.png)

**Comment by sendya** [comment]
@otherfish 恩 知道了
