### ISSUE TITLE
冒昧的问一下，如果要添加网站ico，需要修改哪个文件

### ISSUE THREAD

**Issue by otherfish** [sendya/shadowsocks-panel#149]
面板程序是最新版：
尝试了改了这几个文件：
1. `/Data/Template/Xenon/panel/_head.php `
`/Resource/Xenon/favicon-32x32.png`  // 把png文件放在了这个文件夹
2.  `/Template/Xenon/panel/_head.htm`  // 似乎找不到这个主题的index.html,只有index.php，图片文件统一放在了`/Resource/Xenon/*.png`
3. `/Data/Template/Home/index.php `
4. 链接图片资源的代码是：
`<link rel="shortcut icon" href="{RESOURCE}/paper-plane.png">
<link rel="shortcut icon" type="image/png" href="/paper-plane.png" />`
`<link rel="icon" type="image/png" href="<?php echo RESOURCE; ?>/favicon-32x32.png" sizes="32x32" />`

始终调试不出来效果。

**Comment by sendya** [comment]
@otherfish 任何模板都在 `Template` 内，你要修改的在：`shadowsocks-panel/Template/Xenon/panel/`

**Comment by sendya** [comment]
查阅 [FAQ 常见问题与解答](https://github.com/sendya/shadowsocks-panel/wiki/FAQ) 第 5 条  **Q. 如何修改站点名，LOGO**

**Comment by otherfish** [comment]
@sendya 谢谢回复，这个我看了，我不是修改网站logo，我是想添加一个 网站的favicon图标，我也在你说的`Template`中找到了引入favicon的_head.htm文件，但是不起效果，相对路径和绝对路径都试了，只能在登录页面和找回密码页面看到效果(firefox), chrome无论是首页和登录也都不起效果，所以我想怎么没有index.htm这个文件：

![sp20161017_163128](https://cloud.githubusercontent.com/assets/12808134/19430554/367aad02-9487-11e6-9ac6-a7bc901f3d5f.png)

**Comment by sendya** [comment]
@otherfish https://github.com/sendya/shadowsocks-panel/blob/master/Template/Home/index.htm

**Comment by haodong** [comment]
直接做一个ico图标放到PUB下面`Public/favicon.ico`

**Comment by otherfish** [comment]
@sendya 我对比了你给我的仓库中的文件，确实是新版首页的内容，但我不知道为什么我这边的home文件夹里的首页是老版里的内容，但是网站打开好像是新版的内容，是不是通过那个index.php来动态渲染的？
我现在的做法是把你给首页内容复制替换掉老版的内容了，然后再次引用*.ico文件，好像还是没有生效，可能自己有点绕，不好意思啊。 要不要顺带把index.php这里面的也改一下呢？

![sp20161017_170410](https://cloud.githubusercontent.com/assets/12808134/19431633/d5d3e3ce-948b-11e6-9b4e-8e70cc3988bc.png)
![sp20161017_170612](https://cloud.githubusercontent.com/assets/12808134/19431698/10d639e0-948c-11e6-9fa4-1580d88d7164.png)

**Comment by otherfish** [comment]
@haodong 图片文件要放到这个文件夹里才行吗？

**Comment by sendya** [comment]
@otherfish Data 里都是临时文件，改了下一秒又重新生成了

**Comment by haodong** [comment]
@otherfish 什么文件夹 我不是告诉你路径了么

**Comment by otherfish** [comment]
@haodong 放到这个路径里，其他还要做什么？ 要不要引用了？

**Comment by haodong** [comment]
放进去就行了

**Comment by otherfish** [comment]
@haodong 不行，我自己再看看吧！ 不知道我们两个说的版本是不是一样的，还是感谢各位的回复。

**Comment by otherfish** [comment]
@sendya 
按照你的回复，任何与页面显示相关的，都在`Template`这个文件夹内，但我始终修改
`shadowsocks-panel/Template/Xenon/panel/_head.htm`   和 `shadowsocks-panel/Template/Home/index.htm 
这两个文件都不起效果，添加的代码为: 


![image](https://cloud.githubusercontent.com/assets/12808134/19485549/0c5ae53e-958e-11e6-9cac-7ab833b8102c.png)


但是我试了链接到系统自带的图像有效果，不知道是不是权限控制的问题，还是nginx的配置问题，我确保我的图像在我链接的路径可以找到 ：

![image](https://cloud.githubusercontent.com/assets/12808134/19485281/3e1368ea-958d-11e6-907b-d66975168b71.png)

我在控制台查看我上传的图片显示404：

![image](https://cloud.githubusercontent.com/assets/12808134/19485374/98c6703e-958d-11e6-8258-14e397adaf13.png)

**Comment by haodong** [comment]
噗 非要png…… 好吧 随你
