### ISSUE TITLE
未登陆的情况下直接访问/admin 会报未找到控制器&路径

### ISSUE THREAD

**Issue by kuertianshi** [sendya/shadowsocks-panel#15]
不知道是不是我本地测试的原因，先丢上来啦QVQ

**Comment by sendya** [comment]
@kuertianshi 不清楚，有拦截器在 admin的 Controller

**Comment by sendya** [comment]
@kuertianshi 在控制器有进行拦截，没登录会被转向到 /auth/login

**Comment by kuertianshi** [comment]
@sendya 我这里提示Fatal error: Class 'Controller\Admin\Response' not found in XXX\sspanel\Library\Controller\Admin\AdminListener.php on line 19

但是要是访问/member会转到 /auth/login

**Comment by sendya** [comment]
@kuertianshi 好。知道了，谢谢。  虽然没人会这么搞，待会我加一下 import 就好了

**Comment by kuertianshi** [comment]
@sendya 嗯，错误没啥主要是会报路径

**Comment by sendya** [comment]
@kuertianshi 然而你自己不关闭 开发模式，当然会出路径…

**Comment by sendya** [comment]
@kuertianshi Config.php 里。DEBUG 改 false

**Comment by sendya** [comment]
@kuertianshi 我没在安装文档说明，我的锅

**Comment by kuertianshi** [comment]
@sendya 你骗人！强行摔锅QVQ  这错误提示关了debug也会报

**Comment by sendya** [comment]
@kuertianshi PHP5 版本？

**Comment by kuertianshi** [comment]
@sendya 嗯 5.5

**Comment by sendya** [comment]
@kuertianshi 这个只支持 PHP7 ，PHP5 继承 Exception 之后 还是拦截不到… 我会更新PHP5的支持分支…

**Comment by kuertianshi** [comment]
@sendya 好吧~

**Comment by sendya** [comment]
@kuertianshi  关于 未登录/无权 时，访问管理地址 `/admin/*` 时报错问题，已经解决。于 [Fixed admin no power ERROR...more](https://github.com/sendya/shadowsocks-panel/commit/2793c9886c7b01c14e1ae89c80f9aace88452556)
