### ISSUE TITLE
不知是bug还是有意改之

### ISSUE THREAD

**Issue by y0rvin** [sendya/shadowsocks-panel#153]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

最新面板的管理员后台，点击左上侧设置图标无效；旁边的收回菜单按钮也是无效的。
![bug](https://cloud.githubusercontent.com/assets/20252881/20035922/a94496b2-a432-11e6-980a-f7a073ea5ed7.JPG)

**Comment by sendya** [comment]
@y0rvin 这个好像是在 手机端 会这样。暂时没修正 js脚本。等下次更新把

**Comment by y0rvin** [comment]
@sendya 在PC端测试都有以上问题。等待更新了
