### ISSUE TITLE
python servers.py 时出错

### ISSUE THREAD

**Issue by fox19971102** [sendya/shadowsocks-panel#154]
## 环境
使用的youtube视频里面推荐的cnmp.sh脚本
## 问题/错误信息
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 151, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 59, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 49, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
WARNING:root:db thread except:timed out

**Comment by sendya** [comment]
@fox19971102 shadowsocks-rm 是在数据库所在的服务器吗？  地址 127.0.0.1 ？？

**Comment by fox19971102** [comment]
是的 地址是127.0.0.1

**Comment by sendya** [comment]
@fox19971102 ERROR:root: Errno 98  Address already in use
ERROR:root:can not bind to manager address
管理地址默认就好了  不会改的话尽量别改

**Comment by fox19971102** [comment]
管理地址..我好像没有改 我只是讲数据库账号密码什么的修改成我自己的其他的都没有动，然后就报错了

**Comment by sendya** [comment]
@fox19971102 Errno 98  Address already in use

**Comment by sendya** [comment]
@fox19971102 被占用了， 你是不是 多开了什么

**Comment by fox19971102** [comment]
前端和后端的数据库是同一个 账号密码也都是root的密码 是因为这个的原因吗？  我是按照视频里面一步一步的做的  后端也是照着教程复制的..  走到这一步就报错了  不知道为什么

**Comment by sendya** [comment]
@fox19971102 我后端没做教程把。。。

**Comment by sendya** [comment]
@fox19971102 按照普通的 shadowsocks-manyuser 或者 shadowsocks-rm 都能正常运行后端。

**Comment by fox19971102** [comment]
后端是按照那几行命令复制的...

**Comment by fox19971102** [comment]
今天折腾了一天，原来安装了一个sspanelV3 后端装好了，但是前端一直报错，后来，搜到了您的，按照教程 前端很快装好了，后端又出错了...

**Comment by sendya** [comment]
@fox19971102 拜托。。后端通用的，拜托去看下  https://github.com/mengskysama/shadowsocks-rm/tree/manyuser

**Comment by sendya** [comment]
@fox19971102 把你错误截图出来我看下把。 还有配置截图一份 数据库 user/pass 打码就行了

**Comment by fox19971102** [comment]
哦哦 我刚才谷歌了一次 又重新装了一次。但是还是出错.. 我马上贴下图

**Comment by fox19971102** [comment]
![qq 20161127011628](https://cloud.githubusercontent.com/assets/20569519/20642010/47bdc090-b43f-11e6-9348-52a85017c87d.png)
![qq 20161127011647](https://cloud.githubusercontent.com/assets/20569519/20642012/4d2d2a70-b43f-11e6-8d95-2fc3db3be71c.png)

**Comment by fox19971102** [comment]
![qq 20161127012713](https://cloud.githubusercontent.com/assets/20569519/20642057/aca4f78e-b440-11e6-9f98-17b349fbe03f.png)

**Comment by sendya** [comment]
我也不知道什么情况了，总之提示就是说数据库连接超时了。 你手动连下数据库试试把
