### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by ouyangmland** [sendya/shadowsocks-panel#155]
下个版本能否加入这样的功能
对于套餐时间到期的账户，能否自动让该账户回到免费用户？无论是这个账号属于哪个用户级别，在套餐时间到期后自动回到免费用户这个账户级别

**Comment by sendya** [comment]
即使切回去，也是停用的。这样做有什么意义吗？

**Comment by ouyangmland** [comment]
@sendya 因为在免费账号的情况下，是无权查看PRO节点的。而到期后的账户依旧是之前购买的账户级别，依旧可以看的到PRO节点信息，有时候有些信息，只给付费用户看的，所以方便一些

**Comment by sendya** [comment]
@ouyangmland 我会考虑，但不是以降级的方式。谢谢

**Comment by sendya** [comment]
@ouyangmland 最新的提交已经添加这项功能，可以直接使用 `git pull` 更新代码。无需重装面板或重启服务器。 感谢提交 issue

**Comment by ouyangmland** [comment]
@sendya 感谢作者，无私奉献
