### ISSUE TITLE
管路员后台手机浏览器无法展开后台列表

### ISSUE THREAD

**Issue by ouyangmland** [sendya/shadowsocks-panel#156]
点那个列表图标三个横线的标志，点了没有任何反应，不会展开列表，在用户界面里面能展开列表

**Comment by sendya** [comment]
@ouyangmland 嗯，这个问题前面有人提过 issue 了。但是目前我也没找到是哪个 js 导致的问题。并且由于是后端界面，就暂时先放下了。

**Comment by ouyangmland** [comment]
@sendya 好的。
