### ISSUE TITLE
强烈建议大佬们能在管理后台，仪表盘加入对shadowsocks运行状态的实时监控、显示

### ISSUE THREAD

**Issue by s07319210316** [sendya/shadowsocks-panel#157]
强烈建议大佬们能在管理后台，仪表盘加入对shadowsocks运行状态的实时监控、显示，进程是死掉了，还是活着的啊，基础的cpu/memory/网络接口利用率的监控。
以及可在“用户管理”列表中增加一列用户当前的状态（启用/禁用），不然人多了，都得挨个挨个点进去编辑才知道。

**Comment by Mkdms** [comment]
用第三方服务器监控即可
以下
https://nodequery.com/

**Comment by s07319210316** [comment]
同时建议可以后台管理页面，搞个一键启停shadowsocks的按钮，可在“用户管理”列表中增加一列 复选框，通过勾选实现，批量删除、禁用用户等操作。

**Comment by sendya** [comment]
本功能暂时无时间实现，若您较为有空，可以尝试自行开发。 若能向本项目发起 pull request 甚为感谢。
