### ISSUE TITLE
请问诸位朋友，你们的在订单中心，点击“购买”——“确定”后有报错吗？

### ISSUE THREAD

**Issue by s07319210316** [sendya/shadowsocks-panel#158]
请问诸位朋友，你们的在订单中心，点击“购买”——“确定”后有报错吗？
![qq 20161212185153](https://cloud.githubusercontent.com/assets/24489312/21096835/6fe55e20-c09c-11e6-964d-378c7d52a66b.jpg)
![qq 20161212185222](https://cloud.githubusercontent.com/assets/24489312/21096837/71e40c44-c09c-11e6-8f7f-7f40efbe5cec.jpg)

**Comment by sendya** [comment]
@s07319210316 未完成功能

**Comment by s07319210316** [comment]
@sendya 知道了，感谢！
