### ISSUE TITLE
有个比较好奇的问题

### ISSUE THREAD

**Issue by kuertianshi** [sendya/shadowsocks-panel#16]
为什么新版的要把数据库字段名都改了，想了好久没想通

**Comment by sendya** [comment]
`什么新版的要把数据库字段名都改了` 这啥意思？  `member` 表的字段？

**Comment by kuertianshi** [comment]
@sendya 是的

**Comment by sendya** [comment]
@kuertianshi 从开发这个`sspanel`就一直是这个结构的 db表，你可以看我的 `commit` 历史记录，也没改过 DB呀。

**Comment by kuertianshi** [comment]
@sendya 不= =我的意思是现在的manyuser版本不一般都是user表嘛  改了以后对接好像不太好接，或者是我没找到manyuser那边可以修改字段的地方

**Comment by ju0594** [comment]
呃 本来我想按照readme.md里作者说的改查询字段来兼容ssr 结果实在不会，就直接用作者提供的ss-rm了

**Comment by sendya** [comment]
@kuertianshi 这个面板，其实最开始并没打算开源的，在我内部git上提交的，后来有朋友要，我就直接往这里push -f 了一份，而且我这个面板有对应改好了的manyuser版本可以用。其次。我自己用的版本是可以控制 账户等级。，例如 `VIP` 会优先转发，这个异步问题。

**Comment by sendya** [comment]
@ju0594 改字段很简单啊。。就一个文件要改  。搜索一下 `select` 和 `update` 然后把后面代码里 `u`,`d`,`port`,`enable` 等改成我这个面板所需要的 flow_up, flow_down , enable

**Comment by kuertianshi** [comment]
@sendya 哦哦，了解了

**Comment by sendya** [comment]
不然我去改一个版本放上来吧

**Comment by kuertianshi** [comment]
@ju0594 好像是改model里的user.php

**Comment by kuertianshi** [comment]
@sendya manyuser的字段是在哪个文件里改的

**Comment by sendya** [comment]
@kuertianshi 千万别这么改  整个程序会不能运行的。

**Comment by kuertianshi** [comment]
@sendya 还好我没改233

**Comment by sendya** [comment]
@kuertianshi 我改好放上来吧。。唉。

还有什么版本需要的，我都可以放上来

**Comment by kuertianshi** [comment]
@sendya 没，就想学习下

**Comment by kuertianshi** [comment]
@sendya 找到了 是db_transfer.py下修改嘛

**Comment by ju0594** [comment]
@sendya 你的版本用起来也挺好啦
想问下如果我改了某一些文件 git pull有冲突 那先用git stash再pull后，我修改的文件是不是就直接变成服务器的版本？

**Comment by sendya** [comment]
@kuertianshi @ju0594 
```bash
$ git clone -b manyuser-rss https://github.com/sendya/shadowsocks.git
$ cd shadowsocks/shadowsocks
```

和其他版本安装方法一样，我账户下的 fork 地址：[shadowsocks-rss-manyuser](https://github.com/sendya/shadowsocks/tree/manyuser-rss)

这就是你们需要的 *版 manyuser-rss

**Comment by ju0594** [comment]
@sendya 辛苦了 我在你博客看过 我记得你说过不安全...
不过我是无所谓啦，现在懒的换了 以后可能会需要

**Comment by kuertianshi** [comment]
@sendya 辛苦了:)   我先手动修改一次看看
