### ISSUE TITLE
问个业务逻辑问题

### ISSUE THREAD

**Issue by otherfish** [sendya/shadowsocks-panel#160]
就是手贱运行了计划任务，把管理员的账号停掉了，然后连不上了，好像是把端口封了，然后用iptables重开端口也连不上，最后通过新建个账号连上了，如何避免运行计划任务把管理员停掉的问题，能不能给管理员设置为不过期呢。现在是通过套餐卡把管理员变成了普通用户连上了，不知道阐述的清不清楚。

**Comment by sendya** [comment]
这一段 SQL （https://github.com/sendya/shadowsocks-panel/blob/master/Library/Model/User.php#L136） 内添加一个 过滤管理员的条件就不会了。
