### ISSUE TITLE
部分用户流量没有被归零

### ISSUE THREAD

**Issue by Love4Taylor** [sendya/shadowsocks-panel#163]
## 环境
**PHP** ：  7.0.5  有装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
每个月一号，有部分用户的流量统计没有被清零

**Comment by Acris** [comment]
@Love4Taylor 固定流量套餐用户的流量不会每月清零。

**Comment by Love4Taylor** [comment]
都是套餐卡的用户

**Comment by BorLee** [comment]
“过期\停止”的账户也不会被清空已用流量

清零的条件是`enable`=1 AND `plan`!='Z'
