### ISSUE TITLE
免费用户，用户状态BUG

### ISSUE THREAD

**Issue by ouyangmland** [sendya/shadowsocks-panel#164]
免费用户注册完后，不需要验证邮箱，直接在账户信息里面点账户状态的红色按钮，就可以立即将本来来是停用状态变成启用状态。从而跳过邮箱邮件验证的步骤。不再需要点击邮箱里面的验证链接！

**Comment by maomicq** [comment]
@ouyangmland 一样遇到这个情况，听作者大神说是没有配置运行计划任务。
