### ISSUE TITLE
关于用户到期后收不到邮件提醒

### ISSUE THREAD

**Issue by busbyjrj** [sendya/shadowsocks-panel#166]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

开发者您好，我在测试用户时，发现用户在流量用尽/时间过期之后收不到过期的提醒邮件，但面板上已经显示该用户过期且无法正常使用服务，并且管理员能够正常接收两封测试邮件，用户也能收到注册时的验证码和注册成功的邮件。请问这是否是我手动调整用户流量/到期时间的原因？最后非常感谢您提供了这个面板，谢谢！

**Comment by Acris** [comment]
定时任务有配置成功并执行么？

**Comment by shenlw** [comment]
我也遇到**流量用尽/时间过期之后收不到过期的提醒邮件**的问题，我还以为是代码里没有写

**Comment by sendya** [comment]
@shenlw 建议检查一下是否计划任务正在运行

**Comment by shenlw** [comment]
@sendya 我看了下日志，计划任务有正常运行，即`/usr/bin/curl http://xxx/cron`；另外手机版的页面上能否加上退出账号的设定呢？

**Comment by busbyjrj** [comment]
@sendya @Acris ，  cron 的日志是正常运行的。

**Comment by sendya** [comment]
@busbyjrj @shenlw @Acris  进入管理员面板，系统设置 -> 详细参数 -> 配置项“#mail_stop_expire_notification” 值 调整为 1 开启邮件到期通知（本设置默认为 0 ）

**Comment by busbyjrj** [comment]
@sendya 能够收到到期邮件了，感谢！
