### ISSUE TITLE
请问如何关闭注册邀请码

### ISSUE THREAD

**Issue by zhlzhl123** [sendya/shadowsocks-panel#167]
## 环境
**PHP** ：  7.0.5  无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

请问如何关闭注册邀请码，我希望用户可以自由注册的话该怎么设置？谢谢

**Comment by zhlzhl123** [comment]
我希望所有人都可以注册普通账户，然后通过套餐卡升级

**Comment by sendya** [comment]
你可以修改一下 `\Controller\Auth` 类，将验证 邀请码的段落代码去掉，既不会在验证是否需要验证码；

**Comment by zhlzhl123** [comment]
@sendya 
我自己摸索了一下，还是不太会改。不知道在哪里和怎么改
![123](https://cloud.githubusercontent.com/assets/24950039/23336899/7459f3dc-fc18-11e6-8c51-4ece1b2a6b4a.PNG)
我想所有人不需要邀请码注册就是免费用户。请问该怎么设置呢？谢谢

**Comment by zhlzhl123** [comment]
@sendya 
帮帮看看呗，实在不会弄啊
