### ISSUE TITLE
关于自动清理到期用户的问题

### ISSUE THREAD

**Issue by maomicq** [sendya/shadowsocks-panel#168]
计划任务如何操作呢。谢谢。

**Comment by sendya** [comment]
@maomicq 你是要问程序的计划任务设置 ，还是要问如何配置 crontab ？

**Comment by sendya** [comment]
@maomicq 查看文件：https://github.com/sendya/shadowsocks-panel/blob/master/Library/Helper/Cron/StopExpireUser.php#L31

**Comment by maomicq** [comment]
@sendya 谢谢作者大神，我按照你提供的方法部署了前端，后端自己研究也做了个详细教程，现在好多群有都在用你这个方案，简洁明了。
谢谢提供这个页面文档，我再仔细研究一下这个文档的使用。

还有一个小问题，关于支付这块，目前跟群友研究了好久，都无法实现支付这块，总结了一下，唯一可行的办法就是用第三方发卡平台来代替支付这块。

**Comment by sendya** [comment]
@maomicq 签支付宝等支付平台的精力太大了而已，不然是可以直接实现支付宝支付对接的

**Comment by maomicq** [comment]
@sendya 你好作者大神，我刚刚测试了一下，发现过期用户，如果该用户自己不在 账号中心-个人资料 下面 点 刷新账号状态 的话   那么他一直不过期，，如果过期用户自行 刷新了账号状态后，变成 停用 状态 才能过期。不然一直是可用状态 ，可用平台内节点。计划任务可以管理员自己执行吗？ 谢谢。

**Comment by sendya** [comment]
@maomicq 每五分钟会自动检查的…除非你计划任务没配置运行

**Comment by maomicq** [comment]
@sendya 应该是没有配置运行，请教一下，如何才能配置计划任务运行呢？在管理员后台 计划任务 那块并没有可执行的地方。谢谢。

**Comment by shenlw** [comment]
@maomicq 你是说crontab吗？
https://github.com/sendya/shadowsocks-panel/wiki/Shadowsocks-Panel-面板安装教程#3-配置路由规则

**Comment by maomicq** [comment]
@shenlw 你好，我按照你给的页面在vps上操作了一下，crontab -e  找不到命令。 但是 收到 执行 /usr/bin/curl https://yourdomain.com/cron 这个 可以手动执行计划任务。

**Comment by maomicq** [comment]
@shenlw 我的是没有安装crontab 安装了一下按你的方法解决了谢谢。
安装crontab
yum install vixie-cron
yum install crontabs
