### ISSUE TITLE
看了下不支持UDP吗？

### ISSUE THREAD

**Issue by maomicq** [sendya/shadowsocks-panel#169]
用sockscap64 看部署后不支持udp模式，请问在哪里打开呢？谢谢。

**Comment by sendya** [comment]
@maomicq 与面板无关，请咨询 manyuser 服务端

**Comment by maomicq** [comment]
@sendya  你好大神，不好意思又来麻烦你了，我用的是 wiki里面的 shadowsocks manyuser 安装与对接 的manyuser。看说明写的是支持udp，但是测试 发现并不支持udp模式呢。

**Comment by sendya** [comment]
@maomicq https://github.com/mengskysama/shadowsocks-rm/tree/manyuser


但是测试别人都能 UDP

**Comment by Acris** [comment]
@maomicq 服务端默认开启UDP，请检查防火墙是否开启UDP端口。

**Comment by maomicq** [comment]
@sendya 好的我再检查一下，谢谢大神的耐心解答。

**Comment by sendya** [comment]
查询关键字 `iptables` `udp` `端口`  http://bbs.csdn.net/topics/350207711
