### ISSUE TITLE
管理员修改用户信息不成功，且注册时无法自动分配端口

### ISSUE THREAD

**Issue by deamwork** [sendya/shadowsocks-panel#17]
新注册用户必须手动修改数据库里member里的port字段才能使用
而且用管理员面板无法修改用户信息，所有信息都要从数据库修改

**Comment by sendya** [comment]
修正 port字段 是什么情况？ 这个字段是 空吗?

后端无法修改用户信息 请把错误信息贴出来。

**Comment by deamwork** [comment]
json返回无法修改用户信息：出现未知错误，请重试或联系管理员

port字段默认是NULL

**Comment by sendya** [comment]
@deamwork 你改了配置文件的 ENABLE_PLAN_A ？

**Comment by deamwork** [comment]
我用的是今天中午那时候你commit的版本

**Comment by sendya** [comment]
@deamwork 我中午提交了好几个版本呢。 邀请码的 PLAN 不是 A 就会分配用户端口

**Comment by sendya** [comment]
@deamwork 本地测试 +  线上测试均无问题。 报 `出现未知错误，请重试或联系管理员` 为 Ajax 请求失败，请检查修改时的 浏览器 请求信息。

**Comment by deamwork** [comment]
前面测试了一下，真的是没法修改数据，但是可以读取的，我要是能修改我就不会选择pma去手动修改数据了。不过今天调试了近两个小时，换掉了你的一个sql查询语句，现在恢复正常了。前面的调试里查询过mysql没有发现数据库写操作

**Comment by deamwork** [comment]
我貌似用的是你倒数第二个的commit

**Comment by sendya** [comment]
@deamwork 然而我从昨天的提交之后，就没再动过后台的 增删改查代码。这些代码在 前两天就好多人测试过

**Comment by sendya** [comment]
@deamwork 你完全可以贴出 ajax 的错误信息，否则我也无法查问题

**Comment by deamwork** [comment]
啊我刚刚替换了你的sql语句修复了问题.....现在是正常的.......

**Comment by sendya** [comment]
@deamwork 也可以试试 /admin/user/modify 手动访问地址会不会有问题

**Comment by deamwork** [comment]
啊这个世界好乱

**Comment by deamwork** [comment]
直接访问结果
{"error":1,"message":"Request failed"}

**Comment by sendya** [comment]
没事我就关 issue 了。

**Comment by deamwork** [comment]
还有。...

**Comment by deamwork** [comment]
新注册用户还是没有自动分配端口

**Comment by sendya** [comment]
@deamwork 不是 A 级的邀请码 或者 ENABLE_PLAN_A 必须是 false 才会分配

**Comment by deamwork** [comment]
好的知道了，谢谢。希望完善套餐的部分。支持您的项目~

**Comment by sendya** [comment]
@deamwork 从这个 commit [Fixed register transfer](https://github.com/sendya/shadowsocks-panel/commit/e5be8ffac83b5947cc0dfaec1538e0bca8a428cc) 开始 ，套餐部分就没什么需要改的了。如果你有什么意见，可以提出来。

**Comment by deamwork** [comment]
顺便说一下，右上角（设置）修改密码的地方会跳转到local.dev

**Comment by kuertianshi** [comment]
@sendya @deamwork 刚准备说就看到了
Data\Template\Default\panel\_content.php
	Line 81: <a href="http://local.dev/member/ChangePassword">

**Comment by sendya** [comment]
@deamwork @kuertianshi 昨天晚上最后那个提交 这个链接改好了
