### ISSUE TITLE
请问怎么限制登陆人数

### ISSUE THREAD

**Issue by xiesesshifang** [sendya/shadowsocks-panel#170]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
请问怎么限制登陆人数

**Comment by sendya** [comment]
你所描述的问题 该如何理解 ？
SS 服务端登陆人数限制  / 面板登陆人数限制

**Comment by xiesesshifang** [comment]
ss服务端登录人数限制 就是别人同一个号 多个人同时用
