### ISSUE TITLE
安装后获取静态文件路径问题

### ISSUE THREAD

**Issue by affbridge** [sendya/shadowsocks-panel#171]
## 环境
**基础环境** ：  LNMP
**是否为升级程序** ： 否

## 问题/错误信息
首页获取静态文件出错，找不到JS及CSS文件。
http://www.xxx.com/Resource/Xenon/css/bootstrap.css 
http://www.xxx.com/Resource/Xenon/js/bootstrap.min.js 
http://www.xxx.com/Xenon/Home/js/jquery-1.11.1.min.js 
等等文件。

**Comment by sendya** [comment]
请阅读 [WIKI](https://github.com/sendya/shadowsocks-panel/wiki)

![image](https://static-2.loacg.com/open/static/ss-panel-github/sp20170315_151203.png)

![image](https://static-2.loacg.com/open/static/ss-panel-github/sp20170315_151227.png)

**Comment by affbridge** [comment]
非常感谢大神的回答，我已经装了这个，但是还是提示找不到，然后用浏览器直接打开却无法打开这个静态资源。http://www.antiageblog.com/
请大神帮忙看看，谢谢。

**Comment by affbridge** [comment]
![2017-03-15_15-59-59](https://cloud.githubusercontent.com/assets/21187399/23938727/816cff00-0998-11e7-8138-b31469d374ae.jpg)

**Comment by sendya** [comment]
@affbridge 你执行 php index.php install 了吗

**Comment by affbridge** [comment]
执行这个报错 就执行的php -d disable_functions='' index.php install

**Comment by sendya** [comment]
@affbridge 装了资源之后 还有执行一次吗

**Comment by affbridge** [comment]
没有 我试试，谢谢

**Comment by affbridge** [comment]
搞定 谢谢，大神 您提供付费合作吗？有机会是否能合作？

**Comment by sendya** [comment]
@affbridge 做什么？

**Comment by affbridge** [comment]
现在还在筹划，定了回头我找您，感谢！
