### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by KevinHades** [sendya/shadowsocks-panel#174]
## 环境
**PHP** ：  7.0.17  有装`OpCache`
**NGINX** ： 1.10.3
**MYSQL** ： 10.1.22-MariaDB
**是否为升级程序** ： 否

## 问题/错误信息
Warning: filemtime(): stat failed for /usr/share/nginx/html/shadowsocks-panel/Data/Template/Misc/Error.php in /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php on line 41
Fatal error: Uncaught Core\Error: Cannot write template file: /usr/share/nginx/html/shadowsocks-panel/Data/Template/Misc/Error.php in /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php:180 Stack trace: 
#0 /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php(42): Core\Template::compile('Misc/Error') 
#1 /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php(66): Core\Template::load('Misc/Error') 
#2 /usr/share/nginx/html/shadowsocks-panel/Library/Core/Error.php(73): Core\Template::render() 
#3 /usr/share/nginx/html/shadowsocks-panel/Library/Core/Error.php(50): Core\Error::handleUncaughtException(Object(Core\Error)) 
#4 [internal function]: Core\Error::handlePHPError(2, 'filemtime(): st...', '/usr/share/ngin...', 41, Array)
#5 /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php(41): filemtime('/usr/share/ngin...') 
#6 /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php(66): Core\Template::load('Misc/Error') 
#7 /usr/share/nginx/html/shadowsocks-panel/Library/Core/ in /usr/share/nginx/html/shadowsocks-panel/Library/Core/Template.php on line 180

直接执行php index.php install 报错
Now reloading packages and config...
Database not available! Please modify ./Data/Config.php and try again
Config.php配置文件已经改过正确数据库名，用户名，密码

**Comment by sendya** [comment]
检查一下 ·./Data` 目录是否有 rw 权限

**Comment by KevinHades** [comment]
有这个权限，后来怕还有问题，直接777了

**Comment by KevinHades** [comment]
404 not found 
Resource 添加了，安装成功了，首页打开了，布局文件什么的加载都没有问题，
就是首页中连接的页面都打不开，比如首页，登录，注册等点这些连接页面都404

**Comment by KevinHades** [comment]
好了，是我的伪静态写错了。可以关闭了
