### ISSUE TITLE
如何升级ss panel 到V3

### ISSUE THREAD

**Issue by youngfisher** [sendya/shadowsocks-panel#175]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

先感谢各位写攻略的大神。我在网络上找到一个攻略，按照里面的设置，用的是这个版本的ss panel，成功地建好了站点，但是功能很简陋，config找不到设置流量，还有许多接口找不到修改。

我想升级到panel v3，但是不知道该如何设置mysql和其他的内容，请求援助~

**Comment by sendya** [comment]
抱歉，暂不支持
