### ISSUE TITLE
shadowsocks-manyuser 代理没有正常工作

### ISSUE THREAD

**Issue by holyen** [sendya/shadowsocks-panel#178]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
前端正常运行 shadowsocks-panel
后台按照文档 https://github.com/sendya/shadowsocks-panel/wiki/shadowsocks-manyuser-%E5%AE%89%E8%A3%85%E4%B8%8E%E5%AF%B9%E6%8E%A5 搭建了,并正确配置了数据库,执行 python servers.py
add: {"server_port": 5000, "password":"338ssLHY", "method":"rc4-md5"}
add: {"server_port": 5001, "password":"u6bssEtA", "method":"rc4-md5"}
add: {"server_port": 5002, "password":"HSssyS5i", "method":"rc4-md5"}
但代理无法正常工作

**Comment by sendya** [comment]
@holyen 你目前的状态已经跟面板没什么关系了，检查你自己的防火墙有没有开端口把。 多了解 linux 就能解决这些简单的问题

**Comment by holyen** [comment]
我能这样理解吗   netstat -ntlp 如果列表有 5000,5001,5002 就应该是正确的 @sendya

**Comment by holyen** [comment]
问下 现在我想设多台服务器节点,那如何连接到其它服务器上,我看到有man_pass 是每台都要安装面板+后端吗.如果只有后端的话 没有数据库 @sendya

**Comment by holyen** [comment]
ok,了解了 ,thx
