### ISSUE TITLE
shadowsocks-rm有相应的接口文档吗

### ISSUE THREAD

**Issue by holyen** [sendya/shadowsocks-panel#180]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

**Comment by sendya** [comment]
不清楚，可以去作者那看看 https://github.com/mengskysama/shadowsocks-rm

**Comment by holyen** [comment]
可否留个联系方式 @sendya

**Comment by sendya** [comment]
@holyen Telegram: https://t.me/sendya

**Comment by holyen** [comment]
注册不了 换一个联系方式吧

**Comment by holyen** [comment]
@sendya

**Comment by sendya** [comment]
@holyen 我不用别的聊天工具，TG需扶墙，自己想办法

**Comment by mynuolr** [comment]
close

**Comment by holyen** [comment]
@sendya 我翻了 还是注册不了,,,google+ or facebook,twitter
