### ISSUE TITLE
建成后，网页加载出现了问题

### ISSUE THREAD

**Issue by GHKyuU** [sendya/shadowsocks-panel#181]
## 环境
**PHP** ：  5.6  有`OpCache`
**NGINX** ： 1.12.0
**MYSQL** ： 10.1
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
具体情况[如图](http://wx1.sinaimg.cn/large/a9110ec1gy1fetjsn847tj21yo0zejsq.jpg)

nginx设置如下

```
server{
    listen 80;
    server_name w-kun.pub;
    access_log /data/wwwlogs/w-kun.pub_nginx.log combined;
    index index.html index.htm index.php;
    
    if (!-e $request_filename) {
        rewrite (.*) /index.php last;
    }
    root /data/wwwroot/shadowsocks-panel/Public;

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
            return 404;
        }
        fastcgi_pass unix:/dev/shm/php-cgi.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi.conf;
    }
} 
```

环境搭建使用了oneinstack的一键包，已改opcache.save_comments=1

**Comment by sendya** [comment]
@GHKyuU 资源包没安装，请看 最新 release 发布版说明。或者视频安装教程

**Comment by GHKyuU** [comment]
@sendya [安装了](http://wx4.sinaimg.cn/large/a9110ec1gy1fetlq394w3j215d0lnjxq.jpg)

**Comment by sendya** [comment]
@GHKyuU 在执行一次安装命令

**Comment by GHKyuU** [comment]
@sendya 

> cd /data/wwwroot/shadowsocks-panel/Resource
> rm -rf Xenon
> wget https://github.com/sendya/shadowsocks-panel/releases/download/sspanel-v1.2.0.B/Resource.zip
> unzip Resource.zip
> service nginx restart
> service php-fpm restart

⊙﹏⊙还是不行

**Comment by sendya** [comment]
@GHKyuU 天啊，我叫你在执行一次安装命令，不是让你重复装资源

**Comment by GHKyuU** [comment]
@sendya 好吧，是我理解错了，现在可以了，谢谢

**Comment by GHKyuU** [comment]
刚搭了下后端，遇到了[问题#154](https://github.com/sendya/shadowsocks-panel/issues/154)
