### ISSUE TITLE
如何取消邀请码注册功能

### ISSUE THREAD

**Issue by holyen** [sendya/shadowsocks-panel#182]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

还有充值想走支付宝这个在哪设置

**Comment by sendya** [comment]
@holyen 没有这种功能，自己二次开发

**Comment by holyen** [comment]
是否有源码说明,接口文档说明 @sendya

**Comment by sendya** [comment]
https://github.com/sendya/shadowsocks-panel/blob/master/Library/Controller/Auth.php#L116

https://github.com/sendya/shadowsocks-panel/blob/master/Library/Controller/Auth.php#L146

**Comment by sendya** [comment]
想要自己改，你可能需要读得懂代码，否则一切空谈。 代码基本上重要的地方有备注
