### ISSUE TITLE
Mail Exception: CLASS not available

### ISSUE THREAD

**Issue by nishuo** [sendya/shadowsocks-panel#184]
## 环境
**PHP** ：  7.0.5  有`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
_（发送邮件提示Mail Exception: CLASS not available）_

**Comment by sendya** [comment]
用的哪个 mail 发送方式？

**Comment by nishuo** [comment]
@sendya 
 SMTP方式

**Comment by nishuo** [comment]
不知道咋回事 重启后 已经可用了。
