### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Jiar** [sendya/shadowsocks-panel#185]
## 环境
**ubuntu** ：  16.04.1
**PHP** ：  7.0.18  无装`OpCache`
**NGINX** ： 1.10.0
**MYSQL** ： 5.7.18
**是否为升级程序** ： 否

## 问题/错误信息

安装无报错，访问时，
页面提示：File not found.
控制台提示：Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Acris** [comment]
需要手动安装资源文件。
https://github.com/sendya/shadowsocks-panel/releases/latest

**Comment by Jiar** [comment]
@Acris 资源文件是有装的。感觉是php方面问题。我这边没有php-fpm用户。服务器有装phpmyadmin，都是能正常运行的。

**Comment by sendya** [comment]
@Jiar 照着安装教程安装的吗？

**Comment by sendya** [comment]
@Jiar 能运行 phpMyAdmin 一般都能运行这个项目把

**Comment by sendya** [comment]
@Acris 地址发来我看一下

**Comment by Jiar** [comment]
@Acris 是的。。http://phpmyadmin.umeet.us/
http://shadowsocks.umeet.us/

**Comment by Jiar** [comment]
@Acris 所以nginx配置应该是没问题的。两边就路径不同，配置基本一样。但是这个程序没跑起来嘛。。

**Comment by sendya** [comment]
@Jiar nginx 配置项的 fastcgi_param 代理的 php 没配置对吧

**Comment by Jiar** [comment]
@Acris 不应该吧。。fastcgi_param两个工程都一样，都是  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

**Comment by Jiar** [comment]
`server {
        listen 80;
        server_name shadowsocks.umeet.us;
        access_log /root/web/shadowsocks.umeet.us/ss.log combined;
        index index.php;
        root /root/web/shadowsocks.umeet.us/Public;
        location ~ ^/(.+\.php)$ {
                try_files $uri =404;
                root /root/web/shadowsocks.umeet.us/Public;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
        location ~* ^/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
                root /root/web/shadowsocks.umeet.us/Public;
        }
}`

**Comment by sendya** [comment]
```
server {
        listen 80;
        server_name shadowsocks.umeet.us;
        access_log /root/web/shadowsocks.umeet.us/ss.log combined;
        index index.html index.htm index.php;
        root /root/web/shadowsocks.umeet.us/Public;

        if (!-e $request_filename) {
                rewrite (.*) /index.php last;
        }
        location ~ ^/(.+\.php)$ {
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
```

**Comment by Jiar** [comment]
@Acris 改了，nginx也重启了，还是一个样。。。见鬼

**Comment by sendya** [comment]
php 的日志打出来看一下

**Comment by sendya** [comment]
```
server {
        listen 80;
        server_name shadowsocks.umeet.us;
        access_log /root/web/shadowsocks.umeet.us/ss.log combined;
        index index.html index.htm index.php;
        root /root/web/shadowsocks.umeet.us/Public;

        if (!-e $request_filename) {
                rewrite (.*) /index.php last;
        }
        location ~ ^/(.+\.php)$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
```

**Comment by zuoshangs** [comment]
我发现有个矛盾的地方，既然nginx的root配置成了xxx.com/Public文件夹，那xxx.com/Resource/Xenon/js/bootstrap.min.js，所对应的文件夹就应该是xxx.com/Public/Resource/Xenon/js/bootstrap.min.js，可是实际上文件是在xxx.com/Resource/Xenon/js/bootstrap.min.js文件夹，所以找不到资源文件了，报404了

**Comment by sendya** [comment]
哪来的矛盾？ 资源文件在 `/Public/Resource/` 里啊

**Comment by sendya** [comment]
详细请阅读 `/index.php` 文件内 217 ~ 221 行代码 [index.php#L217](https://github.com/sendya/shadowsocks-panel/blob/master/index.php#L217)

**Comment by zuoshangs** [comment]
谢谢。我看了，xxx.com/Resource和xxx.com//Public/Resource都存在
