### ISSUE TITLE
安装完成后，管理员账号是什么呢？

### ISSUE THREAD

**Issue by zuoshangs** [sendya/shadowsocks-panel#186]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
文档没有写清楚

**Comment by sendya** [comment]
请阅读 WIKI ：
[面板安装教程#面板管理员设置](https://github.com/sendya/shadowsocks-panel/wiki/Shadowsocks-Panel-%E9%9D%A2%E6%9D%BF%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B#4-%E9%9D%A2%E6%9D%BF%E7%AE%A1%E7%90%86%E5%91%98%E8%AE%BE%E7%BD%AE)

或者 FAQ ：

[问题与解答 FAQ#新安装的面板默认管理员是?](https://github.com/sendya/shadowsocks-panel/wiki/FAQ)

Q. 新安装的面板默认管理员是?

> 程序没有默认管理员，第一个注册的账户会成为管理员。
> 管理员可以在后台用户管理中 设定用户为管理员
> 或者在数据库表admin中 新增记录，uid字段为用户的uid

**Comment by mynuolr** [comment]
放弃吧，别弄了，还不如打一局屁股

**Comment by sendya** [comment]
如何您是真心想试试看这个程序，那么建议稍微看一下 WIKI ，真没写出来的，您指出，这边开发一定会补上。
