### ISSUE TITLE
你好作者 请问如何实现 带宽限制呢？

### ISSUE THREAD

**Issue by chinalini** [sendya/shadowsocks-panel#189]
如果每个用户都疯狂下载我该怎么解决不影响其他用户

**Comment by sendya** [comment]
这个 面板 暂时无法控制，你可以从 服务器端入手考虑通过 iptables ，或者修改 SS 服务端来解决

**Comment by im8a** [comment]
manyuser端 有2017年2月更新了 带宽限速的功能
user-config.json 文件:
`
"speed_limit_per_con": 1024,  //单线程限速为1MB/s
"speed_limit_per_user": 2048, // 单端口(单用户?)限速为2MB/s`

**Comment by sendya** [comment]
额。。破娃都被气哭删库了，现在怎么对接?
------
哦对了，你说 2017/2 更新支持限速是 原版 manyuser 还是 ssr manyuser ？

**Comment by im8a** [comment]
ssr啊.. 库我fork了  可以的话我可以帮你看看对接
