### ISSUE TITLE
Bug和问题

### ISSUE THREAD

**Issue by Indexyz** [sendya/shadowsocks-panel#19]
commit 235442c的正则无法匹配邮箱（我Gmail和Hotmail都无法匹配）
以及端口可以自定义开始端口么，从1开始……

**Comment by sendya** [comment]
@Indexyz 端口默认从5000开始的。  
正则问题，刚刚修正了 请git pull一下
commit 于 [Fixed #2793c98 email pattern](https://github.com/sendya/shadowsocks-panel/commit/b5639a646655e77ca3e9aee8bef7ebd508d329ad)

**Comment by sendya** [comment]
@Indexyz 至于端口从1开始
用户UID = Port 
用户 id 从 5000开始自增
Controller\Auth.php 第 164 行开始
$user->port = $user->uid;
用户 port = 数据库自增id。
所以要自定义端口，可以根据mysql自增的主键列进行设定

**Comment by Indexyz** [comment]
嗯，可能是我导入的时候出问题了吧，现在手动设置了表的自增
