### ISSUE TITLE
Database not available! Please modify ./Data/Config.php and try again

### ISSUE THREAD

**Issue by marcolee8210** [sendya/shadowsocks-panel#190]
# 环境
CentOS 7
PHP ： 7.1.7 
NGINX ： 1.12.1
MYSQL ： 10.1.23-MariaDB
是否为升级程序 ： 否

# 问题/错误信息:
使用 master 分支直接克隆到wwwroot 目录
再执行以下步骤:
cp ./Data/Config.simple.php ./Data/Config.php
chmod -R 777 ./Data/
vim ./Data/Config.php
php index.php install

结果出现 Database not available! Please modify ./Data/Config.php and try again

**Comment by sendya** [comment]
@marcolee8210 这没错啊，提示你修改配置文件啊

**Comment by marcolee8210** [comment]
@sendya 但是在这之前我已经修改过配置文件内的 db 密码了.账户名还是 root 没动,改完还是这个提示..

**Comment by sendya** [comment]
@marcolee8210 请确认你的数据库有创建

**Comment by marcolee8210** [comment]
@sendya 已经处理好,漏了创建的步骤.,谢谢.
