### ISSUE TITLE
安装成功,进入后显示"邀请码 如遇到无邀请码请找已经注册的用户获取。"

### ISSUE THREAD

**Issue by marco-lee** [sendya/shadowsocks-panel#191]
环境:
centOS7, php7,mysql5.6,nginx 1.12.1,
问题:
安装成功,进入后显示"邀请码 如遇到无邀请码请找已经注册的用户获取。"
已经在Rescoure下重新
wget https://github.com/sendya/shadowsocks-panel/releases/download/sspanel-v1.3.0/Resource.zip
unzip Resource.zip
之后还是一样.
请问是哪部分错误了? 
补充一下.调试输出都是
404...找不到资源
都是找不到资源文件?  我 Resource 目录有在,里面的资源文件有在,都检查过了.是否什么配置未处理好?

**Comment by sendya** [comment]
资源文件解压在根目录后需要再次执行 install 命令
