### ISSUE TITLE
new install 404 not found

### ISSUE THREAD

**Issue by gucabansimon** [sendya/shadowsocks-panel#192]
hello. i have problem with install.

- successfully installed using latest release (**sspanel-v1.3.0.zip** and **Resource.zip**) 
- demo site at **vip.omayan.com**
-  root path at **/usr/share/nginx/html/shadowsocks-panel/shadowsocks-panel-sspanel-v1.3.0/Public**
- site ok on browser, but click **start** will give 404 not found (**auth/login**)

please help fix

**Comment by gucabansimon** [comment]
Also, youtube video tutorial different from actual result.

**Comment by sendya** [comment]
@gucabansimon please download Resources.zip https://github.com/sendya/shadowsocks-panel/files/1174206/Resource.zip
 to ``/usr/share/nginx/html/shadowsocks-panel/shadowsocks-panel-v1.3.0/``  and try command ``php index.php install``

**Comment by sendya** [comment]
@gucabansimon OR download Resources.zip to ``/usr/share/nginx/html/shadowsocks-panel/shadowsocks-panel-v1.3.0/`` and run command ``unzip Resources.zip``  and try agent

**Comment by sendya** [comment]
Please output php.ini configuration

**Comment by sendya** [comment]
@gucabansimon please check nginx domain.conf 

``````
if (!-e $request_filename) { 
          rewrite (.*) /index.php last;
 }
``````

**Comment by jaysonvelagio** [comment]
@sendya why the website has nothing? http://imgur.com/a/M5Msx check the link

**Comment by jaysonvelagio** [comment]
@sendya  Is there a way to easily convert the website to english?

**Comment by sendya** [comment]
@jaysonvelagio Branch [light](https://github.com/sendya/shadowsocks-panel/blob/light/Library/Language/en-US.yml#L9) support i18n, but not yet completed

**Comment by jaysonvelagio** [comment]
@sendya okay thank you sendya.
