### ISSUE TITLE
Virtual Host not found when try to connect on domain

### ISSUE THREAD

**Issue by jaysonvelagio** [sendya/shadowsocks-panel#193]
http://yamite.info/

`server {
        listen 80;
        server_name yamite.info;
        access_log /data/logs/ss.log combined;
        index index.html index.htm index.php;
        root /data/web/shadowsocks-panel/Public;

	If (! -e $ request_filename ) {
		Rewrite (. *) /index.php last ;
	} 
        location ~ .*\.(php|php5)?$ {
                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}`

Did i missed something?

**Comment by sendya** [comment]
Check if php-fpm  is running
```
service php-fpm status
```

OR

```
systemctl status php-fpm
```

And check if  php listening port or listening unix.sock file
