### ISSUE TITLE
流量清零规则

### ISSUE THREAD

**Issue by hansansui** [sendya/shadowsocks-panel#194]
请问每月首自动清零使用流量，是表示用户还没到期的情况下，使用流量就被清零了？这样怎么控制注册日期截止到期时间内的总流量呢

**Comment by sendya** [comment]
根据用户套餐类型进行分类重置

1.  用户是套餐包
> 1.1 当用户未过期时，月首自动重置已使用流量为 0 ，既可用流量为总流量
> 1.2 当用户已过期，不进行重置流量
> 1.3 当用户已过期，并购买新套餐流量，总流量切换为套餐总可用流量，并重置使用量
> 1.4 当用户未过期但流量用光，购买新套餐则立即进行重置可用流量。
> 1.5 当用户未过期，并购买新套餐流量，会提示到月末在进行套餐切换，否则当前套餐流量丢失，并覆盖为新套餐流量

2. 用户是流量包
> 2.1 当用户未过期，不进行重置
> 2.2 当用户已过期，也不进行重置

**Comment by hansansui** [comment]
好的，非常感谢！这些源码里修改会关联很多其他控制器吗？另外这个框架是自己写的吗？文档好像不是很多啊，有开发手册吗…

**Comment by sendya** [comment]
@hansansui 
框架在 https://github.com/kookxiang/KK-Framework
文档在 https://docs.ikk.me/kk-framework/

但是文档还没写全

**Comment by hansansui** [comment]
@sendya 好的，谢谢
