### ISSUE TITLE
Nothing happen on terminal when python servers.py entered 

### ISSUE THREAD

**Issue by jaysonvelagio** [sendya/shadowsocks-panel#195]
The log says 

`2017, Aug 28 Mon 02:53:48 dbtransfer.py[line:149] INFO db loop
`

what to do on this case? i perfectly installed shadowsocks-panel, but shadowsocks-rm many user didn't work.

**Comment by sendya** [comment]
Open the server firewall port (5000-9999) on `iptables`  or `firewall` .

`INFO db loop` The log is normal.

**Comment by jaysonvelagio** [comment]
@sendya still do nothing. 

![1](https://user-images.githubusercontent.com/31393796/29758619-7f875e34-8be7-11e7-8d6c-b3467ee11745.png)
![2](https://user-images.githubusercontent.com/31393796/29758626-8bb5657a-8be7-11e7-84c7-492d10695a13.png)


The log says

2017, Aug 28 Mon 03:46:59 eventloop.py[line:251] DEBUG using event model: epoll
2017, Aug 28 Mon 03:47:00 dbtransfer.py[line:149] INFO db loop
2017, Aug 28 Mon 03:47:15 dbtransfer.py[line:149] INFO db loop
2017, Aug 28 Mon 03:47:30 dbtransfer.py[line:149] INFO db loop
2017, Aug 28 Mon 03:47:45 dbtransfer.py[line:149] INFO db loop

**Comment by jaysonvelagio** [comment]
@sendya  Still not doing anything

![1](https://user-images.githubusercontent.com/31393796/29758659-dfb993e4-8be7-11e7-82ce-37340a1591ff.png)
![2](https://user-images.githubusercontent.com/31393796/29758665-e41be61c-8be7-11e7-9e20-fd81e0e2755d.png)

The log says.

2017, Aug 28 Mon 03:46:59 eventloop.py[line:251] DEBUG using event model: epoll
2017, Aug 28 Mon 03:47:00 dbtransfer.py[line:149] INFO db loop
2017, Aug 28 Mon 03:47:15 dbtransfer.py[line:149] INFO db loop
2017, Aug 28 Mon 03:47:30 dbtransfer.py[line:149] INFO db loop
2017, Aug 28 Mon 03:47:45 dbtransfer.py[line:149] INFO db loop

**Comment by jaysonvelagio** [comment]
@sendya i also disable firewalld and iptables then run the servers.py and still got a blank reply on terminal. give me tips @sendya
