### ISSUE TITLE
Can't register or login on the panel. Shows blank page on login.

### ISSUE THREAD

**Issue by jaysonvelagio** [sendya/shadowsocks-panel#196]
@sendya can you tell me how to make the registration and login works. 

![help](https://user-images.githubusercontent.com/31393796/29793899-5136b9bc-8c78-11e7-994e-e84c1fab7c8e.png)
![help2](https://user-images.githubusercontent.com/31393796/29793900-51767e26-8c78-11e7-827f-789300204e05.png)

website: http://pinoysocket.stream/ 

I am really confused. Article on wiki says that admin can get thru registration. but i cant register. I also edit the database and fill up member table. still cannot login and shows me a blank page :) give me some tip @sendya  thank you

**Comment by sendya** [comment]
@jaysonvelagio check shadowsocks-rm Config.py DB_HOST connect to shaadowdocks-panel DBHOST

**Comment by jaysonvelagio** [comment]
@sendya yes already did. it is the same database. 

![e1](https://user-images.githubusercontent.com/31393796/29809659-a931a3dc-8ccf-11e7-8634-e37965efa3c3.png)
![e2](https://user-images.githubusercontent.com/31393796/29809660-a9348e12-8ccf-11e7-9db4-1ca91945f523.png)
![e3](https://user-images.githubusercontent.com/31393796/29809777-0f33e578-8cd0-11e7-853e-34c783f464c0.png)



i just did and follow the instructions. read the wiki and all of it, can't really find the way for this to work.
all things are connected. every single detail of instruction is followed, running on centos 7 with firewalld disabled

**Comment by jaysonvelagio** [comment]
@sendya i install version 1.2 and it works fine.. the login button. the register button. so i think that your 1.3 isn't complete or bugged. I really want to make your panel work.

**Comment by sendya** [comment]
1.3 can work, please check the following possible questions

- user list empty
- shadowsocks-rm connect MYSQL server host
- shadowsocks-rm print log
- shadowsocks-rm config.py 'PRO_NODE = 0' and Panel node `pro node = 普通节点`
(/admin/node  edit ) ：
![snipaste_20170829_171259](https://user-images.githubusercontent.com/5404542/29813777-ad6aebb2-8cdd-11e7-85dd-5158547dd2e0.png)

shadowsocks-rm working log text example
```
add: {"server_port": 5000, "password":"XXXXXX", "method":"XXX"}
add: {"server_port": 5001, "password":"XXXXXX", "method":"XXX"}

INFO db loop
INFO db loop
...
```

**Comment by jaysonvelagio** [comment]
@sendya Can you tell me why after login. The website load too slow and end up to an 504 Gateway Time-out.

![gate](https://user-images.githubusercontent.com/31393796/29817721-b3c24aec-8ceb-11e7-8b22-df9bef504904.png)
