### ISSUE TITLE
After login the website loads very slow and totally declared 504 gateway time out.

### ISSUE THREAD

**Issue by jaysonvelagio** [sendya/shadowsocks-panel#197]
Note: Solved by removing cookie encryption. i don't know why the cookie encryption made the server totally not accessible and i saw many complaints here about that. just delete the cookie encryption.

**Comment by rexzerox** [comment]
![screenshot_114](https://user-images.githubusercontent.com/30548067/30043562-a4dedd58-922a-11e7-8c2b-7e76c0599b3e.png)


hello sendya why you share a fully translated in english work someone selling your open source code script here

**Comment by sendya** [comment]
@rexzerox  I do not know, My active community is in China. And the project free, downlaod from here : https://github.com/sendya/shadowsocks-panel


> If you can translate this project free of charge, you can translate and send a merge request to this project. I will add the translator to the development team.
> Note: no wages

**Comment by rexzerox** [comment]
thanks @sendya hope @jaysonvelagio  will release a free source code of his translated version too coz he intended this code for selling purpose not for free

**Comment by mynuolr** [comment]
![ag71 b4 v_o6pz p53y_g y](https://user-images.githubusercontent.com/3831242/30044137-22ed9984-922e-11e7-846a-395a2ffdd756.png)

**Comment by jaysonvelagio** [comment]
@rexzerox lol you are the first one to comment on the post not me. Stop complaining about my reply, just got an idea from you that i can do the installation service on the person who wants the panel.

![aaaaa](https://user-images.githubusercontent.com/31393796/30058598-50451336-926e-11e7-8f94-d4c5bb3c1d13.png)
