### ISSUE TITLE
How to add more vps server in sendya panel?

### ISSUE THREAD

**Issue by rexzerox** [sendya/shadowsocks-panel#198]
I just wanted to know on how it works to add more servers in this source since i got a lot of vps which hosted in other provider.  is this posible ? then please let me know.. some problems ive encounter is after editing some  pages ( well im an english so i need to translate it to my desired language)  the notification message  for users and package details.  doesnt show anymore. im using the old version v1.9.0 this version works fine for me.

**Comment by sendya** [comment]
dashboard / admin / node / (+) add button

input your node info and run node vps shadowsocks manyuser

**Comment by rexzerox** [comment]
sir @sendya  i really dont get  i add sever in my other vps in admin/add node
then i  add
# Pro node 1 true , others false
PRO_NODE = 0

the servers doents work.


in the screenshot below
singapore is working which is main vps

france other vps but still not working please let me know on how to add step by step
it would be helpful to me if u response my problem

![screenshot_122](https://user-images.githubusercontent.com/30548067/30054052-5f41db5a-925d-11e7-9f4c-fecef259a0bc.png)


other question:  do i need to install phpmyadmin in my other vps?
i really dont get on how it works

**Comment by sendya** [comment]
I am now working and will give you a solution later.

**Comment by rexzerox** [comment]
thanks master sendya ,

**Comment by sendya** [comment]
@rexzerox 
No need to install mysql / phpmyadmin, other node vps need open firewall  port 5000~9999 and Connect paenl server mysql (Turn on remote connection permissions)

**Comment by sendya** [comment]
config.py
<img width="609" alt="sp_20170905_221155" src="https://user-images.githubusercontent.com/5404542/30065318-f7331180-9286-11e7-8088-83f936ec41d3.png">

runing
<img width="558" alt="sp_20170905_221041" src="https://user-images.githubusercontent.com/5404542/30065317-f6fcfc44-9286-11e7-9bf7-17e825d63569.png">

The screen output   `add: {"server_port": xxxx, "password":"xxxx", "method":"xxxxx"}`  stands for success

**Comment by rexzerox** [comment]
Thanks for the great response sendya senpai :)

in my other vps how to config the shadowsocks?
i encounter this problem
![screenshot_128](https://user-images.githubusercontent.com/30548067/30106876-7e626f68-932f-11e7-98d6-7c41b0b819ee.png)

i install manyuser and already create database name shadowsocks
and import the sql

after starting the server.py that is the response


so e rename user to member and here the response
![screenshot_129](https://user-images.githubusercontent.com/30548067/30107184-9189200e-9330-11e7-9e16-312415e19c56.png)

this vps is my other server ang want to add as pro node.
but the shadowsocks  vip.omayan.com vps work fine..

![screenshot_130](https://user-images.githubusercontent.com/30548067/30107927-e28eb7b4-9332-11e7-9d47-b4717363cf84.png)

**Comment by sendya** [comment]
DO NOT CREATE A DATABASE AT THE NODE SERVER !!!!!!
Please connect to a remote MYSQL server (shadowsocks-panel server mysql )

**Comment by rexzerox** [comment]
@sendya senpai please tell me how to remote the server thats my big problem i dont know how to remote the myql big thanks for the response

**Comment by sendya** [comment]
```
MYSQL_HOST = 'your master node server(shadowsocks-panel server)'
MYSQL_PORT = 'your master node MySQL port'
MYSQL_USER = 'mysql username'
MYSQL_PASS = 'password'
MYSQL_DB = 'shadowsocks panel db name'
```
Open firewalld MYSQL port And allow mysql remote connect user
link: https://stackoverflow.com/questions/14779104/how-to-allow-remote-connection-to-mysql

**Comment by sendya** [comment]
@rexzerox What is senpai?

**Comment by jaysonvelagio** [comment]
lol you don't need to create database on a node server, just point your node server mysql info to the remote server or the panel database. make sure remote database accept connection to any host. 

And stop complaining to sendya about my comment on symbianize, you are the first one who make a comment there. don't be like a kid complaining things with his mother.

**Comment by rexzerox** [comment]
@jaysonvelagio jayson hindi ko parin ma gets hehe example
yung france server ko eh wala siyang shadowsocks-panel  paano ko ma point yung server na yan dun sa vip.omayan.com na may shadowsocks panel?
anung vps ang need ko e remote ang main na vip.omayan or ang france na vps

**Comment by rexzerox** [comment]
@sendya btw thanks for the help sendya ill try to get rid of these problem and will close the issue if i resolve this case thanks for your efforrt for helping to us.

**Comment by sendya** [comment]
If you still do not understand, I have no way to help you.

<img width="958" alt="sp_20170906_202318" src="https://user-images.githubusercontent.com/5404542/30111617-f554af08-9340-11e7-8bb3-e31e9542e392.png">

**Comment by rexzerox** [comment]
Its really help me a lot now i figured it out on how it works your the best @sendya senpai the screenshot you posted was really wake me up. and its working now.... more power to your and looking forward to your panel .

![screenshot_131](https://user-images.githubusercontent.com/30548067/30115843-77d6d28c-934e-11e7-8c01-f46d9c21d3c5.png)
