### ISSUE TITLE
邮件发送设置，帮忙举个例子呗？试了很多次不成功。

### ISSUE THREAD

**Issue by kilobps** [sendya/shadowsocks-panel#199]
主要问题是不知道该填什么参数，是填xxx呢，还是xxx@163.com呢？

# mailgun
$System_Config['mailgun_key'] = 'key-d35fdd393ced0bd';
$System_Config['mailgun_domain'] = 'sandb79b661251f1c87446d.mailgun.org';
$System_Config['mailgun_sender'] = 'xxx@xxx.com';

# smtp
$System_Config['smtp_host'] = 'smtp.163.com';
$System_Config['smtp_username'] = 'xxx@xxx.com';
$System_Config['smtp_port'] = '25';
$System_Config['smtp_name'] = 'xxx@163.com';
$System_Config['smtp_sender'] = 'xxx';
$System_Config['smtp_passsword'] = 'xxx';
$System_Config['smtp_ssl'] = 'false';

**Comment by sendya** [comment]
程序默认有初始值，照着初始值填写就行

**Comment by sendya** [comment]
如果用 smtp ，服务器禁止了 25 等邮件端口，是不能发送到
