### ISSUE TITLE
首页报错

### ISSUE THREAD

**Issue by echoowall** [sendya/shadowsocks-panel#20]
Fatal error: Uncaught exception 'Core\Error' with message 'Cannot write template file: /home/wwwroot/test.miaoss.win/Data/Template/Misc/Error.php' in /home/wwwroot/test.miaoss.win/Library/Core/Template.php:144 Stack trace: #0 /home/wwwroot/test.miaoss.win/Library/Core/Template.php(30): Core\Template::compile('Misc/Error') #1 /home/wwwroot/test.miaoss.win/Library/Core/Error.php(78): Core\Template::load('Misc/Error') #2 /home/wwwroot/test.miaoss.win/Library/Core/Error.php(55): Core\Error::handleUncaughtException(Object(Core\Error)) #3 [internal function]: Core\Error::handlePHPError(2, 'mkdir(): Permis...', '/home/wwwroot/t...', 289, Array) #4 /home/wwwroot/test.miaoss.win/Library/Core/Template.php(289): mkdir('/home/wwwroot/t...', 511) #5 /home/wwwroot/test.miaoss.win/Library/Core/Template.php(288): Core\Template::createDir('/home/wwwroot/t...', 511) #6 /home/wwwroot/test.miaoss.win/Library/Core/Template.php(138): Core\Template::createDir('/home/wwwroot/t...') #7 /home/wwwroot/test.miaoss.win/Library/Core/Template.php(30): in /home/wwwroot/test.miaoss.win/Library/Core/Template.php on line 144

**Comment by sendya** [comment]
@echoowall 好好的按照 README.md 安装，谢谢。

**Comment by sendya** [comment]
@echoowall 人家提示不是已经说了 没权限 mkdir()

**Comment by sendya** [comment]
安装教程里有明白的写 

```bash
$ cp ./Data/Config.simple.php ./Data/Config.php
$ vim ./Data/Config.php
$ chmod -R 777 ./Data/
$ mysql -uroot -p
```

```$ chmod -R 777 ./Data/```

**Comment by echoowall** [comment]
弄好了·谢谢您，但是有个问题，我在用邀请码注册的时候，无论什么邮箱都提示邮箱格式不正确，是什么鬼·····

**Comment by sendya** [comment]
@echoowall git pull 最新版

**Comment by echoowall** [comment]
反馈一个问题，注册成功后不会自动跳转登录

**Comment by sendya** [comment]
@echoowall 并不是问题。  我故意改的不跳转

**Comment by sendya** [comment]
@echoowall 需要跳转自己去改 login.htm 第 162行被注释的代码

**Comment by echoowall** [comment]
请问admin从哪里添加

**Comment by sendya** [comment]
@echoowall 默认注册的第一个用户是 admin权限，要自己添加 在 user_power 表内 增加一个对应 uid 的数据
