### ISSUE TITLE
端口不显示

### ISSUE THREAD

**Issue by ller** [sendya/shadowsocks-panel#21]
连接信息
端口：
密码：点击显示密码

端口哪里没有显示

**Comment by kuertianshi** [comment]
配置文件关闭A PLAN  或者不要分A组

**Comment by ju0594** [comment]
@kuertianshi A PLAN有问题？

**Comment by sendya** [comment]
如果配置这个 ，不去改，用默认的 `false`  A PLAN就能设定 uid

```php
define('ENABLE_PLAN_A', false);
```

**Comment by kuertianshi** [comment]
@ju0594   #17

**Comment by ju0594** [comment]
@sendya 这个文件在哪里？

**Comment by ju0594** [comment]
@sendya 后台已生成的邀请码删不掉 还有define('ENABLE_PLAN_A', false);在哪？找不到。。，

**Comment by sendya** [comment]
@ju0594  居然删不掉？我测试过好久了= = 有报错什么的吗

**Comment by sendya** [comment]
@ju0594 [Fixed invite remove...more](https://github.com/sendya/shadowsocks-panel/commit/12b5b35991dcedaef61196905350cc7fbc794d7a)
修正了。忘记修改js函数名。

**Comment by ju0594** [comment]
@sendya 删除成功 刷新了又出来了

**Comment by sendya** [comment]
@ju0594 修正了。

**Comment by ju0594** [comment]
@sendya 可以啦
