### ISSUE TITLE
邀请码生成的都是公共的

### ISSUE THREAD

**Issue by ju0594** [sendya/shadowsocks-panel#23]
即使是花流量购买的邀请码。。。
建议花流量生成的为私密不在公共页面显示，不然生成了被别人用了就尴尬了(─.─|||
管理员后台生成的也建议加个私密选项
还有就是批量生成选项了。。。
建议服务器数点击进入节点列表，每次我看了都想点。

**Comment by sendya** [comment]
@ju0594 流量生成的邀请码一直是私密的啊，本身就不会在公共页面显示。
公共页面显示的只有 `-1` 类型的邀请码。

**Comment by sendya** [comment]
@ju0594 下一个版本才会有 批量生成
页面显示需求 自己去改， 吾辈不可能为了一个人改整个gayhub上的代码

**Comment by ller** [comment]
啥时候出下个版本

**Comment by ju0594** [comment]
@sendya 抱歉，成伸手党了，提的都不是有建设性的意见。

**Comment by sendya** [comment]
@ller @ju0594 
这周末之前出来下个版本吧。所有还有需要增加的功能 或者不满意的功能可以提一下

**Comment by ju0594** [comment]
@sendya 锁屏界面添加注销按钮
顺便问下邮件发信怎么设置？我这样设置好像不行。
`$MAIL = array(
	'host' => 'smtp.exmail.qq.com',
	'username' => 'admin@vlink.xyz',
	'password' => 'xxxxxxxxxxx',
	'from'     => 'Vlink加速 <admin@vlink.xyz>',
	'secure' => ''
);`
密码用的是生成的授权码（QQ域名邮箱已绑定）

**Comment by sendya** [comment]
@ju0594 锁屏界面为什么要注销，特意做个锁屏就是为了防止他人登录账户，或者改变当前状态。还注销留锁屏什么意义，你直接Config里把锁屏服务关闭就得了

**Comment by ju0594** [comment]
@Sendya 有些人忘记密码的话就可以注销啊 PC上类似这样…

**Comment by ller** [comment]
@sendya 能不能加个自定义套餐的名字流量价格等。

**Comment by sendya** [comment]
@ller 看情况，应该能。

**Comment by ju0594** [comment]
@sendya 所有节点出现can not bind to manager adress…用的第一个ss版本，帮忙这是什么情况？

**Comment by sendya** [comment]
@ju0594 can not bind to manager address  无法绑定到管理地址
配置文件不会改的。就不要乱改了。不开放管理端口的情况下，即使默认密码，别人也放问不进来。  有问题，去看shadowsocks-rm的作者github上安装说明

**Comment by ller** [comment]
@ju0594 你弄好了吗。端口显示不

**Comment by ju0594** [comment]
@ller 什么端口？

**Comment by ju0594** [comment]
@sendya 没有乱动配置 就配置了数据库和加密方式，我现在已经把带数据库那个节点的vps重置了，又可以用了，但是另外两个节点还是不行(这两个节点昨天配置可以用后就没动过)

**Comment by ller** [comment]
@ju0594 你对接SS后端成功没。。我对接不上。不知道什么问题

**Comment by sendya** [comment]
@ller ss端 数据库地址  账户密码 填写对了 直接启动就行了 。 又不需要做别的配置

**Comment by ju0594** [comment]
@sendya 是lnmp自带iptables屏蔽了3306 不过上次明明删掉了那条规则，不知道怎么又出现了…

**Comment by ju0594** [comment]
@ller 本地的数据库还是远程的 远程的话先授权 再允许3306端口
