### ISSUE TITLE
话说直接把商业主题发到github不太好吧...

### ISSUE THREAD

**Issue by ornodus** [sendya/shadowsocks-panel#25]
没错的话主题应该是这个？
http://themeforest.net/item/xenon-bootstrap-admin-theme-with-angularjs/9059661

如果是个人的license是有限制的

 

> Use, by you or one client, in a single end product which end users <strong>are not</strong> charged for. The total price includes the item price and a buyer fee.

**Comment by sendya** [comment]
嗯 个人license没错。

**Comment by ju0594** [comment]
好高端的样子

**Comment by sendya** [comment]
@ornodus  (懵逼脸    面板不放出来有人喷 sspanel 开源，吾辈这不开源，放出来有接单sspanel改版的喷， 这主题我自己掏钱买的，有人看到了。要向我买，我说自己去外面买。 后来一堆喷没分享精神，我就丢上来了，有机会在换个主题吧，如果你去tf提交license制裁也行
