### ISSUE TITLE
请问邮箱发信功能完成了吗？

### ISSUE THREAD

**Issue by ju0594** [sendya/shadowsocks-panel#26]
问一下，看到管理后台多了功能，设置了下不行。

**Comment by sendya** [comment]
@ju0594 已经可以发送了阿= =，今天测试过 应该没问题。

**Comment by ju0594** [comment]
@sendya 酱紫，config.php里的`'secure' => ''`字段要填吗，我不知道填啥呃。

**Comment by sendya** [comment]
@ju0594 不是 SSL方式发送不用

**Comment by ju0594** [comment]
@sendya QQ邮箱现在强制了SSL。那该怎么填？还是换个不用SSL的。。。

**Comment by sendya** [comment]
@ju0594 exmail 没有强制把。。。 25端口可以的

**Comment by ju0594** [comment]
$MAIL = array(
	'host' => 'smtp.exmail.qq.com',
	'username' => 'admin@vlink.xyz',
	'password' => 'xxxxxx',（用的授权码）
	'from'     => 'Vlink<admin@vlink.xyz>',
	'secure' => ''
);
@sendya 呃 那我设置错了吗？
