### ISSUE TITLE
点击套餐升级，导致数据库被初始化

### ISSUE THREAD

**Issue by mouyuemoyu** [sendya/shadowsocks-panel#28]
数据库里面改了账户余额，用户账户点击升级套餐后，显示升级成功，然后数据库中的数据就被初始化到刚搭建的状态了

**Comment by sendya** [comment]
@mouyuemoyu 升级套餐的接口都没连通，怎么做到的...

**Comment by sendya** [comment]
@mouyuemoyu 算了，有问题等4号过了在找了。现在不在电脑面前 这几天时间也都不会在电脑面前，烦请稍等几日

**Comment by mouyuemoyu** [comment]
恩恩， 辛苦啦

**Comment by sendya** [comment]
检查代码，并且在全新环境搭建一份新的站点 测试后，升级账户等级，A~D均一切正常。 没出现过你说的数据被初始化。
**程序里也没有能让数据初始化的代码**

一般情况可能是你的数据库结构不是新的。常试导入 `.\Data\Shadowsocks-planel-DB.sql` 试试
