### ISSUE TITLE
http://xxx.xxx/cron.html 执行出错

### ISSUE THREAD

**Issue by conupefox** [sendya/shadowsocks-panel#30]
第一次curl 显示ok

之后一直
Parse error: syntax error, unexpected '.', expecting ',' or ';' in /opt/shadowsocks-panel/Library/Helper/Setting.php on line 18

应该怎么弄？

**Comment by sendya** [comment]
@conupefox 改动过 cron 的数据表吗？

**Comment by sendya** [comment]
经过测试并没出现这个问题，请尝试用最新的DB数据库结构以及默认数据内容。
如果是你改过`cron`表里的数据，那么这里不接受此等issue

**Comment by conupefox** [comment]
什么都没改，就是按照github上面的流程跑的。。

mysql> select * from cron;
+----------------+---------+------------+-------+
| id             | enabled | nextrun    | order |
+----------------+---------+------------+-------+
| clearInviteOld |       0 | 1461690331 |   110 |
| clearTransfer  |       1 | 1462032000 |    10 |
| daily          |       0 | 1459094400 |   100 |
| mail           |       0 | 1459011931 |    80 |
| stopExpireUser |       1 | 1459024168 |    30 |
+----------------+---------+------------+-------+
5 rows in set (0.00 sec)

mysql> 

curl http://localhost/cron.html  
<br />
<b>Parse error</b>:  syntax error, unexpected '.', expecting ',' or ';' in <b>/opt/shadowsocks-panel/Library/Helper/Setting.php</b> on line <b>18</b><br />

由于没有https，是不能用http？  还是我有什么东西没装好

**Comment by sendya** [comment]
@conupefox const CONFIG_FILE = DATA_PATH . "Config.php";
18行 是这个报错  . 和 ;    我也不知道为什么。  你php版本是多少

**Comment by conupefox** [comment]
php --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Comment by sendya** [comment]
@conupefox 不清楚什么状况了。其他功能有受影响吗?

**Comment by conupefox** [comment]
这个功能用不了的话。是不是用户有效期和流量按月清零就用不到了？

其他功能暂时没发现什么问题

**Comment by sendya** [comment]
@conupefox 现在 计划任务 的列表页内的 #clearTransfer  #stopExpireUser 状态和时间 发给我看下

**Comment by conupefox** [comment]
不好意思，之前有点忙没及时回复。

计划任务里面的信息如下


任务	说明	下次运行时间	状态	优先级
#clearInviteOld		2016-04-27 01:05:31	停用	110
#clearTransfer		2016-05-01 00:00:00	尚未运行	10
#daily		2016-03-28 00:00:00	停用	100
#mail		2016-03-27 01:05:31	停用	80
#stopExpireUser		2016-03-27 04:29:28	运行完毕	30

**Comment by sendya** [comment]
@conupefox 去升级 https://github.com/sendya/shadowsocks-panel/releases/tag/sspanel-v0.41 这个版本，问题都修正了。
