### ISSUE TITLE
第一个账户注册失败，然后GG

### ISSUE THREAD

**Issue by rootliang** [sendya/shadowsocks-panel#31]
搭建完之后第一个账户注册失败，然后就注册不了。shadowsocks哪个服务器版本好用？

**Comment by sendya** [comment]
@rootliang 不知道你到底要问什么

**Comment by rootliang** [comment]
就是会注册账号失败，给你提个BUG
顺便问一下哪个版本稳定

**Comment by sendya** [comment]
@rootliang 1.  注册账号都会失败，我肯定不会把代码丢出来让别人用
2.  市面上的 shadowsocks-manyuser 都挺稳的的。

检查一下数据库、配置文件 是否配对，数据库是否导入

**Comment by rootliang** [comment]
数据库导入了，可能那时候用手机UC注册的可能跳转了一下吧，你知道了就好就可以关啦，不打扰言肆小可爱

**Comment by sendya** [comment]
@rootliang 你谁？

**Comment by rootliang** [comment]
之前群里眼熟你啦，ghost

**Comment by sendya** [comment]
@rootliang ban不谢
