### ISSUE TITLE
登陆后进入仪表盘时候就一直加载，页面中间转圈

### ISSUE THREAD

**Issue by ToyoDAdoubi** [sendya/shadowsocks-panel#33]
死活进不去啊。。
还有就是面板安装步骤似乎有问题？一些步骤莫名其妙，一些文件夹也没有。。

**Comment by sendya** [comment]
@ToyoDAdoubi 讲明白点

**Comment by ToyoDAdoubi** [comment]
F12 手动删掉<div class="page-loading-overlay">代码就显示正常页面了，估计问题是首次进入，过渡加载无能正确关闭！

**Comment by sendya** [comment]
@ToyoDAdoubi 很明显是脚本没加载到， 跟布局半毛钱关系都没

**Comment by ToyoDAdoubi** [comment]
`我擦，不让写代码.`<div class="page-loading-overlay">`

**Comment by ToyoDAdoubi** [comment]
那怎么解决那...

**Comment by sendya** [comment]
@ToyoDAdoubi 哪个脚本加载不到就补上哪个脚本啊，既然你都那么厉害会删代码了 何尝不试试console是什么脚本挂掉导致页面不加载的

**Comment by kuertianshi** [comment]
同遇到此问题，萌新表示不会改

**Comment by sendya** [comment]
@kuertianshi 浏览器F12看什么东西加载失败了
