### ISSUE TITLE
【报告BUG】仪表盘问题

### ISSUE THREAD

**Issue by hpfs0** [sendya/shadowsocks-panel#34]
首次进入仪表盘会先显示产生的总流量数，但是点击左侧菜单的仪表盘按钮后，绿色数字变成0

**Comment by sendya** [comment]
@hpfs0 
PJAX 的锅，在新版本上已经修复了。

**Comment by hpfs0** [comment]
那旧版如何修复可以说下吗？

**Comment by sendya** [comment]
@hpfs0 
`Template/Default/panel/member.htm`
搜索：`{SITE_NAME} 已经产生流量<code>`
将上面那行的
```
<div class="h4 text-secondary text-bold" data-count="this" data-from="0.00" data-to="{$systemTransfer}" data-suffix="GB" data-decimal="." data-duration="2">0</div>
```
改成
```
<div class="h4 text-secondary text-bold" data-count="this" data-from="0.00" data-to="{$systemTransfer}" data-suffix="GB" data-decimal="." data-duration="2">{$systemTransfer}</div>
```

**Comment by hpfs0** [comment]
@sendya 

非常感谢，我试下。

**Comment by hpfs0** [comment]
@sendya 

反馈下：
按上面提示改好后
第一次进入显示0GB
第二次点击仪表盘数字消失
求解？

**Comment by sendya** [comment]
@hpfs0 
抱歉，给错变量了。那是新版本的变量
重新改成这样
```
<div class="h4 text-secondary text-bold" data-count="this" data-from="0.00" data-to="{$transferAllFlow}" data-suffix="GB" data-decimal="." data-duration="2">{$transferAllFlow}</div>
```

**Comment by hpfs0** [comment]
@sendya 
谢谢，按照方法改成下面这样好了
`<div class="h4 text-secondary text-bold" data-count="this" data-from="0.00" data-to="{$transferAllFlow}" data-suffix="GB" data-decimal="." data-duration="2">{$transferAllFlow}GB</div>`

**Comment by hpfs0** [comment]
默默的问下新版是master里的吧？

**Comment by sendya** [comment]
@hpfs0 dev分支
