### ISSUE TITLE
求助mail的配置

### ISSUE THREAD

**Issue by hpfs0** [sendya/shadowsocks-panel#36]
在Config.php里配置了mail的信息后，smtp服务器是smtp.gmail.com，但是gmail的话貌似走的是ssl验证，这样会报错，请问应该怎么配置

$MAIL = array(
	'host' => 'smtp.gmail.com',
	'username' => 'xxxxx',
	'password' => 'xxxxx',
	'from'     => 'xxxxx',
	'secure' => ''    // 需要填写secure？
);

**Comment by sendya** [comment]
@hpfs0 ..这我还真不知道，这个 支持库的官方也很傻逼的docs文档没写完整。  我还在写 Mailer类，过段时间就能支持 SMTP / PHP自带函数 / 邮件代发 / MailGun 。
建议现在还是暂时换一个 邮件服务商把。

**Comment by hpfs0** [comment]
@sendya 可否给个qq mail的配置sample吗？

**Comment by sendya** [comment]
@hpfs0 'secure' => 'ssl',

**Comment by sendya** [comment]
@hpfs0 默认的配置就是 QQ的mail ,只不过我的是exmail。 换成 mail.qq.com 即可

**Comment by hpfs0** [comment]
@sendya 设置了直接报 Invalid find pwd! The header 'From' expects to be email, integer given.

**Comment by hpfs0** [comment]
@sendya 是否QQ mail需要开启下面这两个
POP3/SMTP服务 (如何使用 Foxmail 等软件收发邮件？)   已关闭 |  开启
IMAP/SMTP服务 (什么是 IMAP，它又是如何设置？) 已关闭 |  开启

**Comment by sendya** [comment]
@hpfs0 不开怎么发...

**Comment by hpfs0** [comment]
@sendya  我刚才开启了IMAP/SMTP服务，但是貌似还是无法发送

**Comment by sendya** [comment]
@hpfs0 后台 邮件测试

**Comment by hpfs0** [comment]
@sendya 刚刚配置成功了，发了邮件。但是给的那个code不能用来登录，还是原来的密码是正确的。求解？邮件内容大概是下面这样：

[xxxxx] Password Recovery

Dear xxxxx:
Use this code to disable your password and access your xxxxx account:

Code: mNANFe8wCP 

Yours, The xxxxx Team

**Comment by sendya** [comment]
@hpfs0 亲爱的用户，这个 代码 是用来禁止你账户的密码的

**Comment by sendya** [comment]
@hpfs0 这里面有说这是新密码让你登录的吗?  你见过哪个网站找回密码是 二话不说生成个新密码就往邮箱发的?

**Comment by sendya** [comment]
@hpfs0 而且找回密码的界面 都是 “中文”，难道也看不懂？页面上的提示也没说 你找回密码成功，发送新密码到你的邮箱里 把？

**Comment by sendya** [comment]
@hpfs0 你说要迁移教程，我还特意把 找回密码 和后续修改系统参数的步骤都做出来了。你有看？

**Comment by hpfs0** [comment]
@sendya 抱歉，我先罗列一下我遇到的问题。
1.禁止你账户的密码，这个我真没理解怎么操作。
2.是没见过哪个网站找回密码是 二话不说生成个新密码就往邮箱发的，所以我也只是猜测，原因是我没找到这个code的用法。
3.我目前还没升级到新版本的，所以不会存在密码加密方式的问题。你给的迁移教程我也看了。

**Comment by sendya** [comment]
@hpfs0 既然你都看了 难道就看不到  找回密码是两个步骤吗?  难道大部分网站都不发验证码直接发新密码给你吗?

**Comment by hpfs0** [comment]
@sendya 可能是我没描述清楚，我现在就是找不到填写验证码的地方，在找回密码界面目前只显示一个填写邮件的输入框。。

**Comment by sendya** [comment]
@hpfs0 去看迁移教程下面的找回密码步骤

**Comment by hpfs0** [comment]
@sendya 原来我是一只在issue里看的，迁移教程没显示完整。。。刚才到wiki里看了终于知道了，感谢耐心指导，麻烦了
