### ISSUE TITLE
升级后重置密码出错

### ISSUE THREAD

**Issue by deamwork** [sendya/shadowsocks-panel#38]
已经按照wiki中的步骤去做了，重置密码时出现：
The request URL is not available 这个错误

**Comment by sendya** [comment]
@deamwork 是哪一个版本？

**Comment by sendya** [comment]
@deamwork 1.02？

**Comment by deamwork** [comment]
嗯 1.02

**Comment by sendya** [comment]
@deamwork 请问 nginx 配置的是 shadowsocks-panel/Public 的路径吗

**Comment by deamwork** [comment]
没错，
root /data/wwwroot/ss.xxx.com/Public;

**Comment by sendya** [comment]
@deamwork 不好意思，建议你git clone 一份最新的代码。

**Comment by deamwork** [comment]
如果有帮助的话：我是直接wget您这的release

**Comment by sendya** [comment]
@deamwork 替换1.02后 php index.php install  在试试找回。  我之前在本地测试下载的zip 没问题，可能是我遗漏了什么

**Comment by deamwork** [comment]
php index.php install 后问题依旧

**Comment by sendya** [comment]
@deamwork 其他页面正常吗？

**Comment by sendya** [comment]
@sendya 有TG或者qq吗，我可能需要Library/Controlle 的目录文件列表图…才比较好解决。

**Comment by sendya** [comment]
@sendya 咦…点错回复

**Comment by deamwork** [comment]
都能访问，但是提交表单都返回这个错误（登录和注册返回的内容不一样，但是我F12后看到的内容也是URL那个）

**Comment by sendya** [comment]
@deamwork nginx伪静态对的吗

**Comment by deamwork** [comment]
nginx按照wiki要求已经配置好正确的root，以及路由

**Comment by deamwork** [comment]
是伪静态的

**Comment by deamwork** [comment]
`server {
listen 80;
server_name ss.xxx.com;
access_log /data/wwwlogs/ss.xxx.com_nginx.log combined;
index index.html index.htm index.php;
include /usr/local/nginx/conf/other.conf;
root /data/wwwroot/ss.xxx.com/Public;

location ~ .*\.(wma|wmv|asf|mp3|mmf|zip|rar|jpg|gif|png|swf|flv)$ {
    valid_referers none blocked *.xxx.com ss.xxx.com;
    if ($invalid_referer) {
        #rewrite ^/ http://www.linuxeye.com/403.html;
        return 403;
        }
    }
location ~ .*\.(php|php5)?$ {
    #fastcgi_pass remote_php_ip:9000;
    fastcgi_pass unix:/dev/shm/php-cgi.sock;
    fastcgi_index index.php;
    include fastcgi.conf;
    }
if (!-e $request_filename) {
    rewrite (.*) /index.php last;
}
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
    expires 30d;
    access_log off;
    }
location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
    }
}`

**Comment by sendya** [comment]
@deamwork 
```
server{
    listen 80;
    server_name sscat.it www.sscat.it;
    access_log /home/wwwlogs/sscat_nginx.log combined;
    index index.html index.htm index.php;
    root /home/wwwroot/shadowsocks-panel/Public; 
   if (!-e $request_filename) {
        rewrite (.*) /index.php last;
    }
    
    location ~ .*\.(php|php5)?$  {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
}
```
root这行改到上面 reload再试试。。

**Comment by deamwork** [comment]
刚刚贴出了我的配置....

**Comment by sendya** [comment]
@deamwork 不行。  路由 要在 php location 的前面

**Comment by deamwork** [comment]
试了，问题依旧

**Comment by sendya** [comment]
@deamwork 手动访问 xxx.com/cron  是什么内容

**Comment by deamwork** [comment]
返回404

贴上刚刚您需要的目录内容：
total 64
drwxr-xr-x 2 www www  4096 Apr 15 00:40 Admin
-rw-r--r-- 1 www www   338 Apr 11 08:43 Admin.php
-rw-r--r-- 1 www www   837 Apr 11 08:43 Api.php
-rw-r--r-- 1 www www  7901 Apr 11 11:12 Auth.php
-rw-r--r-- 1 www www   335 Mar  9 10:15 BaseAction.php
-rw-r--r-- 1 www www  3932 Apr 11 18:07 Card.php
-rw-r--r-- 1 www www   405 Mar 28 11:33 Cron.php
-rw-r--r-- 1 www www   453 Apr 11 08:43 Index.php
-rw-r--r-- 1 www www  1132 Mar  9 10:15 Install.php
-rw-r--r-- 1 www www  1895 Apr 11 08:43 Invite.php
-rw-r--r-- 1 www www 10876 Apr 11 11:20 Member.php
-rw-r--r-- 1 www www  3165 Apr 11 08:43 Node.php
-rw-r--r-- 1 www www   388 Apr 11 08:43 Support.php

**Comment by sendya** [comment]
@deamwork 手动访问 https://love.loacg.com/auth/register.json 也是 404把

**Comment by sendya** [comment]
@deamwork 如果也是 就肯定是 rewrite 不对。

**Comment by deamwork** [comment]
{"code":403,"data":null,"hasError":true,"message":"The request URL is not available"}

**Comment by sendya** [comment]
@sendya 把我的域名坏成你的。

**Comment by sendya** [comment]
@deamwork 。。。等等…这个错误

**Comment by sendya** [comment]
@deamwork 麻烦把 Public/index.php 内容贴一下…

**Comment by deamwork** [comment]
> <?php
> /**
>  * KK-Framework
>  * Author: kookxiang <r18@ikk.me>
>  */
> 
> // Initialize constants
> define('ROOT_PATH', dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR);
> define('LIBRARY_PATH', ROOT_PATH . 'Library/');
> define('DATA_PATH', ROOT_PATH . 'Data/');
> define('TIMESTAMP', time());
> @ini_set('display_errors', 'on');
> @ini_set('expose_php', true);
> 
> // Register composer
> require ROOT_PATH . 'Package/autoload.php';
> 
> // Register error handler
> Core\Error::registerHandler();
> 
> // Initialize config
> @include DATA_PATH . 'Config.php';
> 
> // Handler for user power
> Core\Filter::register(new Helper\LoginFilter());
> // Handler for json request
> Core\Filter::register(new Helper\JSON());
> 
> $defaultRouter = new Core\Router();
> $defaultRouter->handleRequest();

**Comment by sendya** [comment]
@deamwork php 什么版本… 我在本地在测试了一下还是没问题 。。

**Comment by deamwork** [comment]
PHP 7.0.4 (cli) (built: Mar 17 2016 17:27:19) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by deamwork** [comment]
nginx version: nginx/1.9.12
built by gcc 4.9.2 (Debian 4.9.2-10) 
built with OpenSSL 1.0.1k 8 Jan 2015
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-ipv6 --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-ld-opt='-ljemalloc'

mysql  Ver 14.14 Distrib 5.7.11, for Linux (x86_64) using  EditLine wrapper

**Comment by sendya** [comment]
@deamwork Core 目录麻烦也列一下吧。
真没发现是哪里的问题 看来都是 .json路径炸了

**Comment by deamwork** [comment]
# tree Library/Core/
Library/Core/
|-- Database.php
|-- DefaultRouter.php
|-- Error.php
|-- Filter.php
|-- IFilter.php
|-- Model.php
|-- Request.php
|-- Response.php
|-- Router.php
`-- Template.php

0 directories, 10 files

# ls -l Library/Core/
total 48
-rw-r--r-- 1 www www 2027 Apr 11 08:43 Database.php
-rw-r--r-- 1 www www 1851 Apr  7 10:55 DefaultRouter.php
-rw-r--r-- 1 www www 3491 Apr  7 10:55 Error.php
-rw-r--r-- 1 www www 1662 Apr  7 10:55 Filter.php
-rw-r--r-- 1 www www  324 Apr  7 10:55 IFilter.php
-rw-r--r-- 1 www www 3975 Apr 11 08:43 Model.php
-rw-r--r-- 1 www www 1475 Apr  7 10:55 Request.php
-rw-r--r-- 1 www www 1615 Apr  7 10:55 Response.php
-rw-r--r-- 1 www www  363 Apr 11 08:43 Router.php
-rw-r--r-- 1 www www 8327 Apr 11 08:43 Template.php

**Comment by sendya** [comment]
@deamwork server {
listen 80;
server name ss.xxx.com;
access log /data/wwwlogs/ss.xxx.com nginx.log combined;
index index.html index.htm index.php;

root /data/wwwroot/ss.xxx.com/Public;

if (!-e $request filename) {
    rewrite (. ) /index.php last;
}

location ~ . \.(php|php5)?$ {
    #fastcgi pass remote php ip:9000;
    fastcgi pass unix:/dev/shm/php-cgi.sock;
    fastcgi index index.php;
    include fastcgi.conf;
    }

location ~ . \.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
    expires 30d;
    access log off;
    }
location ~ . \.(js|css)?$ {
    expires 7d;
    access log off;
    }
}

nginx 你尝试改成我发送的这个内容 restart下nginx

**Comment by deamwork** [comment]
抱歉拖了这么久，笔记本彻底没电了，已经按照您给的配置替换后重启nginx，问题依旧

**Comment by sendya** [comment]
@deamwork 那抱歉，明天再帮你解决吧。我该睡了，明日还要上班

**Comment by deamwork** [comment]
很抱歉这么晚了还在打扰您，要不您先休息吧，debug我明天中午和晚上可以和您一起进行。我这不是很着急的

**Comment by deamwork** [comment]
接下来怎么做

**Comment by sendya** [comment]
@deamwork  有telegram吗。即时聊天软件比较好搞定事情

**Comment by deamwork** [comment]
并没有.....但是有QQ和Tox

**Comment by deamwork** [comment]
https://tools.deamwork.com/notepad/ocre

**Comment by sendya** [comment]
@deamwork 抱歉我不用qq...  现在你的情况是 所有事页面的 能访问，所有事 post请求的不能访问 吗

**Comment by sendya** [comment]
这样是有正常页面的对吗 http://xxx.com/support/tos

**Comment by deamwork** [comment]
我貌似还可以直接访问admin....不需要登录，而且也不显示登录名

**Comment by deamwork** [comment]
tos是正常点的

**Comment by sendya** [comment]
@deamwork 有地址吗。给我。 我上去查下

**Comment by deamwork** [comment]
https://tools.deamwork.com/notepad/ocre

**Comment by sendya** [comment]
@deamwork 麻烦你检查一下 \Library\Controller\Auth.php  文件中第81行开始 是否含有
    /**
     * @JSON
     */

**Comment by deamwork** [comment]
存在

**Comment by sendya** [comment]
整个sspanel目录给777试试

**Comment by sendya** [comment]
感觉是 反射机制 失效了，或者 JSON过滤器没过滤

**Comment by deamwork** [comment]
根目录0777 -R 问题依旧

**Comment by sendya** [comment]
@deamwork 你的PHP有opcache模块吗

**Comment by deamwork** [comment]
with Zend OPcache v7.0.6-dev

**Comment by kookxiang** [comment]
方便发下 php 配置吗？一般是在：

 - /etc/php.ini
 - /etc/php.d/10-opcache.ini （如果有的话

r18 (at) ikk.me

**Comment by deamwork** [comment]
Telegram: @riportam222

**Comment by kookxiang** [comment]
telegram.me/kookxiang 我没办法联系到你

**Comment by deamwork** [comment]
telegram认为我是spam....

**Comment by kookxiang** [comment]
因为你不是国内手机号…… 你还是邮件我吧

**Comment by deamwork** [comment]
邮件已发

**Comment by kookxiang** [comment]
修改 `opcache.save_comments=0` 为 `opcache.save_comments=1` 保存后重启 PHP

**Comment by deamwork** [comment]
问题解决了.....但是目录权限表全是777这样没问题么........

**Comment by sendya** [comment]
@deamwork 你可以把权限去掉 只留读取。但是 ./Data/Template 必须有写入权

**Comment by deamwork** [comment]
除了Data外其他的都设定为0644可以吗？

**Comment by sendya** [comment]
@deamwork 可以

**Comment by deamwork** [comment]
ZendOpcache is configured not saving PHP DocComments which is required.
升级最新commit后全站报错这个....怎么处理

**Comment by sendya** [comment]
@deamwork 你的 `opcache`  没有开启 `opcache.save_comments` 和 `opcache.load_comments ` 检查一下 php的 opcache 配置

**Comment by sendya** [comment]
@deamwork 更新之前没问题 吗？

**Comment by deamwork** [comment]
这个issue的版本是正常的....

**Comment by kookxiang** [comment]
@sendya 我觉得我们需要验证一下这两个配置项的影响

**Comment by sendya** [comment]
@kookxiang 无力啊。我说了用 编译好的版本，非要直接git = =

**Comment by deamwork** [comment]
你更新的那么辛苦，帮你找bug啊~

**Comment by kookxiang** [comment]
我觉得还是需要验证下的，因为到时候肯定会 merge 到主干的

**Comment by deamwork** [comment]
我也这么想的....
我的php.ini设置贴出来：
https://tools.deamwork.com/notepad/olms

**Comment by sendya** [comment]
@kookxiang 我在自己服务器关闭了这两个项目会报错，开启后不会。 这又是一个坑，有的人配置又会出问题

**Comment by deamwork** [comment]
刚刚看了官网的文档
http://files.zend.com/help/Zend-Server-6.3-IBMi/content/zendserverapi/zend_opcache-configuration_directives.htm#dir-opcache.save_comments
貌似没问题啊....

**Comment by congjie** [comment]
遇到相同问题~~  拉的目前git最新版~~  这个问题还没解决么0 0？？

**Comment by sendya** [comment]
@congjie 出的什么错？

**Comment by congjie** [comment]
@sendya 和deamwork一样的错，因为我是oneinstack然后我修改/usr/local/php/etc/php.d/ext-opcache.ini了这个文件就好了。现在在配置节点

**Comment by sendya** [comment]
@congjie 

### 10. lnmp 一键环境
* [安装教程(CentOS7)(需要有动手能力)](https://github.com/sendya/shadowsocks-panel/wiki/CentOS7-LNMP%E7%8E%AF%E5%A2%83,NGINX%E9%85%8D%E7%BD%AE%E9%9D%A2%E6%9D%BFconf)  
* [LinuxEye提供的一键环境oneinstack](https://oneinstack.com/)

(oneinstack安装的环境需要修改 `/usr/local/php/etc/php.d/ext-opcache.ini` 文件，将值 `opcache.save_comments=1` 修改保存，并且重启`php-fpm`)

如果我没记错，安装教程内有说明这个问题
