### ISSUE TITLE
 php index.php install 安装错误

### ISSUE THREAD

**Issue by kania1983** [sendya/shadowsocks-panel#39]
出现错误 环境是php5.6  如下 php index.php install
Now installing dependencies...
PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/shadowsocks-panel/index.php on line 66

Warning: system() has been disabled for security reasons in /home/wwwroot/shadowsocks-panelindex.php on line 66
It seems composer failed to install package

**Comment by sendya** [comment]
@kania1983  目录没有写入权，或者php禁止了system()权限

**Comment by kania1983** [comment]
感谢，这个修改了php.in文件的禁用函数，貌似网站文件的目录修改为Public后，首页的css js 都是404，
如下的这个路由也是做了的呀
if (!-e $request_filename) {
    rewrite (.*) /index.php last;
}

**Comment by sendya** [comment]
@kania1983 git clone 的 还是 1.02的zip包

**Comment by kania1983** [comment]
下载了这个 https://github.com/sendya/shadowsocks-panel/releases/download/sspanel-v1.02/shadowsocks-panel.zip

安装php index.php install 时出现  Operation timed out after 60000 milliseconds with 38820 out of 1610287 bytes received
再次安装出现 Failure when receiving data from the peer

难道用的是国内的主机，污染造成的吗

**Comment by sendya** [comment]
@kania1983 composer的官方站差不多是墙死掉了。 没办法在线直接下载到 composer.phar
在 shadowsocks-panel 目录下使用 `wget http://h.mloli.com/composer.phar` 下载一份，在执行 php index.php install

**Comment by kania1983** [comment]
composer.phar 已经搞定，貌似邀请码无法显示，无法注册管理，invite的status字段是为0 可用的

**Comment by sendya** [comment]
@kania1983 安装程序时，默认的两个邀请码都不能使用吗？
* 334ab1a9fbc19b4c688ca7fd5f8f9ffa
* 0914e68a1527352c5c6ccee132e303eb
这两个

**Comment by kania1983** [comment]
不能显示，也提示邀请码不可用

**Comment by sendya** [comment]
@kania1983 你连接到数据库看看 `invite` 表有没有这两条数据 ，并且 `status = 0`

**Comment by kania1983** [comment]
当然有的，status = 0

**Comment by sendya** [comment]
@kania1983 
`\Library\Controller\Invite.php` 第 **20** 行代码
如下：
```php
$inviteList = InviteModel::GetInviteArray(-1);
```
改成：
```php
$inviteList = InviteModel::getInviteArray(-1);
```

**Comment by kania1983** [comment]
已修改，也清空了缓存模版缓存，问题依旧

**Comment by sendya** [comment]
@kania1983  麻烦发一下地址..我看下。

**Comment by sendya** [comment]
@kania1983 php index.php install 时，是否有过报错。因为是在国内。我相信国内主机 基本上都连不上 composer源。

**Comment by sendya** [comment]
@kania1983 
尝试修改根目录文件 `composer.json`
将内容修改为：
```json
{
  "name": "kookxiang/KK-Framework",
  "description": "A very simple && fast php framework",
  "minimum-stability": "beta",
  "license": "Apache",
  "authors": [
    {
      "name": "kookxiang",
      "email": "r18@ikk.me"
    }
  ],
  "config": {
    "vendor-dir": "Package"
  },
  "autoload": {
    "psr-4": {
      "": "Library/"
    }
  },
  "require": {
    "robmorgan/phinx": "^0.5.3",
    "nette/mail": "*"
  },
   "repositories": {
    "packagist": {
       "type": "composer",
        "url": "http://packagist.phpcomposer.com"
    }
   }
}
```

其 在文件末尾 追加了内容

```json
,
   "repositories": {
    "packagist": {
       "type": "composer",
        "url": "http://packagist.phpcomposer.com"
    }
   }
```

**Comment by sendya** [comment]
@kania1983 问题解决了吗？

**Comment by kania1983** [comment]
感谢，已经跑起来了，结合前一个版本，个人感觉可以把推送通知做成这个样式的，http://demo.cssmoban.com/cssthemes3/mstp_115_enonadmin/mailbox-main.html  有问题会员可以发ticke，并同时触发邮件通知，感觉这样正式一点。其次仪表盘的实时在线应该是登陆会员的实时在线吧，我记得原版的SS有个 t 字段，这个是SS的实时在线。个人感觉开源的这种项目，像收费，充值卡之类的，你应该搞个收费服务。。

**Comment by sendya** [comment]
@kania1983  
* 消息服务以及没了呀。v1.01开始没支持消息服务了。只有系统固定的4条有效果。
* 页面上的实时在线，的确是 SS的实时在线
* 没精力写支付接口，所以就看别人意见弄了这个充值卡，并且计划里 还有API密钥可以直接提取和创建卡密。用于淘宝自动发卡。
* 写这个来赚钱，我觉得要跟之前一样被人喷，也就懒得了。（天朝有那么一部分人实在不敢恭维，所以就不弄收费了，认识的熟人，几乎要什么功能，都可以免费帮写，如果对方乐意给点饮料钱，我也不会矜持拒收的

**Comment by kania1983** [comment]
port, u, d, transfer, enable, swtich 修改对应
port, flow_up, flow_down, transfer, enable

你的是只做这这几个表的适配，原版的https://github.com/mengskysama/shadowsocks/tree/manyuser 有个字段t, last keepalive time 是指SS客户端输入密码正确连接之后最后一次在线的值，我们的这个不管SS客户端上没上线，都显示在线的

**Comment by sendya** [comment]
@kania1983 
看这里 [shadowsocks](https://github.com/sendya/shadowsocks-rm/blob/manyuser/shadowsocks/dbtransfer.py#L75)

```python
        if query_sub_when == '':
            return
        query_sql = query_head + ' SET flow_up = CASE port' + query_sub_when + \
                    ' END, flow_down = CASE port' + query_sub_when2 + \
                    ' END, lastConnTime = ' + str(int(last_time)) + \
                    ' WHERE port IN (%s)' % query_sub_in
        # print query_sql
        conn = cymysql.connect(host=config.MYSQL_HOST, port=config.MYSQL_PORT, user=config.MYSQL_USER,
                               passwd=config.MYSQL_PASS, db=config.MYSQL_DB, charset='utf8')
        cur = conn.cursor()
        cur.execute(query_sql)
        cur.close()
        conn.commit()
        conn.close()
```

`lastConnTime `

**Comment by sendya** [comment]
@kania1983 这样能看懂吧.. 那三个版本的 ss manyuser 的代码。

**Comment by kania1983** [comment]
奇怪了，网站刚跑起来没有登录SS，就显示在线

**Comment by sendya** [comment]
@kania1983 
看这里 [Library/Controller/Auth.php#L121](https://github.com/sendya/shadowsocks-panel/blob/dev/Library/Controller/Auth.php#L121)

新注册账户，会设定一个注册时间为默认值，过`600s`就没了

`$user->lastConnTime = $user->regDateLine;  `

```php
$user->transfer = $transferNew;
            $user->invite = $inviteCode;
            $user->plan = $invite->plan;// 将邀请码的账户类型设定到注册用户上.
            $user->regDateLine = time();
            $user->lastConnTime = $user->regDateLine;  
            $user->sspwd = Utils::randomChar();
            $user->payTime = time(); // 注册时支付时间
            $user_test_day = Option::get('user_test_day')?: 7;
            $user->expireTime = time() + (3600 * 24 * intval($user_test_day)); // 到期时间
            $user->port = Utils::getNewPort(); // 端口号
            $user->setPassword($passwd);
            $user->save();
```

**Comment by kania1983** [comment]
明白，感谢解答，可以关闭了
