### ISSUE TITLE
按照readme 没有安装成功

### ISSUE THREAD

**Issue by vacan** [sendya/shadowsocks-panel#4]
按照readme 没有安装成功，不知道有没有需要注意的地方？

**Comment by sendya** [comment]
@vacan 把你运行后的页面信息发出来看下

**Comment by vacan** [comment]
不好意思，我的浏览器还没能看到任何内容……
if (!-e $request_filename) {
    rewrite (.*) /index.php last;
请问这个加到 nginx的配置文件中吗？

**Comment by sendya** [comment]
@vacan 是的， 例子如下：
server{
  listen 80;
  server_name panel.local.dev;
  #access_log  logs/local.dev.access.log  main;

  index  index.html index.htm index.php;
  root "/home/wwwroot/shadowsocks-panel";

  # router
  if (!-e $request_filename) {
   rewrite (.*) /index.php break;
  }

  location ~ \.php(.*)$  {
      fastcgi_pass   127.0.0.1:9000;
      fastcgi_index  index.php;
      fastcgi_split_path_info  ^((?U).+\.php)(/?.+)$;
      fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
      fastcgi_param  PATH_INFO  $fastcgi_path_info;
      fastcgi_param  PATH_TRANSLATED  $document_root$fastcgi_path_info;
      include        fastcgi_params;
  }

}

**Comment by vacan** [comment]
[error] 19110#0: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: X.X.X.X , server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host:
这是我nginx里的错误日志，是不是我的nginx没有配好？

**Comment by vacan** [comment]
server {
        listen 82 default_server;
        listen [::]:82 default_server ipv6only=on;

        root /usr/share/nginx/html/ss;
        index index.html index.htm index.php;

 # Make site accessible from http://localhost/
        server_name localhost;

if (!-e $request_filename) {
    rewrite (.*) /index.php last;
}
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
        }

        location ~ /\.ht {
                deny all;
        }

}
这是我的配置文件

**Comment by sendya** [comment]
php7 以下的版本请 clone 分支 https://github.com/sendya/shadowsocks-panel/tree/PHP5 支持php5
命令 `git clone -b PHP5 https://github.com/sendya/shadowsocks-panel.git`

你的nginx配置  这个不要
```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
```

**Comment by vacan** [comment]
可以进入主界面，但是登录界面好像加载不完全，而且也不知道用户名和密码。

**Comment by sendya** [comment]
https://github.com/sendya/shadowsocks-panel/wiki/%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E

```
2. 打开网站注册您的账户, 默认注册的第一个账户为 admin 账户,您也可以修改 user_power 表的uid字段修改或添加您的admin权限账户.
```

看说明..  有问题的界面可以截图发上来看下.
