### ISSUE TITLE
请问虚拟主机怎么安装新版

### ISSUE THREAD

**Issue by xiadena** [sendya/shadowsocks-panel#40]
我是小白。VPS到是装好了，虚拟主机能装吗

**Comment by sendya** [comment]
@xiadena 额...可以。
把你vps装好的那一份整个目录打包 传到vps上面 db也要从 vps 上那一份导出 在导入到虚拟主机里。

**Comment by sendya** [comment]
@xiadena 原因：  虚拟主机无法直接执行安装程序 php index.php install ，则无法自动导入 数据库。和 部分 模板资源的 构建

**Comment by xiadena** [comment]
好的，我试试
