### ISSUE TITLE
邮件相关设置问题

### ISSUE THREAD

**Issue by Indexyz** [sendya/shadowsocks-panel#41]
配置文件中的`username`选项
在有些邮件服务商中(例如SendGrid)的SMTP选项中是不一定为邮箱的
> Change your SMTP authentication username and password to your SendGrid username and password

然后就出现了喜闻乐见的错误 `The header 'From' expects to be email, string '***' given.`
(虽然我感觉这个是KK Framework的问题)

**Comment by sendya** [comment]
本身就没打算支持，谢谢。
想用自己写，反正邮件接口在那里。

**Comment by sendya** [comment]
并且 `框架` 本身并没提供邮件支持。

**Comment by Indexyz** [comment]
@sendya 是SMTP的接口

**Comment by Indexyz** [comment]
也就是SMTP服务器的用户名不一定为邮箱

**Comment by sendya** [comment]
@Indexyz username 字段 本身就没限制必须是邮箱地址阿，而且可以正常使用阿，你看清楚你报错是什么，  发送人 报错好吗？人家告诉你username错了吗

**Comment by Indexyz** [comment]
@sendya 刚刚看了一下Mail类的代码在45行 `$this->setFrom($this->config['username']);`
中setFrom应该是`config`里的是`from`而且不是`username`,
nette中要求的是`email or format "John Doe" <doe@example.com>`

**Comment by sendya** [comment]
@Indexyz 哦…是这样阿，

**Comment by sendya** [comment]
@Indexyz 那你就自己改一下嘛…反正我又不用这个，几天前就弃掉这个了

**Comment by Indexyz** [comment]
Orz那好吧
