### ISSUE TITLE
无法安装的一个问题

### ISSUE THREAD

**Issue by Snrat** [sendya/shadowsocks-panel#42]
[PDOException]                                                                         
  SQLSTATE[HY000]: General error: 1364 Field 'regDateLine' doesn't have a default value

**Comment by Snrat** [comment]
检查发现是php.ini问题，已经解决！

**Comment by sendya** [comment]
[fixed-438d261](https://github.com/sendya/shadowsocks-panel/commit/438d261d2838155c410d2ecc8827d5673d39e851)
