### ISSUE TITLE
注册新用户时出现“系统错误! 请求服务器失败，请稍后重试”

### ISSUE THREAD

**Issue by yueker** [sendya/shadowsocks-panel#43]
注册新用户时出现“系统错误! 请求服务器失败，请稍后重试”
然后安装时有这个告警：
root@root:/home/wwwroot/shadowsocks-panel# php index.php install
Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
/home/wwwroot/shadowsocks-panel/Package/bin/phinx: 17: /home/wwwroot/shadowsocks-panel/Package/bin/phinx: /home/wwwroot/shadowsocks-panel/Package/robmorgan/phinx/bin/phinx: Permission denied
All done~ Cheers!

**Comment by sendya** [comment]
@yueker phinx: Permission denied
给这个 `/home/wwwroot/shadowsocks-panel/Package/robmorgan/phinx/bin/phinx` 可执行权限

**Comment by yueker** [comment]
多谢 搞定
