### ISSUE TITLE
对于站库分离的模式，好像有点bug

### ISSUE THREAD

**Issue by 604542720** [sendya/shadowsocks-panel#46]
Now reloading packages and config...PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'MY IP ' (using password: YES)' in /home/wwwroot/shadowsocks-panel/shadowsocks-panel/Library/Core/Database.php:27

这里读取的貌似是本机IP，而不是config里面配置的IP？

**Comment by sendya** [comment]
@604542720 config里设置的什么ip就是什么ip

**Comment by 604542720** [comment]
但是我的config里面配置的 host  是远程主机IP，这个地方读的却是本机IP，导致报了这个错误

**Comment by sendya** [comment]
稍等，查一下

**Comment by 604542720** [comment]
ok,搞定了，远程用户没添加上去，不好意思
