### ISSUE TITLE
整合数据库的时候报了这么个错误

### ISSUE THREAD

**Issue by 604542720** [sendya/shadowsocks-panel#47]
SQLSTATE[HY000]: General error: 1364 Field 'reguid' doesn't have a default value

**Comment by sendya** [comment]
请提供 `MYSQL` 版本号

先使用 
```
git clone https://github.com/sendya/shadowsocks-panel.git
cd /shadowsocks-panel
php index.php install
```

这样安装吧，要先配置 `Config.php` 才执行 `php index.php install`

**Comment by 604542720** [comment]
是按照这个顺序执行的。
 == 20160406131937 MessageTable: migrating
 == 20160406131937 MessageTable: migrated 0.5958s

 == 20160406132651 InviteDefaultDb: migrating

                                                                                
  [PDOException]                                                                
  SQLSTATE[HY000]: General error: 1364 Field 'reguid' doesn't have a default value

**Comment by sendya** [comment]
@604542720 我要 MYSQL 版本，这个报错是 百分之2的几率出现的。

**Comment by 604542720** [comment]
MySQL version 5.6.25

**Comment by kookxiang** [comment]
编辑 `my.ini`，禁用 `STRICT_TRANS_TABLES`

**Comment by 604542720** [comment]
我查了下表的引擎用的是innodb，所以默认启用了STRICT_TRANS_TABLES，my.cnf 的sql_mode sql_mode去掉STRICT_TRANS_TABLES好像没有效果

**Comment by sendya** [comment]
@604542720 重启mysql了没

**Comment by 604542720** [comment]
重启了的

**Comment by 604542720** [comment]
这个 reguid 在创建的时候不能自动给它赋一个默认的值吗

**Comment by kookxiang** [comment]
可以，但是这是治标不治本的方法

**Comment by 604542720** [comment]
ok,搞定了。google大法好。 On Centos 6.5 i had to edit  /usr/my.cnf and set (even though /etc/my.cnf existed and bindings were successfully set there。我刚刚只改了/etc/my.cnf 这个地方。
一个新问题来了，我以为这个前端是可以直接对接以前的manyuser的数据库表，看样子好像是在里面新建了用户表？？

**Comment by sendya** [comment]
@604542720 与原版 manyuser 不兼容，用我安装教程里提供的三种

**Comment by 604542720** [comment]
安装这个前端的时候，原版manyuser里面的表结构没有被修改吧？
那我是不是直接删掉这个前端新增加的表结构就可以了？

**Comment by sendya** [comment]
@604542720 本面板跟旧版本manyuser所有版本都不兼容。
谢谢，若删除本面板增加的的 `member`.则会导致面部无法运行。请直接使用 member  当作 manyuser 的主表

**Comment by 604542720** [comment]
我的意思是这样的。
这个库不用你的这个面板，用orvice的那个。是不是只要删除新增加的表就可以了？
(我有洁癖强迫症，不删除不舒服斯基= =)
还是说删除了这些新表，会影响到原来orvice的面板运行？

还有一个就是，你的 "SS manyuser安装与对接" 教程里面有介绍到支持的“目前支持版本： 原版 manyuser” ，所以这个地方请修改一下

**Comment by sendya** [comment]
随便你删 不影响其他

**Comment by 604542720** [comment]
好的，Thx
