### ISSUE TITLE
安装后打开网页出现如下错误

### ISSUE THREAD

**Issue by egoate** [sendya/shadowsocks-panel#48]
#!env php Sorry, This page is not available due to incorrect server configuration.

**Comment by sendya** [comment]
@egoate 认真看 安装教程

**Comment by egoate** [comment]
是 nginx 配置错了吗

**Comment by sendya** [comment]
@egoate 是  网站目录配错了 root  /xxxxx/shadowsocks-panel/Public 才对

**Comment by egoate** [comment]
已解决 忘记把 fastcgi 路径也改过来了 谢谢！
