### ISSUE TITLE
邮件报错

### ISSUE THREAD

**Issue by kozora** [sendya/shadowsocks-panel#50]
http://ww3.sinaimg.cn/large/891f6d5agw1f3253i92t5j20ha0bdadk.jpg

**Comment by sendya** [comment]
@kozora 我好像没说过支持 mailgun。。
如果是标准 SMTP 可以安装配置里默认的格式写。

（mailgun的支持还没写好。）

**Comment by kozora** [comment]
额..我用QQ企业邮箱也不行。。。

**Comment by sendya** [comment]
@kozora 默认配置里 的就是QQ企业邮箱

**Comment by siminai** [comment]
咦。我配置好了以后邮件的确是发得出去。但是请求重置密码的时候提示请求服务器失败。可能邮件系统配置出错无法发送邮件！.只能按重试.但是code已经发去邮箱里了.

**Comment by siminai** [comment]
XHR failed loading: POST "http://domain.xx/auth/forgePwd.json".

**Comment by helaobibi** [comment]
一样，我也是这样，我还没有试，不过1.02正常，看代码新版本好像加了一个timeout 4000

**Comment by sendya** [comment]
@helaobibi 发不出去？

**Comment by helaobibi** [comment]
OK了，因为是国外的主机，用国内的smtp速度太慢了，4000timeout超过了，我用qq企业国外的节点hwsmtp.exmail.qq.com解决了

**Comment by sendya** [comment]
@helaobibi 收发邮件超过4秒 体验度太差了。不然我限制超时干嘛

**Comment by helaobibi** [comment]
是的，老版本发邮件确是太慢了

**Comment by helaobibi** [comment]
@sendya 目前搭起来没什么太大问题，感谢

**Comment by kozora** [comment]
我的配置没错啊，还是报同样的错
$MAIL = array(
    'host' => 'hwsmtp.exmail.qq.com',
    'username' => 'admin@xxxx',
    'password' => 'xxxxxxx',
    'from'     => 'xx <admin@xxxxx>',
    'secure' => 'ssl'
);

**Comment by helaobibi** [comment]
@kozora 你用的1.03吗？我1.03一点问题都没有

**Comment by kozora** [comment]
@helaobibi 是最新版啊 :(

**Comment by helaobibi** [comment]
那就不知道了

**Comment by sendya** [comment]
@kozora 那就别开SSL阿

**Comment by helaobibi** [comment]
@sendya 大神，到期时间是什么意思啊？是不是到了那个时间流畅就重置了？

**Comment by sendya** [comment]
@helaobibi 到期了就连不上所有ss节点了。。

**Comment by helaobibi** [comment]
@sendya 也就是说注册只有7天有效期啊？

**Comment by sendya** [comment]
@helaobibi 你自己改一下账户到期时间啊

**Comment by helaobibi** [comment]
@sendya 那套餐B  D  C有没有到期时间啊？

**Comment by sendya** [comment]
@helaobibi 废话肯定有啊。
商业功能， 不用可以去关掉 计划任务的 自动停止超流量用户+账户到期自动停用账户功能。

**Comment by helaobibi** [comment]
@sendya 哈哈，还是保留吧，也挺好，谢谢
