### ISSUE TITLE
希望能更新一下您fork的Shadowsocks-manyuser后端

### ISSUE THREAD

**Issue by Acris** [sendya/shadowsocks-panel#52]
您好，
从Wiki上看到shadowsocks-panel与后端对接的时候，后端是用的你fork的并且已经修改好数据表字段名的repo，但是距离原repo的更新有一段时间了，比如shadowsocks-rm manyuser，原作者已经添加了OTA等等很多特性，希望您能更新一下你这边的fork，谢谢。 :- )
![QQ截图20160420165136.png](https://ooo.0o0.ooo/2016/04/20/57174420148b7.png)

**Comment by sendya** [comment]
有空再更新

**Comment by Acris** [comment]
我这边尝试着改了一份：https://github.com/Acris/shadowsocks-rm/tree/manyuser

**Comment by sendya** [comment]
@Acris ok，我可以把这个链接 直接更新到 README.md 上吗？

**Comment by Acris** [comment]
@sendya 嗯，可以，我也会及时同步原作者代码的。感谢。

**Comment by sendya** [comment]
@Acris 已链接。在 [ss manyuser 安装与对接](https://github.com/sendya/shadowsocks-panel/wiki/ss-manyuser-%E5%AE%89%E8%A3%85%E4%B8%8E%E5%AF%B9%E6%8E%A5)
