### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by TChenQuan** [sendya/shadowsocks-panel#55]
任务	说明	下次运行时间	状态	优先级
#clearInviteOld		2016-04-15 21:09:44	停用	             110
#clearTransfer		2016-05-01 00:00:00	尚未运行 	     10
#daily	        	2016-04-15 21:09:44	停用	             100
#mail		        2016-04-15 21:09:44	停用	              80
#stopExpireUser	2016-04-23 13:26:01	等待运行	      30

停用怎么解？

**Comment by sendya** [comment]
@TChenQuan 你要干嘛？

**Comment by TChenQuan** [comment]
群发邮件啊停用0.0

**Comment by sendya** [comment]
@TChenQuan 没这个功能啊

**Comment by TChenQuan** [comment]
账号停用怎么批量启用

**Comment by TChenQuan** [comment]
那在消息管理的邮件是什么？

**Comment by sendya** [comment]
@TChenQuan 我并没没说现在是完成版。而且 releases 才发布到1.03吧。其他功能都还在测试或者在写呢。

**Comment by TChenQuan** [comment]
好吧

**Comment by TChenQuan** [comment]
最后一个问题

**Comment by TChenQuan** [comment]
用户到期怎么批量启用

**Comment by sendya** [comment]
@TChenQuan 没有这个功能

**Comment by sendya** [comment]
@TChenQuan 要么就自己去数据库改下

**Comment by TChenQuan** [comment]
邀请码的延期试用卡是什意思  可以延期到期时间

**Comment by TChenQuan** [comment]
吗？

**Comment by sendya** [comment]
@TChenQuan 试用延期卡 谢谢。   把试用时间延期的。

**Comment by TChenQuan** [comment]
http://7xtalp.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160423133459.png  
卡号有点异常不是么？

**Comment by sendya** [comment]
@TChenQuan 怎么异常了。刷新啊

**Comment by TChenQuan** [comment]
可以添加一个可以重复使用的延期卡吗？

**Comment by sendya** [comment]
@TChenQuan 试试呗

**Comment by TChenQuan** [comment]
怎么试...在数据库重复添加相同卡号的  延期卡？

**Comment by sendya** [comment]
@TChenQuan 哦你要添加一张能重复激活的卡号啊？  没这个功能 不用想了

**Comment by TChenQuan** [comment]
500多个用户手动启用账号？

**Comment by TChenQuan** [comment]
批量生成了卡号   批量导出怎么做？

**Comment by sendya** [comment]
@TChenQuan `update member set enable=0 where 1=1 `

**Comment by TChenQuan** [comment]
数据库执行？

**Comment by Acris** [comment]
@TChenQuan 是。

**Comment by TChenQuan** [comment]
已解决
