### ISSUE TITLE
404

### ISSUE THREAD

**Issue by andy520** [sendya/shadowsocks-panel#56]
panel安装完成后提示404Nginx网页路径为Public，nginx-t也提示successful，但是打开网页提示404（Public下有index.php）

**Comment by Acris** [comment]
检查下你的Nginx配置

**Comment by usami-mizugi** [comment]
nette/utils suggests installing ext-intl (for script transliteration in Strings::webalize() and toAscii())
nette/mail suggests installing ext-fileinfo (to detect type of attached files)
symfony/console suggests installing psr/log (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
/home/wwwroot/kano/Package/bin/phinx: 17: /home/wwwroot/kano/Package/bin/phinx: /home/wwwroot/kano/Package/robmorgan/phinx/bin/phinx: Permission denied
Now check resources is exits...
Resources is not existed, gulping...
All done~ Cheers!
--------------------------------------------------------------------------------------------------------------
执行pip index.php install 有Permission denied问题出现，请解决办法是？
