### ISSUE TITLE
System Error - 42

### ISSUE THREAD

**Issue by carlwg** [sendya/shadowsocks-panel#57]
System Error - 42

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ss.message' doesn't exist

安装后进入 login 页面报此错误 php 已开启 system() 函数

**Comment by carlwg** [comment]
已解决，Package 目录未取得权限。

**Comment by ml1720770** [comment]
我也遇到相同问题，给Package 777权限未能解决此问题。

**Comment by sendya** [comment]
@ml1720770 权限给了要运行一次安装

**Comment by ml1720770** [comment]
@sendya 运行了安装，观察发现未写入数据库，且检查写入权限正常，安装中也没有对该问题报错

**Comment by Mkdms** [comment]
@ml1720770 你确定给对权限了吗？

**Comment by ml1720770** [comment]
@Mkdms 确定给对了，现在排查可能是php版本过低，待验证

**Comment by ml1720770** [comment]
安装日志如下：
[root@VM_140_184_centos web]# php index.php install
Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing nette/utils (v2.3.8)
    Loading from cache

  - Installing nette/mail (v2.3.4)
    Loading from cache

  - Installing symfony/yaml (v3.0.4)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.1.1)
    Loading from cache

  - Installing symfony/console (v3.0.4)
    Loading from cache

  - Installing symfony/filesystem (v3.0.4)
    Loading from cache

  - Installing symfony/config (v3.0.4)
    Loading from cache

  - Installing robmorgan/phinx (v0.5.3)
    Loading from cache

nette/utils suggests installing ext-gd (to use Image)
nette/utils suggests installing ext-intl (for script transliteration in Strings::webalize() and toAscii())
nette/utils suggests installing ext-mbstring (to use Strings::lower() etc...)
symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
symfony/console suggests installing psr/log (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
Generating autoload files
Now reloading packages and config...You have mail in /var/spool/mail/root
[root@VM_140_184_centos web]# php index.php install
Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Now reloading packages and config...

**Comment by sendya** [comment]
@ml1720770 呵呵，这php也能用?

**Comment by sendya** [comment]
@ml1720770 缺这却那的。

**Comment by ml1720770** [comment]
@sendya 那么运行这个需要哪些模块，我是LAMP on Ubuntu 14.04

**Comment by Acris** [comment]
@ml1720770 如果你是php5，则执行：apt-get install php5-gd php5-intl php5-mbstring
