### ISSUE TITLE
pip index.php install Permission denied

### ISSUE THREAD

**Issue by usami-mizugi** [sendya/shadowsocks-panel#58]
nette/utils suggests installing ext-intl (for script transliteration in Strings::webalize() and toAscii())
nette/mail suggests installing ext-fileinfo (to detect type of attached files)
symfony/console suggests installing psr/log (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
/home/wwwroot/kano/Package/bin/phinx: 17: /home/wwwroot/kano/Package/bin/phinx: /home/wwwroot/kano/Package/robmorgan/phinx/bin/phinx: Permission denied
Now check resources is exits...
Resources is not existed, gulping...

All done~ Cheers!
----------------------------------------------------------------------------------------------------------------------------------------------
执行pip index.php install 有Permission denied问题出现，请解决办法是？

**Comment by sendya** [comment]
@usami-mizugi 没权限就给权限。哪个文件提示没权限给他

**Comment by usami-mizugi** [comment]
问题解决.THX
