### ISSUE TITLE
如何强制https访问

### ISSUE THREAD

**Issue by ml1720770** [sendya/shadowsocks-panel#59]
通用的rewrite和javascript重定向均无法使用。

**Comment by sendya** [comment]
@ml1720770 开https跟本程序无关的吧？

**Comment by ml1720770** [comment]
@sendya 因为这个rewrite太奇妙了，修改亦无从下手。

**Comment by sendya** [comment]
@ml1720770 该开https就开https ，哪里奇怪了。

**Comment by sendya** [comment]
@ml1720770 在说了 开https和 http跳转到https跟   程序的rewrite一点关系都没

**Comment by sendya** [comment]
@ml1720770 给你一个例子

```nginx
server {
	listen 443 http2 ssl;
	server_name sscat.it www.sscat.it;
	access_log /home/wwwlogs/sscat_nginx.log combined;
	index index.html index.htm index.php;
	root /home/wwwroot/shadowsocks-panel/Public;
	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
	
	ssl on;
	ssl_certificate /home/ssl/sscat.pem;
	ssl_certificate_key /home/ssl/sscat_key.pem;
	ssl_session_timeout 5m;

	if (!-e $request_filename) {
		rewrite (.*) /index.php last;
	}
	location ~ .*\.(php|php5)?$ {
		fastcgi_pass  127.0.0.1:9000;
		fastcgi_index index.php;
		include fastcgi.conf;
		}
	location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
		expires 30d;
		}
	location ~ .*\.(js|css)?$ {
		expires 7d;
		}
}
server {
	listen 80;
	server_name sscat.it www.sscat.it;
	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
	return 301 https://sscat.it$request_uri;
}
```

**Comment by sendya** [comment]
对了，要不要告诉你世界上最出名的博客系统`wordpress`也是一样的rewrite写法？

**Comment by ml1720770** [comment]
我尝试过以下的方法：
1、在rewrite规则前/后加入：`rewrite ^(.*)$  https://$host$1 permanent;  `
结果：循环跳转。
2、在Public\index.php加入：`<script type="text/javascript">
var url = window.location.href;
                if (url.indexOf("https") < 0) {
                    url = url.replace("http:", "https:");
                    window.location.replace(url);
                }
</script>`
结果：仅首页可以打开，其他页面被重定向到https的index.php，且404。
3、将http根目录指向另一个文件夹（只有index.php），然后写入以上代码。
结果：同上
4、最终还是找到了解决方案，删除所有80端口的配置文件，仅保留以下内容：
`server {
    listen 80;
    server_name domainname
    rewrite ^ https://$server_name$request_uri permanent;
}`

**Comment by sendya** [comment]
@ml1720770 居然没懂我的意思... 100多个用户，只有你的脑洞比较大，出了问题。  开https正常的方式开就行了。哪来那么多脑洞

**Comment by sendya** [comment]
解决了就好了。 没问题的话就关issue了。
