### ISSUE TITLE
流量显示问题以及用户禁用

### ISSUE THREAD

**Issue by Dk2048** [sendya/shadowsocks-panel#62]
流量为负的时候显示为byte单位
![1](https://ooo.0o0.ooo/2016/04/26/571f0929117f5.png)

为plan Z的用户增加一个cron，充值流量后，余量为正，自动启用
其他套餐类用户不受影响

**Comment by sendya** [comment]
@Dk2048 

> 充值流量后，余量为正，自动启用
这句话的意思??

这样理解吗?
> 充值流量以后 余量大于0就启用  小于0不启用的意思??? for @Acris

**Comment by Dk2048** [comment]
对，不排除增加流量后依旧为负的情况

但是这个方法和后台的启用停用冲突了，如果要解决自动启用的话可能还要再添加一个字段

**Comment by sendya** [comment]
@Dk2048 那就不通过计划任务启用了，因为一旦使用 套餐卡/试用卡/流量卡，去增加时间/流量。 则会触发一次检查是否启用账户

**Comment by sendya** [comment]
@Dk2048 于是遗留下来了一个问题。。 如果签到了100MB 流量变成没超过了。 却不会启用了 。2333

**Comment by Dk2048** [comment]
签到来说的话是增加流量吧，怎么会造成 可用流量 < 已用流量呢

还有就是注册用户默认流量，流量卡只能是整数，这个其实不解决也没问题

我这里后台删除用户也有点问题

    Non_static meethod Core\Model::delete()
    should not be called statically

个人资料那删倒是没问题

消息管理里面的 4 首页浮动提示 这个没法禁用，过一段时间又开了

**Comment by sendya** [comment]
@Dk2048 消息禁用那个 ，修正了。
