### ISSUE TITLE
php index.php install安装错误

### ISSUE THREAD

**Issue by tuutoo** [sendya/shadowsocks-panel#64]
system()错误和phpinx权限问题都弄好了后，安装还是报错了，错误是分隔线下面的，请问是什么原因呢？
安装用的是方式一
# 方式一：克隆最新版本
cd /home/wwwroot/
git clone https://github.com/sendya/shadowsocks-panel.git
cd shadowsocks-panel
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
[root@DOSGP2 superss01.ddns.us]# php index.php install
Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
Phinx by Rob Morgan - https://phinx.org. version 0.5.3

using config file ./phinx.php
PHP Fatal error:  Call to a member function query() on null in /home/wwwroot/superss01.ddns.us/phinx.php on line 21

Fatal error: Call to a member function query() on null in /home/wwwroot/superss01.ddns.us/phinx.php on line 21
Now check resources is exits...
All done~ Cheers!

**Comment by Acris** [comment]
麻烦告知一下php和MySQL版本。

**Comment by tuutoo** [comment]
问题找到了，是我偷懒，Config.php却Copy的之前版本的。没有拷贝当前的Config.simple，并在此基础上修改。
谢谢！
