### ISSUE TITLE
无效登录! 请求服务器失败，请稍后重试

### ISSUE THREAD

**Issue by tuutoo** [sendya/shadowsocks-panel#65]
网页能够打开，点击登陆后可以跳转到http://网站/auth/login，不过点击登陆的时候出了这个错误：
**无效登录! 请求服务器失败，请稍后重试**
请问可能是什么原因呢？
之前的版本是可以正常登陆的，目录有备份不过不会看版本号。

**Comment by sendya** [comment]
@tuutoo 你访问 http://xxxxx/auth/login.json 看有什么内容

**Comment by tuutoo** [comment]
{"code":200,"data":{"globalMessage":[]}}

**Comment by sendya** [comment]
@tuutoo 数据库不完整。执行 php index.php install  建议先备份数据库

**Comment by tuutoo** [comment]
好了 应该是新旧数据库不一致造成的。 重建数据库，再install就好了。
谢谢

**Comment by sendya** [comment]
@tuutoo 从多旧的版本升级上来的？

**Comment by tuutoo** [comment]
@sendya 旧的目录还在，能从目录的文件里看到版本吗？

**Comment by sendya** [comment]
@tuutoo /shadowsocks-panel/Library/Helper/Updater.php 这个文件里

**Comment by tuutoo** [comment]
<?php
/**
 * shadowsocks-panel
 * Add: 2016/4/6 16:02
 * Author: Sendya <18x@loacg.com>
 */

        $online_version = "v0.41"; // 从 update.loacg.com 服务器上获取版本变化

**Comment by sendya** [comment]
@tuutoo https://github.com/sendya/shadowsocks-panel/wiki/v0.2-v.03-v.04x-%E8%BF%81%E7%A7%BB-v1.02-%E6%95%99%E7%A8%8B
以后有问题先看WIKI。  WIKI上没有在问吧

**Comment by tuutoo** [comment]
@sendya 了解了 谢谢！
