### ISSUE TITLE
打开网页显示错误

### ISSUE THREAD

**Issue by fl20002** [sendya/shadowsocks-panel#66]
#!env php Sorry, This page is not available due to incorrect server configuration.

什么原因？

**Comment by sendya** [comment]
@fl20002 看WIKI

**Comment by fl20002** [comment]
完全按照WIKI要求做的   system删了   权限给了   安装也没报错 都是DONE

public也加了    伪静态也写了  

还有哪有问题？

**Comment by fl20002** [comment]
还有  phpmyadmin  打开   数据库前面有个小红×   有问题吗

**Comment by Acris** [comment]
@fl20002 Apache还是NGINX，贴一下服务器配置文件。

**Comment by fl20002** [comment]
Downloading composer...Done!
Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing guzzlehttp/promises (1.1.0)
    Downloading: 100%

  - Installing psr/http-message (1.0)
    Downloading: 100%

  - Installing php-http/promise (v1.0.0)
    Downloading: 100%

  - Installing php-http/httplug (v1.0.0)
    Downloading: 100%

  - Installing php-http/discovery (v0.8.0)
    Downloading: 100%

  - Installing guzzlehttp/psr7 (1.3.0)
    Downloading: 100%

  - Installing mailgun/mailgun-php (v2.0)
    Downloading: 100%

  - Installing guzzlehttp/guzzle (6.2.0)
    Downloading: 100%

  - Installing php-http/guzzle6-adapter (v1.0.0)
    Downloading: 100%

  - Installing symfony/yaml (v3.0.4)
    Downloading: 100%

  - Installing symfony/polyfill-mbstring (v1.1.1)
    Downloading: 100%

  - Installing symfony/console (v3.0.4)
    Downloading: 100%

  - Installing symfony/filesystem (v3.0.4)
    Downloading: 100%

  - Installing symfony/config (v3.0.4)
    Downloading: 100%

  - Installing robmorgan/phinx (v0.5.3)
    Downloading: 100%

php-http/discovery suggests installing php-http/message (Allow to use Guzzle or Diactoros factories)
php-http/discovery suggests installing puli/composer-plugin (Sets up Puli which is required for Discovery to work. Check http://docs.php-http.org/en/latest/discovery.html for more details.)
symfony/console suggests installing psr/log (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
/home/wwwroot/www.ssyiqiwan.top/Package/bin/phinx: 17: /home/wwwroot/www.ssyiqiwan.top/Package/bin/phinx: /home/wwwroot/www.ssyiqiwan.top/Package/robmorgan/phinx/bin/phinx: Permission denied
Now check resources is exits...
Resources is not existed, copying...
All done~ Cheers!


这样的提示  是不是  安装成功了 ？

**Comment by Acris** [comment]
@fl20002 没有权限执行phinx，先给他赋权限再安装。

**Comment by fl20002** [comment]
chmod -R 777 ./Package
php index.php install
Now installing dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
Phinx by Rob Morgan - https://phinx.org. version 0.5.3

using config file ./phinx.php
using config parser php
using migration path /home/wwwroot/www.ssyiqiwan.top/Migrations
warning no environment specified, defaulting to: current
using database ssyiqiwan

 == 20160406101626 CreateTable: migrating
 == 20160406101626 CreateTable: migrated 0.0195s

 == 20160406101714 TableDefaultDb: migrating
 == 20160406101714 TableDefaultDb: migrated 0.0301s

 == 20160417083525 UpdateVersion: migrating
 == 20160417083525 UpdateVersion: migrated 0.0025s

 == 20160428010744 TableUpdate: migrating
 == 20160428010744 TableUpdate: migrated 0.0079s

All Done. Took 0.0951s
Now check resources is exits...
All done~ Cheers!

**Comment by Acris** [comment]
@fl20002 应该没问题了

**Comment by fl20002** [comment]
#!env php Sorry, This page is not available due to incorrect server configuration.
![1](https://cloud.githubusercontent.com/assets/18693963/14875133/e6c7f5c8-0d39-11e6-9acb-a9c14cfa01e9.png)

/**
 * Database Connection:
 */
Core\Database::initialize('mysql:dbname=ssyiqiwan;host=localhost;port=3306;charset=UTF8', 'root', 'XXXXXX');

其他地方没动 



 root  /home/wwwroot/www.ssyiqiwan.top/Public;
if (!-e $request_filename) {
        rewrite (.*) /index.php last;
        }

**Comment by sendya** [comment]
@fl20002 Public 下的 index.php 内容发出来看下。

报这个错
`#!env php Sorry, This page is not available due to incorrect server configuration.`
代表执行的文件是 根目录的安装程序 `index.php` 并不是 程序路由`index.php`

**Comment by fl20002** [comment]
<?php
/**
 * KK-Framework
 * Author: kookxiang <r18@ikk.me>
 */

// Initialize constants
define('ROOT_PATH', dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR);
define('LIBRARY_PATH', ROOT_PATH . 'Library/');
define('DATA_PATH', ROOT_PATH . 'Data/');
define('TIMESTAMP', time());
@ini_set('display_errors', 'on');
@ini_set('expose_php', false);

// Register composer
require ROOT_PATH . 'Package/autoload.php';

// Register error handler
Core\Error::registerHandler();

// Initialize config
@include DATA_PATH . 'Config.php';

if (ini_get('opcache.enable')) {
    if (!ini_get('opcache.save_comments')) {
        throw new \Core\Error('ZendOpcache is configured not saving PHP DocComments which is required.');
    }
}

// Handler for user power
Core\Filter::register(new Helper\LoginFilter());

// Handler for json request
Core\Filter::register(new Helper\JSON());

$defaultRouter = new Core\Router();
$defaultRouter->handleRequest();

**Comment by sendya** [comment]
nginx 配置发出来

**Comment by fl20002** [comment]
server
    {
        listen 80;
        #listen [::]:80;
        server_name www.ssyiqiwan.top ssyiqiwan.top;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/www.ssyiqiwan.top/Public;

        if (!-e $request_filename) {
        rewrite (.*) /index.php last;
        }

        include other.conf;
        #error_page   404   /404.html;
        include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /home/wwwlogs/www.ssyiqiwan.top.log;
    }

**Comment by sendya** [comment]
enable-php.conf; 发出来

**Comment by fl20002** [comment]
location ~ [^/]\.php(/|$)
        {
            try_files $uri =404;
            fastcgi_pass  unix:/tmp/php-cgi.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
        }

**Comment by sendya** [comment]
重启 nginx 了没

**Comment by fl20002** [comment]
卧槽   我傻逼

**Comment by fl20002** [comment]
这步忘记了

**Comment by Acris** [comment]
@fl20002

**Comment by fl20002** [comment]
话说 数据库那里 红X 没关系吗

**Comment by sendya** [comment]
@fl20002 不知道，面板只负责面板该做的事，至于数据库是什么原因，我也不清楚情况

**Comment by fl20002** [comment]
那个  前面那个Package 的权限问题    是不是安装里面改下  

开始是没有这个目录   我等于是先要执行一遍php index.php install

然后有了目录 再给目录权限   然后再执行一遍php index.php install

**Comment by sendya** [comment]
@fl20002 你数据库是空的话

**Comment by fl20002** [comment]
谢谢你们    你们的回复 真心快啊
