### ISSUE TITLE
站点运行了一段时间报错

### ISSUE THREAD

**Issue by hpfs0** [sendya/shadowsocks-panel#67]
今天打开站点，突然报以下的错误，从报错信息看貌似是disk空间不足，但是我查询了一下，我的disk还有7G+，所以基本排除此原因。先求助，这是什么错误。还怎样修复？
System Error - 2

session_start(): open(/tmp/sess_8sfpfbq7c5cobiauf267egm2r7, O_RDWR) failed: No space left on device (28)

**Comment by sendya** [comment]
@hpfs0 SESSION 没读写权，自己想办法

**Comment by hpfs0** [comment]
谢谢提示，我顺藤摸瓜找找答案吧

**Comment by hpfs0** [comment]
@sendya 刚刚将php.ini回收session的参数修改后，重启php就好了。
