### ISSUE TITLE
有没有 sspanel 转移这个版本的办法

### ISSUE THREAD

**Issue by saladinxp** [sendya/shadowsocks-panel#69]
例如数据库迁移啥的。

**Comment by sendya** [comment]
暂无解决办法。

**Comment by saladinxp** [comment]
@sendya 回复的真快

**Comment by sendya** [comment]
@saladinxp 毕竟不用开github自动推送的

**Comment by sendya** [comment]
@saladinxp 可以把sspanel的 user 表结构贴出来，我看看在安装脚本里写一个一键转换数据库

**Comment by Dk2048** [comment]
ss-panel v2.4.5

    CREATE TABLE IF NOT EXISTS `user` (
    `uid` int(11) NOT NULL,
    `user_name` varchar(128) CHARACTER SET utf8mb4 NOT NULL,
    `email` varchar(32) NOT NULL,
    `pass` varchar(32) NOT NULL,
    `passwd` varchar(16) NOT NULL,
    `t` int(11) NOT NULL DEFAULT '0',
    `u` bigint(20) NOT NULL,
    `d` bigint(20) NOT NULL,
    `plan` varchar(2) CHARACTER SET utf8mb4 NOT NULL,
    `transfer_enable` bigint(20) NOT NULL,
    `port` int(11) NOT NULL,
    `switch` tinyint(4) NOT NULL DEFAULT '1',
    `enable` tinyint(4) NOT NULL DEFAULT '1',
    `type` tinyint(4) NOT NULL DEFAULT '1',
    `last_get_gift_time` int(11) NOT NULL DEFAULT '0',
    `last_check_in_time` int(11) NOT NULL DEFAULT '0',
    `sign_day` int(11) NOT NULL DEFAULT '1',
    `last_rest_pass_time` int(11) NOT NULL DEFAULT '0',
    `reg_date` datetime NOT NULL,
    `invite_num` int(8) NOT NULL,
    `money` decimal(12,2) NOT NULL,
    `ref_by` int(11) NOT NULL DEFAULT '0'
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

后续版本不知道什么结构
