### ISSUE TITLE
邀请码

### ISSUE THREAD

**Issue by sendya** [sendya/shadowsocks-panel#7]
### 管理端 功能

1. 邀请码生成
2. ~~邀请码查看列表~~
3. 邀请码编辑("因邀请码能影响账户注册时的账户面板等级")

**Comment by dreammes** [comment]
管理员后台点击添加邀请码http://XXXX/admin/invite 
 提示
System Error - 404
The request URL is not exists
We're now fixing this problem, sorry for the inconveniences.
BackTrace:<br>index.php:27 (Core/DefaultRouter->handleRequest)
Library/Core/DefaultRouter.php:22 (Core/Error->__construct)

**Comment by sendya** [comment]
抱歉哈，这是未完成功能。所以不属于bug提交。（这个功能应该会在这周末完成，这周六日应该会有较大的项目进度， ~~不过还是要看这周公司是否加班~~
在 issue内的项目问题 没有划删除线或者标注完成的，都是尚未完成功能，无需提交iss。

**Comment by zm3201904** [comment]
启动时、ServerPool' object has no attribute 'server_run_status' 报这个错误，是我 哪里没有配置正确么。
十分喜欢首页，谢谢。

**Comment by sendya** [comment]
启动什么

**Comment by zm3201904** [comment]
python server.py 的时候

**Comment by sendya** [comment]
python-m2crypto 这些库装了么

**Comment by ajun59420** [comment]
后台很多错误啊，什么时候出完整版

**Comment by sendya** [comment]
已修复完成。
