### ISSUE TITLE
刚更新后发现forgePwd收到邮件是空白

### ISSUE THREAD

**Issue by helaobibi** [sendya/shadowsocks-panel#70]
测试邮件正常

**Comment by sendya** [comment]
@helaobibi 数据库中 `options` 表，是否有 k  `custom_mail_forgePassword_content` 或者 `custom_mail_forgePassword_content_2`

**Comment by helaobibi** [comment]
没有，是不是要install一下？

**Comment by sendya** [comment]
@helaobibi 任何情况下升级都需要 install ，`install `完全不会影响旧数据。可放心食用

**Comment by helaobibi** [comment]
ok谢谢

**Comment by helaobibi** [comment]
正常了，但是收邮件速度比以前慢了好多

**Comment by sendya** [comment]
@helaobibi 因为标准的邮件发送改为 邮件列队 发送了。 这个问题我在与参与开发的讨论之后再次做出调整吧。  （现在邮件大约是1分钟延迟，因为这是计划任务的执行时间。）

**Comment by helaobibi** [comment]
好ok
