### ISSUE TITLE
 php index.php install 遇到问题  这是咋回事呢

### ISSUE THREAD

**Issue by saladinxp** [sendya/shadowsocks-panel#71]
PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/shadowsocks-panel/index.php on line 95

Warning: system() has been disabled for security reasons in /home/wwwroot/shadowsocks-panel/index.php on line 95
It seems composer failed to install package

**Comment by Acris** [comment]
https://github.com/sendya/shadowsocks-panel/wiki/Shadowsocks-Panel-%E9%9D%A2%E6%9D%BF%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B
看Wiki

**Comment by sendya** [comment]
@saladinxp 看 WIKI。写的非常清楚，而且是加粗字

**Comment by saladinxp** [comment]
@sendya @Acris 好， 你2回复真快

**Comment by saladinxp** [comment]
另外我是菜鸟 只会 依葫芦画瓢
请允许php函数 system   这个应该哪里设置呢谢谢

**Comment by Acris** [comment]
@saladinxp php.ini disabled_function

**Comment by saladinxp** [comment]
@Acris ok thanks
这个问题解决了，我去解决下个问题了
