### ISSUE TITLE
安装后php提示出错Failed opening required

### ISSUE THREAD

**Issue by Love4Taylor** [sendya/shadowsocks-panel#72]
完全按照wiki搞得，安装后显示如下
Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/shadowsocks-panel/Package/autoload.php) is not within the allowed path(s): (/home/wwwroot/shadowsocks-panel/Public:/tmp/:/proc/) in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

Warning: require(/home/wwwroot/shadowsocks-panel/Package/autoload.php): failed to open stream: Operation not permitted in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

Fatal error: require(): Failed opening required '/home/wwwroot/shadowsocks-panel/Package/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

**Comment by sendya** [comment]
@Love4Taylor composer依赖没装成功，再次执行安装。  如果是国内主机，换composer源 ，如果是 composer.phar 都下载失败了，自己上传 composer.phar 或者 `wget http://h.mloli.com/composer.phar`

**Comment by Love4Taylor** [comment]
然而是linode，不管是改源还是手动下phar都一样的说

[root@li539-82 shadowsocks-panel]# php index.php install
Now installing dependencies...
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
Now reloading packages and config...Done!
Now migrating database...
Phinx by Rob Morgan - https://phinx.org. version 0.5.3

using config file ./phinx.php
using config parser php
using migration path /home/wwwroot/shadowsocks-panel/Migrations
warning no environment specified, defaulting to: current
using database shadowsocks

All Done. Took 0.0173s
Now installing resources...
Deleting old resources...
done.
Copying resources...
All done~ Cheers!

**Comment by sendya** [comment]
@Love4Taylor  根目录 /Package/ 有没有文件？

**Comment by Love4Taylor** [comment]
有啊
[root@li539-82 ~]# ls /home/wwwroot/shadowsocks-panel//Package/
autoload.php  bin  composer  guzzlehttp  mailgun  php-http  psr  robmorgan  symfony

**Comment by Acris** [comment]
@Love4Taylor

**Comment by Love4Taylor** [comment]
centos7,不过感觉关系似乎不是很大？之前idcf同样centos7就正常

**Comment by Acris** [comment]
@Love4Taylor 看看是不是SELinux权限问题，执行下面命令试试。
 sudo setsebool httpd_read_user_content=1

**Comment by Love4Taylor** [comment]
噗 SELinux就没开
setsebool:  SELinux is disabled.

**Comment by sendya** [comment]
那就换台，或者换个系统，或者换个lnmp环境， 或者算了别装了。

**Comment by sendya** [comment]
还有一个可能。
PHP的配置开启了 严格目录检查

root 路径在 `shadowsocks-panel/Public`
引入文件在 根目录 所以无权限读取。

**Comment by sendya** [comment]
php.ini 配置文件中

```
;open_basedir =
```
将 `open_basedir` 配置屏蔽，重启php

**Comment by Love4Taylor** [comment]
有毒
php.ini里open_basedir这个参数本来就是被注释掉的并没有配置

**Comment by sendya** [comment]
@Love4Taylor 换lnmp ，装我这个
https://sendya.me/archives/centos7-nginx-php-mariadb-mysql-install.html

**Comment by Love4Taylor** [comment]
更换lnmp后已正常，lnmp.org里的真的是有毒
