### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by fl20002** [sendya/shadowsocks-panel#73]
一个普通用户  可以使用节点A   然后我把节点A 改成高级节点 

面板上面  是无权使用   但是 实际上 节点还是一直可以连接使用

**Comment by Acris** [comment]
@fl20002 所以你第一次添加的时候就设置为Pro节点 不要让普通用户看见了

**Comment by sendya** [comment]
@fl20002 废话。服务端并没控制啊。  （想控制吗？ 自定义服务端程序谢谢。本程序并不无偿提供） 建议自己改服务端

**Comment by fl20002** [comment]
卧槽 你们2个是不是守着屏幕前面等消息？

**Comment by Acris** [comment]
@fl20002 ==

**Comment by fl20002** [comment]
话说  仪表盘 下面   112,34$   这个有什么特殊的含义吗

**Comment by Acris** [comment]
@fl20002 暂时无用

**Comment by sendya** [comment]
@fl20002 有人发issue   会推送到聊天工具，  钱啊。现在没用

**Comment by fl20002** [comment]
求关键词  这么高大上的东西 给我来一份

**Comment by fl20002** [comment]
话说  即使 我把节点 设置成PRO   如果有个用户从高级变成普通    他还是能上高级节点？

这个是不是没得救？

**Comment by Acris** [comment]
@fl20002 没救。 可以自己改SS服务端。

**Comment by fl20002** [comment]
咋改？ 求教程

**Comment by sendya** [comment]
@fl20002 如果之后心情好 也有时间，免费做一个可以控制账户等级的服务端**请不要期望**

**Comment by sendya** [comment]
@fl20002 给你教程了 还不如直接放出服务端 有意义吗这提问

**Comment by fl20002** [comment]
我不懂啊  我还以为有接口  就像设置数据库那样   如果要改代码  那我只能做伸手党了

**Comment by sendya** [comment]
@fl20002 最新版 `shadowsocks-rm` 可能是你需要的东西
地址：[shadowsocks manyuser 安装与对接](https://github.com/sendya/shadowsocks-panel/wiki/shadowsocks-manyuser-%E5%AE%89%E8%A3%85%E4%B8%8E%E5%AF%B9%E6%8E%A5)
