### ISSUE TITLE
Cannot send new password due to a typo

### ISSUE THREAD

**Issue by Yves-X** [sendya/shadowsocks-panel#74]
This is the default option:
(database > options > custom_mail_forgePassword_content_2)
`Dear {nickname}:<br/>Here\'s your new password<br/>(这是你的新密码)<br/><br/>Password: {newPassWord}<br/><br/><b>ATTENTION: PLEASE CHANGE THE PASSWORD AND DELETE THIS EMAIL IMMEDIATELY ALTER LOG IN YOUR ACCOUNT FOR SECURITY PURPOSES.</b><b>请在登录后立即修改密码，并且删除此邮件.</b><br/><br/>Yours, The {SITE_NAME} Team`

In which the `{newPassWord}` should be `{newPassword}`.

It's better to have a simple fix :)

**Comment by sendya** [comment]
1. Open url: `yourdomain.com/setting/system`
2. find `custom_mail_forgePassword_content_2` 
3. clicked `编辑` button
4. modify your forge password content.
5. clicked `立即保存` . done

**Comment by sendya** [comment]
在新版本已经修正这个单词问题，感谢反馈。
