### ISSUE TITLE
后台添加卡号出现数据库报错

### ISSUE THREAD

**Issue by Mkdms** [sendya/shadowsocks-panel#75]
后台添加卡号出现数据库报错，其他邀请码什么的正常。
系统错误如下
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expireTime' in 'field list'

**Comment by sendya** [comment]
程序版本号麻烦提供一下

**Comment by Mkdms** [comment]
用的是言总的https://sendya.me/archives/centos7-nginx-php-mariadb-mysql-install.html  ，panel版本？ 1.10

**Comment by Mkdms** [comment]
@sendya 我还以为你睡了。没敢在TG喊你

**Comment by Acris** [comment]
有没有执行 php index.php install

**Comment by Mkdms** [comment]
@Acris 有的。

**Comment by Mkdms** [comment]
我git pull后 执行了 php index.php install

**Comment by Mkdms** [comment]
@Acris 老版本 1.04
