### ISSUE TITLE
后端shadowsocks-rm manyuser

### ISSUE THREAD

**Issue by fl20002** [sendya/shadowsocks-panel#77]
config.py里面的#BIND IP  里面怎么填写？

import logging
#Config
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'XXXX'
MYSQL_DB = 'ss'

# Pro node 1 true , others false
PRO_NODE = 1

MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333
#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'aes-256-cfb'

#LOG CONFIG
LOG_ENABLE = False
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'

/root/shadowsocks-rm/shadowsocks$ python servers.py
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address

**Comment by Acris** [comment]
@fl20002 #if you want bind ipv4 and ipv6 ' :: '
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'

**Comment by fl20002** [comment]
我的前端和后端在一个VPS上面   这里应该怎么填写？  不懂哇

**Comment by Acris** [comment]
@fl20002 一般0.0.0.0就好了

**Comment by fl20002** [comment]
我就是填写的0000啊  
/root/shadowsocks-rm/shadowsocks$ python servers.py
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address

**Comment by Acris** [comment]
@fl20002 你是不是已经开启了一个服务端？

**Comment by fl20002** [comment]
没啊  我中午刚重装的VPS  才装好前端   现在装的后端

**Comment by fl20002** [comment]
root@host:~# cd shadowsocks-rm/shadowsocks
root@host:~/shadowsocks-rm/shadowsocks# python servers.py
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address
^CTraceback (most recent call last):
  File "servers.py", line 61, in <module>
    main()
  File "servers.py", line 57, in main
    time.sleep(100)
KeyboardInterrupt
root@host:~/shadowsocks-rm/shadowsocks#

**Comment by Acris** [comment]
@fl20002 检查下你SS服务的端口是不是和本地的有冲突

**Comment by fl20002** [comment]
前端就我一个人  端口18000  会和什么冲突？   改成48000  一样的错误

**Comment by sendya** [comment]
SS_BIND_IP 怎么写的？

**Comment by fl20002** [comment]
#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'aes-256-cfb'

**Comment by sendya** [comment]
用 `ip addr show eth0` 或者 `ipconfig` 看一下IP地址 有几组

用 `netstat –apn | grep 23333` 或者你绑定的端口
发出来

**Comment by sendya** [comment]
IP记得打码

**Comment by fl20002** [comment]
/$ ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:16:3c:8f:b1:80 brd ff:ff:ff:ff:ff:ff
    inet 1.2.2.2/24 brd 1.2.2.2 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3cff:fe8f:b180/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by fl20002** [comment]
/$ netstat –apn | grep 23333
/$ netstat –apn | grep 48000

**Comment by sendya** [comment]
@fl20002 没结果？？

**Comment by sendya** [comment]
有几张网卡

**Comment by fl20002** [comment]
/$ netstat –apn | grep 23333
没有返回
就一个eth0

**Comment by sendya** [comment]
那我也不知道了。

**Comment by Acris** [comment]
bind ip换成你VPS的IP试试

**Comment by fl20002** [comment]
提供一个 systemd 服务脚本，写进 /etc/systemd/system/shadowsocks-py.service

没有这个文件  是自己新建一个吗?

**Comment by sendya** [comment]
@fl20002 是

**Comment by fl20002** [comment]
脚本写好  supervisor进程守护   也写好了 

放那就行  还是要输入什么命令？  小白不懂

**Comment by sendya** [comment]
@fl20002 恕我没时间教你使用Linux ，自己想办法

**Comment by fl20002** [comment]
shadowsocks-rss manyuser   一切正常

这个RM  为啥就是不行呢   我又找了一台VPS  装RSS正常  删了装RM  就是报错误   奇了怪了

**Comment by fl20002** [comment]
root@host:~/shadowsocks/shadowsocks# python servers.py
python: can't open file 'servers.py': [Errno 2] No such file or directory
root@host:~/shadowsocks/shadowsocks# python server.py
INFO: loading config from config.json
shadowsocks
2016-04-30 10:04:41 ERROR    [Errno 98] Address already in use
Traceback (most recent call last):
  File "/root/shadowsocks/shadowsocks/server_pool.py", line 64, in _loop
    mgr.add_to_loop(loop)
  File "/root/shadowsocks/shadowsocks/asyncmgr.py", line 49, in add_to_loop
    self._sock.bind((Config.MANAGE_BIND_IP, Config.MANAGE_PORT))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
Unhandled exception in thread started by <function _loop at 0x7fb1892192a8>
Traceback (most recent call last):
  File "/root/shadowsocks/shadowsocks/server_pool.py", line 71, in _loop
    os.exit(0)
AttributeError: 'module' object has no attribute 'exit'
2016-04-30 10:04:41 INFO     db start server at port [18000] pass [1024]
2016-04-30 10:04:41 INFO     start server at 18000


原版的也报[Errno 98] Address already in use   这个错误   但是能用

**Comment by fl20002** [comment]
root@host:~/shadowsocks-rm/shadowsocks# python servers.py
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 151, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 59, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 49, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
WARNING:root:db thread except:timed out

**Comment by Acris** [comment]
@fl20002 看错误信息好像是连接数据库超时

**Comment by fl20002** [comment]
不可能啊  三个后端   其他2个都行  就RM不行。。。

**Comment by sendya** [comment]
@fl20002

**Comment by wulv** [comment]
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 207, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 110, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
WARNING:root:db thread except:<urlopen error [Errno -2] Name or service not known>
^CTraceback (most recent call last):
  File "servers.py", line 63, in <module>
    main()
  File "servers.py", line 59, in main
    time.sleep(100)
KeyboardInterrupt

**Comment by sendya** [comment]
@wulv 请使用 https://github.com/Acris/shadowsocks-rm  请勿修改 `PANEL_VERSION` 参数
