### ISSUE TITLE
SMTP的改进

### ISSUE THREAD

**Issue by frankwei98** [sendya/shadowsocks-panel#79]
我用的是SendCloud
SMTP的username是没有"@"符号的
导致系统发信会提示这个:

> The header 'From' expects to be email, string ' **用户名** ' given.

希望能够改进 不是所有邮箱的SMTP用户名都是邮箱地址

**Comment by Acris** [comment]
@frankwei98 下个版本修复

**Comment by sendya** [comment]
SendCloud 是什么玩意，我只会写SMTP阿

**Comment by sendya** [comment]
人呢 @frankwei98 你倒是提供一下网站啊，这玩意真没听过。

**Comment by freejishu** [comment]
SendCloud发送邮件之前内容模板（框架）比如通过审核，否则是发不出去的。
你肯定是没过审核导致的错误。把邮件内容框架提交审核一下应该可以解决

**Comment by frankwei98** [comment]
抱歉各位  刚刚去试用飞机杯了（笑

@sendya 
SendCloud的网站 https://sendcloud.sohu.com
目前我只是在Localhost上搭建来做试验 没有在互联网上的网站

@freejishu 好吧 我更新了最新版 的确没提示

> The header 'From' expects to be email, string ' 用户名 ' given.

我自己研究看看
