### ISSUE TITLE
如何更新旧版本呢?

### ISSUE THREAD

**Issue by maoshublog** [sendya/shadowsocks-panel#80]
如题,假如我的是1.03版本要更新到1.1版本如何才能无损更新到1.1

**Comment by Acris** [comment]
1、备份数据库
2、下载最新版本覆盖旧版本
3、执行 php index.php install
4、如无意外，升级完成。

**Comment by sendya** [comment]
@maoshublog 若无问题，请关闭issue。有问题请继续提出 （2小时候将关闭）
