### ISSUE TITLE
Trying to install

### ISSUE THREAD

**Issue by meetec** [sendya/shadowsocks-panel#81]
I have LEMP installed and i think that I do everything in tutorial.
But I get error:
Warning: require(/home/wwwroot/shadowsocks-panel/Package/autoload.php): failed to open stream: No such file or directory in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

Fatal error: require(): Failed opening required '/home/wwwroot/shadowsocks-panel/Package/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/wwwroot/shadowsocks-panel/Public/index.php on line 16

**Comment by meetec** [comment]
I resolved issues.
First make database sspanel and then again > php index.php install
but now need to deal with .... http://localhost/Public/auth/login

**Comment by meetec** [comment]
I edit /etc/nginx/sites-available/default and do this
- changed root folder of site from default /var/www/html to /home/wwwroot/shadowsocks-panel/Public
- changed server name to my IP address or domain name.
I put symbolic link of phpmyadmin in folder to.

**Comment by meetec** [comment]
I don't get is how to make first account? Admin account?

**Comment by meetec** [comment]
I used invite code to make an account. Is there option for second language?

**Comment by Acris** [comment]
@meetec Hello, currently we have no plan to support second language.

**Comment by meetec** [comment]
@Acris 
I can do translation to English, but I need help.

**Comment by sendya** [comment]
@meetec Willing to answer

**Comment by meetec** [comment]
@Acris Where to start? It will be another Template or?

**Comment by Acris** [comment]
@meetec I'm very sorry. We developed the shadowsocks-panel is just for Chinese users, so at this time our program don't have i18n module. If you want to translate it to English, you need change many source code, it will be a hard work. We also don't have a plan to support other languages in the future.

**Comment by meetec** [comment]
@Acris Then I need to start as soon as possible.

**Comment by meetec** [comment]
But how to sync with your changes of code?

**Comment by Acris** [comment]
@meetec You can fork this repo.

**Comment by Acris** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by meetec** [comment]
I fork repo and start editing.

**Comment by TChenQuan** [comment]
666666666666666666666

**Comment by gucabansimon** [comment]
hello. i have problem with install.

sucessfully installed at vip.omayan.com

but cannot login 404 not found
