### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by meetec** [sendya/shadowsocks-panel#83]
Hi guys,
I have made tree ss servers, all users are using same port and password. In the front of tree server I put HAproxy as load balance and that is working great. People is connection on that HAproxy and I redirect them to ss servers.
But If I want to put this panel multiple ports, users, etc.
How can I configure HAproxy to redirect tcp to ss servers if I use multiple ports?
any idea....

**Comment by Acris** [comment]
@meetec Maybe you should add all of your shadowsocks ports to HaProxy configure file. There have a Python script to help you do this : https://github.com/HoshinoTouko/ha-ss-autogen

**Comment by meetec** [comment]
Thanks @Acris I will try to do that.
