### ISSUE TITLE
后台流量显示有问题

### ISSUE THREAD

**Issue by tuutoo** [sendya/shadowsocks-panel#86]
如图。
![image](https://cloud.githubusercontent.com/assets/9068314/15036705/8be24a14-12c5-11e6-9a0d-590a0d98ad72.png)

![image](https://cloud.githubusercontent.com/assets/9068314/15036717/b3517d40-12c5-11e6-9206-5f98de7560d5.png)

**Comment by Acris** [comment]
更新最新版本，此问题已修复。

**Comment by sendya** [comment]
暂时不准备弄这个功能，可以先无视。
