### ISSUE TITLE
安装完毕后无法访问网站php fatal错误

### ISSUE THREAD

**Issue by rqd1995** [sendya/shadowsocks-panel#89]
按照教程成功安装后，访问页面显示500错误。日志中记录如下：
PHP Fatal error:  Unknown: Failed opening required '/data/www/shadowsocks-panel/Public/index.php' (include_path='.:') in Unknown on line 0
同时收到本地邮件内容如下：
From root@VM_0_242_centos.localdomain  Mon May  9 14:34:01 2016
Return-Path: <root@VM_0_242_centos.localdomain>
X-Original-To: root
Delivered-To: root@VM_0_242_centos.localdomain
Received: by VM_0_242_centos.localdomain (Postfix, from userid 0)
        id ED04B6C1B3; Mon,  9 May 2016 14:34:01 +0800 (CST)
From: "(Cron Daemon)" <root@VM_0_242_centos.localdomain>
To: root@VM_0_242_centos.localdomain
Subject: Cron <root@VM_0_242_centos> /usr/vin/curl https://xxxxxx.com/cron
Content-Type: text/plain; charset=ANSI_X3.4-1968
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=500>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=C>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20160509063401.ED04B6C1B3@VM_0_242_centos.localdomain>
Date: Mon,  9 May 2016 14:34:01 +0800 (CST)

/bin/sh: /usr/vin/curl: No such file or directory

求解决方法！非常感谢！

**Comment by sendya** [comment]
@rqd1995 php.ini 配置文件中

`;open_basedir =`
将 open_basedir 配置屏蔽，重启php

**Comment by rqd1995** [comment]
本身就是注释掉的，重启了php也没有用，还是不行

**Comment by sendya** [comment]
@rqd1995 php版本号，系统版本 发出来。

**Comment by rqd1995** [comment]
centos7，php5.6

**Comment by sendya** [comment]
@rqd1995 能详细提供 php.ini    include_path 参数吗?或者说是否有配置该参数

**Comment by rqd1995** [comment]
; UNIX: "/path1:/path2"
;include_path = ".:/php/includes"
;
; Windows: "\path1;\path2"
;include_path = ".;c:\php\includes"
;
; PHP's default setting for include_path is ".;/path/to/php/pear"
; http://php.net/include-path

; The root of the PHP pages, used only if nonempty.
; if PHP was not compiled with FORCE_REDIRECT, you SHOULD set doc_root
; if you are running php as a CGI under any web server (other than IIS)
; see documentation for security issues.  The alternate is to use the
; cgi.force_redirect configuration below
; http://php.net/doc-root
doc_root =

**Comment by sendya** [comment]
@rqd1995 php是怎么装的?自己编译还是？

**Comment by rqd1995** [comment]
用的lamp一键安装包，其他程序运行都正常

**Comment by sendya** [comment]
@rqd1995 抱歉 一键安装包 可能出现任何未知情况，无法给予帮助，烦请自行查询PHP是否开启了 防站点目录跨站 /文件夹权限 等配置。

**Comment by rqd1995** [comment]
那我自己编译安装一下？需要什么编译参数？

**Comment by sendya** [comment]
@rqd1995 https://github.com/sendya/shadowsocks-panel/wiki/Shadowsocks-Panel-%E9%9D%A2%E6%9D%BF%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B#lnmp

**Comment by sendya** [comment]
@rqd1995 lamp 看看虚拟目录内是否有 `.htaccess` 文件，是否有配置 php_value include_path 等信息。 并且本程序建议使用nginx+php-fpm+mysql

**Comment by rqd1995** [comment]
谢谢，我再折腾折腾有问题再发issue
