### ISSUE TITLE
hanging dns lug.ustc.edu.cn

### ISSUE THREAD

**Issue by meetec** [sendya/shadowsocks-panel#90]
Hi,
I have dns problem (not allways) with lug.ustc.edu.cn geting image for user
and wait for fonts.lug.ustc.edu.cn

**Comment by Acris** [comment]
@meetec Hello, you can change fonts.lug.ustc.edu.cn to fonts.googleapis.com

**Comment by meetec** [comment]
Ok. now it is good. Thanks
