### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by meetec** [sendya/shadowsocks-panel#91]
Hi, 
can you tell me why Data folder have 777 access is it bad for security?
Why the Template folder is created in Data folder?
When you something change in code you need to delete that "Template folder" to rebuild site?
Thanks

**Comment by kookxiang** [comment]
1. Data folder need 777 is because we needs to write data to it and need to list file inside it.

    If everyone can login via SSH, yeah, everyone can change it, it is bad, but it's nothing to do with this application.

2. Because it need to be write somewhere anyway.
3. No, the framework can detect it if you change template file and rebuild the change file.

**Comment by meetec** [comment]
Thanks
