### ISSUE TITLE
新生成邀请码 注册完毕后默认是停用状态

### ISSUE THREAD

**Issue by Mkdms** [sendya/shadowsocks-panel#92]
**PHP** ：  7.0.5  有装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： 否

发生事情时间:2016/5/11 大约晚上19：30 问题；新生成邀请码 注册完毕后默认是停用状态 面板版本为：v1.12

**Comment by Mkdms** [comment]
数据库等其他设置均为改动过

**Comment by sendya** [comment]
@Mkdms

**Comment by Mkdms** [comment]
@sendya git clone 嗯。 是我自己犯傻 git dev的分支 问题已经解决了。
