### ISSUE TITLE
shadowsocks-rm hanging

### ISSUE THREAD

**Issue by meetec** [sendya/shadowsocks-panel#93]
```python
import logging

#Config
MYSQL_HOST = 'remoteserverIP'
MYSQL_PORT = 3306
MYSQL_USER = 'usermysql'
MYSQL_PASS = 'xxxxxxxxxx'
MYSQL_DB = 'sspanel'

# Pro node 1 true , others false
PRO_NODE = 0

MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333
#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'aes-256-cfb'

#LOG CONFIG
LOG_ENABLE = False
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'
```

/shadowsocks-rm/shadowsocks# python servers.py

Nothing ???

After Crtl+C

^CTraceback (most recent call last):
  File "servers.py", line 61, in <module>
    main()
  File "servers.py", line 57, in main
    time.sleep(100)
KeyboardInterrupt

Is there something I can do?

**Comment by Acris** [comment]
@meetec Can you connect to your remote database server on your shadowsocks server?

**Comment by meetec** [comment]
@Acris yes I can connnect,
I wrote some script to try connection and that part is for shure.

**Comment by meetec** [comment]
import cymysql
conn = cymysql.connect(host='XXREMOTEIPXXX', user='usermysql', passwd='xxxxxx', db='sspanel', charset='utf8')
cur = conn.cursor()
cur.execute("SELECT email FROM member")
for r in cur.fetchall():
   print(r)

cur.close()
conn.close()

And I get emails as output

**Comment by sendya** [comment]
```python
LOG_ENABLE = True
```
```shell
cat /var/log/shadowsocks.log
```

**Comment by meetec** [comment]
2016, May 12 Thu 01:29:25 eventloop.py[line:251] DEBUG using event model: epoll
2016, May 12 Thu 01:29:26 dbtransfer.py[line:149] INFO db loop

**Comment by sendya** [comment]
There is no error.
Check the `member` table `enable = 1` (mysql)

**Comment by meetec** [comment]
Yes ... That's It

BIG Thanks

**Comment by Acris** [comment]
@meetec What's your shadowsocks-panel's version? release or dev branch?

**Comment by meetec** [comment]
First it was 1.1 but I change code to v1.12 release.
I fork repo because need to translate panel but I only work on your master branch.

**Comment by Acris** [comment]
@meetec Can you give a screenshot for your member table's data (Do not disclose your password)?

**Comment by meetec** [comment]
This is after I change in table enable to 1
![capture](https://cloud.githubusercontent.com/assets/6350423/15205682/b9801006-1819-11e6-8629-cfe8e3e9b2cd.PNG)

**Comment by meetec** [comment]
When I opened Admin> User managment
all two users revert enable to Disabled
Then I edit user in panel change to <Enable> ...  now in database I see `enable = 1`

**Comment by Acris** [comment]
The shadowsocks-rm still keep hanging when you set `enable = 1` ?

**Comment by meetec** [comment]
@Acris No. Work's fine.

**Comment by Acris** [comment]
@meetec Nice. When user has expired then cron task will set enable to 0.

**Comment by meetec** [comment]
@Acris I see cron is reverting to 0... Now is't again disable! lol
What is best procedure to renew membership.

**Comment by Acris** [comment]
@meetec You can use Package card feature on admin dashboard.

**Comment by meetec** [comment]
@Acris I did't get how to use "card feature" in your panel, probably I was lost in translation :).
Can you explain to me how card feature works?

**Comment by Acris** [comment]
@meetec Go to http://yourdomain.com/admin/card , you can add fourth type cards. The first one called 'Package card', in this type you can set different level (A/B/C/D/VIP) and Expiry Date for each package.  User can active card in http://yourdomain.com/member/actCard. For example, you added a card which level is C and expiry date is 30days, when user activated this card, user's level will change to C and his expiry time will add 30 days.

**Comment by meetec** [comment]
@Acris ok, I get it for first card.
Package card is card that have "level of access" and "expiry date".
Traffic card have "amount of flow GB".
"Trail card" - third card is to prolong test period? 
"Balance card" - fourth card is ...?

**Comment by meetec** [comment]
@Acris I figured out what it's for the fourth card "Balance card", it is to add money to account.
How can I change user plan from Fix data plan to C package 30 days?

**Comment by Acris** [comment]
@meetec fix data plan?

**Comment by meetec** [comment]
@Acris I translated Z plan in "Fix data plan" sorry.

**Comment by Acris** [comment]
@meetec By default, Z plan's expiry time is one year, and can't change to A/B/C/D/VIP.

**Comment by meetec** [comment]
@Acris And after that one year I just add GB to account and that user will have one year more?

**Comment by Acris** [comment]
@meetec Yes.

**Comment by meetec** [comment]
@Acris I said that I'm working on the english translation. Now I see that you update to v1.13.
But I was wondering which is the best way to update my panel?
First I sync my repository with yours.
And then ....

**Comment by Acris** [comment]
@meetec It's a hard work. Maybe we will and i18n support in the future. At this time you need manually merge the code.

**Comment by meetec** [comment]
@Acris I finished 70% of the work. I think I'll end up in a few days.

**Comment by kookxiang** [comment]
Now you can just run the following commands to update your branch:
```shell
git origin add upstream https://github.com/sendya/shadowsocks-panel.git
git fetch origin
git rebase origin/master
```

We'll have a i18n support in framework soon, but there's problems with front-end resources. So the i18n support will be delayed.

**Comment by meetec** [comment]
Hi guy,
can you tell me where can I look to change this part
5GB (free)
100GB (13RMB) 
200GB (20RMB) 
500GB (35RMB) 

thanks

**Comment by sendya** [comment]
@meetec Database  `Options` table  OR  URL: http://yourdomain.com/admin/message

**Comment by meetec** [comment]
@sendya In `Option` I found `custom_plan_name` to change name
In `Option` I found `custom_transfer_level` for transfer level
but I can not find 13RMB or 35 RMB in code or database.

**Comment by sendya** [comment]
@meetec Try to http://yourdomain.com/admin/message

**Comment by sendya** [comment]
If you want to modify the default values , change file `/shadowsocks-panel/Migrations/20160406101714_table_default_db.php` Line:  73 - 115

**Comment by meetec** [comment]
@sendya 
I see now in `/shadowsocks-panel/Migrations/20160406101714_table_default_db.php`
you are inserting in table `message`.
I found in table `message` that code.
Thanks
