### ISSUE TITLE
代理连不上

### ISSUE THREAD

**Issue by fl20002** [sendya/shadowsocks-panel#96]
## 环境
**PHP** ：  7.0.5  无`OpCache`
**NGINX** ： 1.10.0
**MYSQL** ： 5.7
**是否为升级程序** ： 否
前端后端在同一个VPS上面，网站正常，页面正常
## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_
root@host:~/shadowsocks-rm/shadowsocks# python servers.py
add: {"server_port": 41000, "password":"1024", "method":"aes-256-cfb"}

到这一步了     前面都正常    但是就是连不上  打开百度  提示  500 Internal Privoxy Error

应该怎么查？

**Comment by fl20002** [comment]
2016, May 13 Fri 10:21:08 eventloop.py[line:251] DEBUG using event model: epoll
2016, May 13 Fri 10:21:09 dbtransfer.py[line:149] INFO db loop
2016, May 13 Fri 10:21:09 dbtransfer.py[line:136] INFO db start server at port [41000] pass [1024]
2016, May 13 Fri 10:21:09 manager.py[line:86] INFO adding server at 0.0.0.0:41000
2016, May 13 Fri 10:21:24 dbtransfer.py[line:149] INFO db loop
2016, May 13 Fri 10:21:39 dbtransfer.py[line:149] INFO db loop
2016, May 13 Fri 10:21:54 dbtransfer.py[line:149] INFO db loop

**Comment by sendya** [comment]
没有任何问题，检查你自己的客户端设置问题

**Comment by fl20002** [comment]
iptables的锅    关了就可以   

现在有个新问题   

普通用户升级到VIP用户，能用PRO节点，能正常使用， 但是页面上面还是显示的无权使用

**Comment by sendya** [comment]
@fl20002 认真看提示，明明写过升级套餐后需要重新登录。
