### ISSUE TITLE
问个小白问题 

### ISSUE THREAD

**Issue by fl20002** [sendya/shadowsocks-panel#97]
1：supervisor已经设置运行正常了，这个systemd脚本是什么作用？还用搞吗

2：某个用户改了端口以后，是不是一定要重启下supervisor才能把原来的端口关掉？ 我现在试验，不重启，新旧2个端口都能用。。。

万分感谢！

**Comment by Acris** [comment]
@fl20002 1、有了supervisor就不要systemd。
2、不用

**Comment by fl20002** [comment]
针对2
是我哪里设置不对吗？  改了端口以后，用户列表那里端口信息都更新了，但是旧的还是一直能用

**Comment by Acris** [comment]
@fl20002 改了端口不是立即生效的，你可以看一下后端日志。

**Comment by Acris** [comment]
@fl20002 大概15秒~30秒就生效了,旧端口也会被移除.

**Comment by fl20002** [comment]
我等了5分钟   还是不行。。。
哪里的问题？   改了端口，页面，数据库里面都更新了

**Comment by fl20002** [comment]
我试了下  用户从VIP变为普通   端口都能关闭  再变回来 ，又恢复正常

这个都可以  为啥改端口 就不能关闭原来的？

**Comment by sendya** [comment]
@fl20002 你为什么要改SS端口呢请问？ 是什么需求驱使你去改端口？

**Comment by fl20002** [comment]
既然可以这样  我就想试试看行不行

强迫症

**Comment by sendya** [comment]
@fl20002 咋不试试炸服务器

**Comment by fl20002** [comment]
我之前提问不少，给我的感觉Acris回答的耐心，你每次都是一份高高在上的，嘲讽的语气
如果你不愿意回答  可以不回答  或者直接关闭，或者直接告诉我 爱用用不用滚。
用不着这样嘲讽一个小白，没必要这么秀优越

**Comment by sendya** [comment]
哦？ 那我就这么回复吧。
