### ISSUE TITLE
邮箱验证问题

### ISSUE THREAD

**Issue by lezaijjh** [sendya/shadowsocks-panel#98]
## 环境
**PHP** ：  7.0.5  有/无装`OpCache`
**NGINX** ： 1.9.15
**MYSQL** ： 5.6
**是否为升级程序** ： NO

## 问题/错误信息
_（一般为页面输出结果，或开启DEBUG后的报错）_

使用新版进行邮箱校验测试，注册邮箱收到如下邮件，无任何内容只包含一个txt附件 其中附件txt内容为空
[http://lezaitest.oss-cn-hangzhou.aliyuncs.com/BaiduShurufa_2016-5-14_14-17-19.png](url)

**Comment by lezaijjh** [comment]
http://lezaitest.oss-cn-hangzhou.aliyuncs.com/BaiduShurufa_2016-5-14_14-17-19.png

**Comment by kookxiang** [comment]
请将邮件原文贴出来以便分析，例如 Gmail / Inbox：
![image](https://cloud.githubusercontent.com/assets/2725379/15266862/5093f004-19e4-11e6-96c8-153bdf8b6d7d.png)

**Comment by lezaijjh** [comment]
Received: from smtp545-122.mail.xxx.com. (unknown [202.108.3.165])
	by mx22 (Coremail) with SMTP id 08mowAAX07C1wTZX2X5RAQ--.36347S2;
	Sat, 14 May 2016 14:12:05 +0800 (CST)
Received: from 11.11.111.11.vultr.com (HELO sendmail)([11.11.111.11])
	by xxx.com with ESMTP
	14 May 2016 14:12:04 +0800 (CST)
X-Sender:xx@xx.com
X-Auth-ID: xx@xx.com
X-SMAIL-MID: 5438905767243
FROM: SS <xx@xx.com>
TO: <xxx@126.com>
Subject: =?UTF-8?B?W+enr+acqFNT572R57uc5Yqg6YCf5ZmoXSDmlrDotKbmiLfms6jlhozpgq7nrrHmoKHpqow=?=
Content-Type: multipart/mixed;
	boundary="----=_Part_aaa65d6d95464230831e0adb8ad82d4f5736c1ad1bcdf"
MIME-Version: 1.0
X-CM-TRANSID:08mowAAX07C1wTZX2X5RAQ--.36347S2
Message-Id:<5736C1B5.A9EC28.21629@m15-147.126.com>
Authentication-Results: mx22; spf=pass smtp.mail=xx@xx.com;
X-Coremail-Antispam: 1Uf129KBjDUn29KB7ZKAUJUUUUU529EdanIXcx71UUUUU7v73
	VFW2AGmfu7bjvjm3AaLaJ3UbIYCTnIWIevJa73UjIFyTuYvjxUs-txDUUUU
Date: Sat, 14 May 2016 14:12:05 +0800 (CST)


------=_Part_aaa65d6d95464230831e0adb8ad82d4f5736c1ad1bcdf
Content-Type:text/html; charset=utf-8
Content-Transfer-Encoding: base64


------=_Part_aaa65d6d95464230831e0adb8ad82d4f5736c1ad1bcdf

**Comment by lezaijjh** [comment]
11.11.111.11 xx@xx.com均为马赛克

**Comment by sendya** [comment]
1. 程序是什么版本？
2. 数据库表中`options`表数据 是否存在一条 `custom_mail_verification_content` 字段的数据

**Comment by lezaijjh** [comment]
1.程序1.15
2.没有该字段

**Comment by sendya** [comment]
是否为升级程序 ： NO ？？？？？   全新安装不会出这样的事吧.

**Comment by lezaijjh** [comment]
抱歉==我的数据库是旧的 但文件是全新的

**Comment by sendya** [comment]
issue模板真是白弄了。按照要求填写以下都不行吗...


`php index.php install`　执行了没？

**Comment by lezaijjh** [comment]
执行了的  没有报错

**Comment by sendya** [comment]
@lezaijjh 以后建议每次 releases 时更新程序，不要一直去直接拉取分支。

**Comment by sendya** [comment]
@lezaijjh 在数据库里执行 delete phinxlog where version='20160509011415'

**Comment by lezaijjh** [comment]
可爱的是我的phinxlog表中没有 version='20160509011415'的数据

**Comment by sendya** [comment]
@lezaijjh php index.php install 执行结果发出来

**Comment by lezaijjh** [comment]
十分感谢您的帮助 但由于某些原因 我可能会稍晚再继续操作 请不要关闭本issue 谢谢

**Comment by lezaijjh** [comment]
再install 再删除字段 再install 成功 谢谢
