### ISSUE TITLE
Use of undefined constant PHP_BINARY - assumed 'PHP_BINARY' in /home/wwwroot/shadowsocks-panel/index.php on line 120

### ISSUE THREAD

**Issue by relei1988** [sendya/shadowsocks-panel#99]
## 环境
**PHP** ：  5.3.3  有/无装`OpCache`
**NGINX** ： 1.10.0
**MYSQL** ： 5.6
**是否为升级程序** ： 否

## 问题/错误信息
Use of undefined constant PHP_BINARY - assumed 'PHP_BINARY' in /home/wwwroot/shadowsocks-panel/index.php on line 120

无法安装的样子，cent os 6
麻烦看看有什么办法改进吗

**Comment by kookxiang** [comment]
不支持 PHP 5.3
